
# motion states 
uint8 motion_front_middle
uint8 motion_front_left
uint8 motion_front_right
uint8 motion_left
uint8 motion_right
uint8 motion_back

# Button states
uint8 button_1
uint8 button_2
uint8 button_3
uint8 button_4

# Cliff states
uint8 cliff_middle
uint8 cliff_left
uint8 cliff_right

# Temperature state
float32 temperature

# IR state
float32 ir_front_middle
float32 ir_front_left
float32 ir_front_right
float32 ir_left
float32 ir_right
float32 ir_back

# LED status
string led_status

# UVC status
string uvc_status