#!/usr/bin/env python3

import rospy
import sys
import yaml

# nav_msgs/Odometry
from nav_msgs.msg import Odometry
from std_msgs.msg import Float32 , Int64 , Int64MultiArray , MultiArrayLayout , MultiArrayDimension
from datetime import datetime


distanceyaml = "distance.yaml"


class Distance:
    def __init__(self):
        self.linear = None
        self.angular = None
        self.distance = 0
        self.uptine_accumulate = 0
        self.uptime_last = 0
        self.ini_time_for_now = datetime.now()
        self.ini_time_stamp = datetime.now()
        try:
            stream1 =  open(distanceyaml, "r") #as stream1:
            distance_yaml = yaml.safe_load(stream1)
            odo = distance_yaml['odo']
            self.distance = odo
            
            try :
                self.uptine_accumulate = distance_yaml['uptime']
            except:
                try:
                    file = open(distanceyaml, "a+") #as file:
                    dict_file = {'odo': self.distance , "uptime":self.uptine_accumulate}
                    # print("update")
                    document = yaml.dump(dict_file, file)
                    file.close()
                except yaml.YAMLError as exc:
                    print(str(exc))
            # print(odo)
            
            stream1.close()
        except :
            try:
                file = open(distanceyaml, "a+") #as file:
                dict_file = {'odo': self.distance , "uptime":self.uptine_accumulate}
                # print("update")
                document = yaml.dump(dict_file, file)
                file.close()
            except yaml.YAMLError as exc:
                print(str(exc))

        self.speed = rospy.Subscriber(
            'odom',
            Odometry,
            self.speed_callback)

        self.odo_pub = rospy.Publisher(
            'odo',
            Float32, queue_size=10
        )

        # self.uptime_last_pub = rospy.Publisher(
        #     'uptime_last',
        #     Int64, queue_size=10
        # )

        # self.uptime_accumulate_pub = rospy.Publisher(
        #     'uptime_accumulate',
        #     Int64, queue_size=10
        # )

        self.uptime_all_pub = rospy.Publisher(
            'uptime_all',
            Int64MultiArray, queue_size=10
        )

        rospy.loginfo('Distance Init')

    def speed_callback(self, msg):
        self.linear = msg.twist.twist.linear.x
        self.angular = msg.twist.twist.angular.z

        time = datetime.now()
        diff = time - self.ini_time_for_now
        diff2 = time - self.ini_time_stamp

        # print("Diff: "+str(round(diff.total_seconds(),3)))
        if (round(diff.total_seconds(), 3) > 0.01):
            # print("Cal")
            # print("Ang:" + str(round(abs(self.angular),1)))
            # print("Linear:" + str(round(abs(self.linear),1)))
            if (round(abs(self.linear), 1) > 0.0):
                self.distance += round(abs(self.linear), 2) * \
                    round(diff.total_seconds(), 3)
            elif (round(abs(self.angular), 1) > 0.0):
                self.distance += round(abs(self.angular), 2) * \
                    round(diff.total_seconds(), 3)
            # print("Distance: "+str(self.distance))
            # print("Diff2: "+str(round(diff2.total_seconds(),1)))
            if (round(diff2.total_seconds(), 3) > 1):
                self.uptine_accumulate += round(diff2.total_seconds(), 3)
                self.uptime_last += round(diff2.total_seconds(), 3)
                try:
                    file = open(distanceyaml, "w") #as file:
                    dict_file = {'odo': self.distance,"uptime":self.uptine_accumulate}
                    # print("update")
                    document = yaml.dump(dict_file, file)
                    file.close()
                except yaml.YAMLError as exc:
                    print(str(exc))
                self.ini_time_stamp = time

                state_uptime_last = Int64()
                state_uptime_last.data = int(self.uptime_last)
                # self.uptime_last_pub.publish(state_uptime_last)

                state_uptime_accumulate = Int64()
                state_uptime_accumulate.data = int(self.uptine_accumulate)
                # self.uptime_accumulate_pub.publish(state_uptime_accumulate)

                
                dim = MultiArrayDimension()
                dim.label = "Uptime Acc"
                dim2 = MultiArrayDimension()
                dim2.label = "Uptime last"

                layout = MultiArrayLayout()
                layout.dim = [dim,dim2]

                label = ["Uptime Acc" , "Uptime Last"]
                state_uptime_all = Int64MultiArray()
                state_uptime_all.layout = layout

                state_uptime_all.data = [int(self.uptine_accumulate/3600) , int(self.uptime_last/3600) ]
                self.uptime_all_pub.publish(state_uptime_all)

            state = Float32()
            state.data = self.distance/1000
            self.odo_pub.publish(state)
            self.ini_time_for_now = time

            # state_uptime_last = Int64()
            # state_uptime_last.data = int(self.uptime_last)
            # # self.uptime_last_pub.publish(state_uptime_last)

            # state_uptime_accumulate = Int64()
            # state_uptime_accumulate.data = int(self.uptine_accumulate)
            # # self.uptime_accumulate_pub.publish(state_uptime_accumulate)

            
            # dim = MultiArrayDimension()
            # dim.label = "Uptime Acc"
            # dim2 = MultiArrayDimension()
            # dim2.label = "Uptime last"

            # layout = MultiArrayLayout()
            # layout.dim = [dim,dim2]

            # label = ["Uptime Acc" , "Uptime Last"]
            # state_uptime_all = Int64MultiArray()
            # state_uptime_all.layout = layout

            # state_uptime_all.data = [int(self.uptine_accumulate/3600) , int(self.uptime_last/3600) ]
            # self.uptime_all_pub.publish(state_uptime_all)

        # print("Linear: "+str(self.linear)+" Ang: "+str(self.angular))
        # rospy.loginfo("Linear: "+str(self.linear)+" Ang: "+str(self.angular))
        return


def main(argv=sys.argv):

    rospy.init_node('matrix_stamp_distance', anonymous=True)
    Distance()
    rospy.spin()

    # rospy.shutdown()


if __name__ == '__main__':
    main()
