# goal definition 

string check_charger_end=check_charger_end
string backward=backward
string cmd
                    #             cmd = check_charger_end                               cmd = backward  
string arg0_str     #detect charger_end                                                 ""
string arg1_str     #detect switch                                                      ""
uint64 arg0_uint     #schedule Hour 24hour format                                        0
uint64 arg1_uint     #schedule Minute                                                    0
float64 arg0_float  #                                                                   distance (backward mode)
float64 arg1_float  #                                                                   max_vel (backward mode)
bool arg0_bool      #if false = set timmer char, true = set schedule                    false
---
# results definition
uint8 SUCCESS                   = 0
uint8 TIMEOUT                   = 1
uint8 CMD_NOTFOUND              = 2
uint8 TIMMER_LATE               = 3
uint8 PREEMPT                   = 4        

uint8 SERIAL_CON_MATCH          = 10
uint8 BATTERY_STATE_DIS         = 11
uint8 TIMMER_FINISH             = 12
uint8 SCHEDULE_FINISH           = 13

uint8 result
string text

---
# feedback definition
uint8 sequence
string text
uint64 timeout