string up_check_obj="up_check_obj"
string up_skip_obj="up_skip_obj"
string down="down"
string stop="stop"
string rst="rst"

string cmd
int64 timeout

-------------
# result definition

uint8 pending = 0
uint8 manualInterupt = 1
uint8 limitH_NotcloseOBJ = 2
uint8 limitH_closeOBJ = 3
uint8 limitL = 4
uint8 limitL_NotcloseOBJ = 5
uint8 limitL_closeOBJ = 6
uint8 ctrlStateErr = 7
uint8 notFoundOBJ = 8
uint8 mstop = 9
uint8 overload = 10
uint8 emer_active = 11

uint8 liftBusy = 20
uint8 waitDataTimeout = 21
uint8 controlTimeout = 22
uint8 cmd_not_found = 23


uint8 result
string text
uint8 sequence

-------------
# feedback definition
uint8 sequence
string text
uint64 timeout