#!/usr/bin/env python3

import math
from math import sin, cos, pi

import rospy
import tf
from nav_msgs.msg import Odometry
from geometry_msgs.msg import *
from std_srvs.srv import *
from sensor_msgs.msg import *
from std_msgs.msg import *
from matrix_msgs.msg import *

from struct import *
import can
from can import *
from can_msgs.msg import *
import time
import sys
import os
from enum import Enum

# from dataclasses import dataclass


class UpdateOdom:
    def __init__(self):
        
        self.node_name = "keya_odometry"
        rospy.init_node(self.node_name)

        # canbus read param
        if not rospy.has_param("~device_name"):
            rospy.set_param("~device_name", "LSD300") 
        if not rospy.has_param("~dual_driver_motor"):
            rospy.set_param("~dual_driver_motor", False) 
        if not rospy.has_param("~use_matrix_navgo_bypass"):
            rospy.set_param("~use_matrix_navgo_bypass", False)
        if not rospy.has_param("~can_device"):
            rospy.set_param("~can_device", "can0")
        if not rospy.has_param("~canbus_bitrate"):
            rospy.set_param("~canbus_bitrate", 500000)
        if not rospy.has_param("~dual_motor_id"):
            rospy.set_param("~dual_motor_id", 1)
        if not rospy.has_param("~motor_1_id"):
            rospy.set_param("~motor_1_id", 3)
        if not rospy.has_param("~motor_2_id"):
            rospy.set_param("~motor_2_id", 2)
        if not rospy.has_param("~accel_time"):
            rospy.set_param("~accel_time", 100)
        if not rospy.has_param("~decel_time"):
            rospy.set_param("~decel_time", 100)
        if not rospy.has_param("~velocity_unit_rpm"):
            rospy.set_param("~velocity_unit_rpm", 1)
        self.device_name = rospy.get_param("~device_name")
        self.dual_driver_motor = rospy.get_param("~dual_driver_motor")
        self.use_matrix_navgo_bypass = rospy.get_param("~use_matrix_navgo_bypass")
        self.can_device = rospy.get_param("~can_device")
        self.can_bitrate = rospy.get_param("~canbus_bitrate")
        self.dual_motor_id = rospy.get_param("~dual_motor_id")
        self.motor_1_id = rospy.get_param("~motor_1_id")
        self.motor_2_id = rospy.get_param("~motor_2_id")
        self.accel_time = rospy.get_param("~accel_time")
        self.decel_time = rospy.get_param("~decel_time")
        self.velocity_unit_rpm = rospy.get_param("~velocity_unit_rpm")


        self.ControlState = Enum('ControlState', ['INIT', 'MANUAL_MODE', 'ROBOT_SYSTEM_CHECK', 'MOTOR_STATE_CHECK', 'INIT_MOTOR', 'WAIT_STATUSWORD_ENABLED', 'BASE_CONTROL', 'GET_ACTUAL_VELOCITY', 'FINAL', 'FAULT_CHECKING', 'FAULT_DETECTED', 'CLEAR_FAULT', 'ERROR', 'PAUSE'])
        self.control_state = Enum('control_state', ['INIT', 'CHECK_MANUAL', 'CHECK_AUTO', 'MOVE_AUTO', 'MANUAL_INTERUPT', 'EMERGENCY', 'ERR', 'PAUSE', 'FINISH'])
        self.motion = Enum('motion', ['IDEL', 'STOP', 'UP', 'DOWN', 'RST'])
        self.error_state = Enum('error_state', ['NOT_FOUND_OBJ', 'LIFT_TOO_HIGH', 'LIFT_TOO_LOW', 'CLOSE_OBJ'])
        self.motion_seqs = Enum('motion_seqs', ['check_obj', 'check_env', 'go_stop', 'go_ctrl', 'go_finish'])
        self.motion_results = Enum('motion_results', ['pending', 'manualInterupt', 'limitH_NotcloseOBJ', 'limitH_closeOBJ', 'limitL', 'limitL_NotcloseOBJ', 'limitL_closeOBJ', 'ctrlStateErr', 'notFoundOBJ', 'mstop'])



        self.isSim = False


        self.motor_1_id = 3
 

        self.current_time = rospy.Time.now()
        self.last_time = rospy.Time.now()
        self.message = Frame()

        self.LED_CONTROL_RATE = 1
        self.HB_RATE = 3
        self.IOSTATE_RATE = 10

        self.obj_detector = 0
        self.closer_detector = 0
        self.liml_detector = 0
        self.limh_detector =0
        self.EMO = 0
        self.up_button= 0
        self.down_button = 0

        self.motion_req_goal = self.motion.IDEL.value
        self.motion_req_complete = False
        self.motion_result = 0
        self.motion_seq = 0
        self.motion_ctrl_complete = False

        self.send_result = False

        self.control_seq = 0

        self.isAutoMode = False
        self.isButtonInterupt = True
        self.isSkipCheckOBJ = False
        self.isInitial_Trigger = False
        self.isInitial_Finish = False
        self.isInitial_Success = False
        self.isReset = False


        self.up_stmp_time = 0
        self.down_stmp_time = 0
        self.init_up_stmp = False
        self.init_down_stmp = False

        self.statusword_stmp = 0

        self.up_press_time = 0
        self.down_press_time = 0

        self.prev_led_control_time = 0
        self.prev_hb_time = 0
        self.prev_iostate_time = 0
        self.prev_io_time = 0


        self.motion_req_goalSTR = ""
        # self.inputStringPort = ""


        self.control_seq = self.control_state.INIT.value
        self.motion_req_complete = True

        self.fst_data_come = False
        self.current_motor_state =""
        self.motor_status = DeviceStateCanopen()
        self.ControlState_seq = self.ControlState.INIT.value

        try:
            self.bus = can.Bus(interface='socketcan',
                                channel=self.can_device,
                                receive_own_messages=False,
                                bitrate=self.can_bitrate)

            self.buffer = can.BufferedReader()
            self.notifier = can.Notifier(self.bus, [self._get_message, self.buffer])

        except:
            print("[matrix_CanOpenLifter_LSD100]: cansocket name {} not found.please check list network interfaces".format(self.can_device))
            os.system('ifconfig')
            # sys.exit(0)


        # self.odom_pub = rospy.Publisher("matrix_canopen_motor/" + self.device_name + "/odom", Odometry, queue_size=1)
        self.tx_pub = rospy.Publisher("matrix_canopen_lifter/" + self.device_name + "/tx", String, queue_size=10)
        self.io_state = rospy.Publisher("matrix_canopen_lifter/" + self.device_name + "/io_state", Int8MultiArray, queue_size=5)


        # self.odom_broadcaster = tf.TransformBroadcaster()
        self.rx_sub = rospy.Subscriber("matrix_canopen_lifter/" + self.device_name + "/rx", String, self.callback_rx)
        self.reset_service = rospy.Service("matrix_canopen_lifter/" + self.device_name + "/reset", SetBool, self.callback_reset)
        

        rate = rospy.Rate(20)

        self.NMT_service(0x03, "Switch to the <Operational> state")
        
        while not rospy.is_shutdown():
            # print("cal odom!!")
            # self.calculateOdom()

            self.MainLoopControl()
            # self.manual()

            # print("spped m1 {},  m2 {}".format(self.m1_actual_speed, self.m2_actual_speed))
            rate.sleep()
    
    def _get_message(self, message):

        # request Digital IO input status RO CiA301 decive profile 
        # LD Servo Driver CANOPEN Protocal-en.pdf, Page 56
        # 200Bh/01, Digital IO input status, UINT16, RO
        # print(message)
        if (message.arbitration_id == 0x580 + self.motor_1_id) and (message.dlc == 8) and (message.data[1] == 0x0b):
        # if message.dlc == 8:
            if message.data[2] == 0x20:
                # print(hex(message.data[2]))
                try:
                    binary_str = format(int(message.data[4]), '08b')
                    # print(binary_str)
                    self.closer_detector = int(binary_str[7])
                    self.liml_detector = int(binary_str[6])
                    self.limh_detector = int(binary_str[5])
                    self.EMO = int(binary_str[4])
                    self.up_button= int(binary_str[3])
                    self.down_button = int(binary_str[2])

                    if (rospy.Time.now().to_sec() - self.prev_io_time) >= (1):
                        msg = Int8MultiArray()
                        msg.data = [2, self.up_button, self.down_button, 2, self.closer_detector, self.limh_detector, self.liml_detector, 2, 2, 2, self.EMO]
                        self.io_state.publish(msg)
                        self.prev_io_time = rospy.Time.now().to_sec()

                    self.fst_data_come = True
                    # print("close:{}, liml:{}, limh:{}, re:{}, up:{}, down:{}".format(self.closer_detector, self.liml_detector, self.limh_detector, self.EMO, self.up_button, self.down_button))
                except Exception as e:
                    print(str(e))
        
        if (message.arbitration_id== 0x180 + self.motor_1_id) and (message.dlc == 7):
            # print(hex(message.data[4]) + hex(message.data[5]))
            
            # # rospy.logwarn("status word {} {}".format(hex(message.data[5]), hex(message.data[4])))

            # # message = [0x00, 0x00, 0x00, 0x00, 0x27, 0x13, 0x00, 0x00]
            # # sw_h = bytearray([message.data[4], message.data[5]])
            # # sw_d = unpack('<h', sw_h)
            sw_h = message.data[4]
            # print(sw_h)
            # # sw_d = sw_d[0]
            sw_b = format(sw_h, '#010b')
            # print(sw_b)
            
            self.motor_status.binary = sw_b

            STW_ReadytoSwitchON = int(sw_b[len(sw_b)-1])
            STW_SwitchedON  = int(sw_b[len(sw_b)-2])
            STW_OperationEnabled = int(sw_b[len(sw_b)-3])
            STW_Fault = int(sw_b[len(sw_b)-4])
            STW_VoltageEnabled = int(sw_b[len(sw_b)-5])
            STW_QuickStop = int(sw_b[len(sw_b)-6])
            STW_SwitchONDisabled = int(sw_b[len(sw_b)-7])
            STW_Warning = int(sw_b[len(sw_b)-8])


    


            if not STW_ReadytoSwitchON and not STW_SwitchedON and not STW_OperationEnabled and STW_Fault and not STW_SwitchONDisabled:
                print("Fault")
                # self.MotorSwitched(self.motor_1_id, "Fault Reset")
                self.current_motor_state = "Fault"
                self.motor_status.state = DeviceStateCanopen.STATE_FAULT
                self.ControlState_seq = self.ControlState.FAULT_CHECKING.value
            elif STW_ReadytoSwitchON and STW_SwitchedON and STW_OperationEnabled and STW_Fault and not STW_SwitchONDisabled:
                print("Fault2")
                self.MotorSwitched(self.motor_1_id, "Fault Reset")
                self.current_motor_state = "Fault reaction active"
                self.motor_status.state = DeviceStateCanopen.STATE_FAULT
            elif STW_ReadytoSwitchON and STW_SwitchedON and STW_OperationEnabled and not STW_Fault and not STW_QuickStop and not STW_SwitchONDisabled:
                # print("Fault")
                self.current_motor_state = "Quick stop active"
                # self.motor_status.state = DeviceStateCanopen.STATE_QUICK_STOP_ACTIVE
            elif STW_ReadytoSwitchON and STW_SwitchedON and STW_OperationEnabled and not STW_Fault and STW_QuickStop and not STW_SwitchONDisabled:
                # print("Enabled Operation")
                self.current_motor_state = "Enabled Operation"
                self.motor_status.state = DeviceStateCanopen.STATE_OPERATION_ENABLED
            elif STW_ReadytoSwitchON and not STW_SwitchedON and not STW_OperationEnabled and not STW_Fault and STW_QuickStop and not STW_SwitchONDisabled:
                # print("Enabled Operation")
                self.current_motor_state = "Ready to switch on"
                # self.motor_status.state = DeviceStateCanopen.STATE_OPERATION_ENABLED
            elif STW_ReadytoSwitchON and STW_SwitchedON and not STW_OperationEnabled and not STW_Fault and STW_QuickStop and not STW_SwitchONDisabled:
                # print("Enabled Operation")
                self.current_motor_state = "Switched on"
                # self.motor_status.state = DeviceStateCanopen.STATE_OPERATION_ENABLED
            elif not STW_ReadytoSwitchON and not STW_SwitchedON and not STW_OperationEnabled and not STW_Fault and not STW_SwitchONDisabled:
                # print("Switch ON Disabled")
                self.current_motor_state = "Not ready to switch on"
                # self.motor_status.state = DeviceStateCanopen.STATE_SWITCH_ON_DISABLED
            elif not STW_ReadytoSwitchON and not STW_SwitchedON and not STW_OperationEnabled and not STW_Fault and STW_SwitchONDisabled:
                # print("Switch ON Disabled")
                self.current_motor_state = "Switech on disabled"
                self.motor_status.state = DeviceStateCanopen.STATE_SWITCH_ON_DISABLED
            else:
                # print("UNKNOW")
                self.current_motor_state = "UNKNOW"
                self.motor_status.state = DeviceStateCanopen.STATE_UNKNOW
            
            # print(self.current_motor_state)

            # self.sendData("[6041h_"+str(self.current_motor_state)+"]", 1)

            self.statusword_stmp = rospy.Time.now().to_sec()
            
            

            
            # print("motor state ---- {}, mode {}".format(self.motor_status.text, self.motor_status.state))
            # array = []
            # array.append(message.data[4])
            # array.append(message.data[5])

            # self.motor_status.status_word = array
            
            
 


        return message
    
    def callback_rx(self, msg):
        msg = str(msg)
        startOfLinePort = False
        endOfLinePort = False
        inputStringPort = ""
        completePort = False

        for x in range(len(msg)):
            inChar4 = msg[x]
            # print(inChar4)
            #// char buffer[50];
            if (inChar4 == "#"):
                startOfLinePort = True
            if (startOfLinePort) and (inChar4 == "$"):
                endOfLinePort = True
            if (startOfLinePort) and (inChar4 != "#") and (inChar4 != "$"):
                inputStringPort += inChar4
            if (startOfLinePort) and (endOfLinePort):
                completePort = True
                startOfLinePort = False
                endOfLinePort   = False

        if(completePort):
            # print(inputStringPort)
            self.isSkipCheckOBJ = False

            #For module debug only!!!!!
            # self.isInitial_Finish = True
            # self.motion_req_complete = False
            #

            if(self.isInitial_Finish):
                
                cmd_match = True
                
                if(inputStringPort == ("Tx"+self.device_name+"_UP")):
                    self.motion_req_goal = self.motion.UP.value
                elif(inputStringPort == ("Tx"+self.device_name+"_UP_SkipCheckOBJ")):
                    self.motion_req_goal = self.motion.UP.value
                    self.isSkipCheckOBJ = True
                elif(inputStringPort == ("Tx"+self.device_name+"_DOWN")):
                    self.motion_req_goal = self.motion.DOWN.value
                elif(inputStringPort == ("Tx"+self.device_name+"_DOWN_SkipCheckOBJ")):
                    self.motion_req_goal = self.motion.DOWN.value
                    self.isSkipCheckOBJ = True
                elif(inputStringPort == ("Tx"+self.device_name+"_STOP")):
                    self.motion_req_goal = self.motion.STOP.value
                elif(inputStringPort == ("Tx"+self.device_name+"_RST")):
                    #self.ResetSystem()
                    self.motion_req_goal = self.motion.RST.value
                else:
                    self.motion_req_goal = self.motion.IDEL.value
                    cmd_match = False
                    
                
                if(cmd_match):
                    print("{} Driver: receive new goal --> {}, {}".format(self.device_name, inputStringPort, self.motion_req_goal))
                    if(not self.motion_req_complete):
                        self.sendData("_AcPreemptGoal_["+str(self.motion_req_goalSTR)+"]", 1)
                        self.motion_req_goalSTR = inputStringPort
                        self.sendData("_AcRecvNewGoal_["+str(inputStringPort) +"]", 1)
                    else:
                        self.motion_req_goalSTR = inputStringPort
                        self.sendData("_AcRecvGoal_["+inputStringPort+"]", 1)
                    
                    if(self.motion_req_goal == self.motion.RST.value):
                        self.ResetSystem()
                    
                    
                else:
                    print("{} Driver: cmd miss match --> {}".format(self.device_name, inputStringPort))
                
                self.clear_parameter()
               
                
                print("-----------------------")

           
        
        
            
 
    
    def callback_reset(self, req):
        return True, "LSD100 reset success!!"

    def manual(self):
        self.reqDigitalInputs(self.motor_1_id)
        if (self.up_button == 0) and (self.down_button == 0):
            self.LiftMovement(self.motor_1_id, "STOP")
        elif (self.up_button == 0) and (self.down_button == 1):
            self.LiftMovement(self.motor_1_id, "UP")
        elif (self.up_button == 1) and (self.down_button == 0):
            self.LiftMovement(self.motor_1_id, "DOWN")
        else:
            self.LiftMovement(self.motor_1_id, "STOP")

    def MainLoopControl(self):

        # print(self.ControlState_seq)

        self.checkKeyButtonSpecial()

        if self.ControlState_seq == self.ControlState.INIT.value:
            # self.sendData("[INIT]", 1)
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: INIT")
            self.ControlState_seq = self.ControlState.MOTOR_STATE_CHECK.value
        elif self.ControlState_seq == self.ControlState.MOTOR_STATE_CHECK.value:
            # self.sendData("[MOTOR_STATE_CHECK]", 1)
            self.ControlState_seq = self.ControlState.FAULT_CHECKING.value
        elif self.ControlState_seq == self.ControlState.FAULT_CHECKING.value:
            # self.sendData("[FAULT_CHECKING]", 1)
            if self.current_motor_state == "Fault":
                self.sendData("[CLEAR_FAULT]", 1)
                print("Clear fault")
                self.MotorSwitched(self.motor_1_id, "Fault Reset")
                self.ControlState_seq = self.ControlState.FINAL.value
            else:
                self.ControlState_seq = self.ControlState.INIT_MOTOR.value
        elif self.ControlState_seq == self.ControlState.INIT_MOTOR.value:
            # self.sendData("[INIT_MOTOR]", 1)
            if (self.EMO == 1):
                if(self.current_motor_state != "Enabled Operation"):
                    self.init_Motor(False)
                    self.ControlState_seq = self.ControlState.WAIT_STATUSWORD_ENABLED.value
                else:
                    self.ControlState_seq = self.ControlState.BASE_CONTROL.value
            else:
                self.MotorSwitched(self.motor_1_id, "Disable Voltage")
                self.ControlState_seq = self.ControlState.FINAL.value
        elif self.ControlState_seq == self.ControlState.WAIT_STATUSWORD_ENABLED.value:
            # print("WAIT_STATUSWORD_ENABLED")
            self.sendData("[WAIT_STATUSWORD_ENABLED]", 1)
            if self.motor_status.state == DeviceStateCanopen.STATE_OPERATION_ENABLED:
                self.ControlState_seq = self.ControlState.BASE_CONTROL.value
                self.ResetSystem()
                # self._isMotor_1_OperationEn = True
                # self._isMotor_2_OperationEn = True
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: ************************************************    ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]:                                                     ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: CanOpenMotor orientalBLVD-KRD Ready To Drive!!!     ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]:                                                     ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: *************************************************   ")
        elif self.ControlState_seq == self.ControlState.BASE_CONTROL.value: 
            # self.sendData("[BASE_CONTROL]", 1)
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: BASE_CONTROL")
            # Status Machine in "Operation enabled"
            if self.motor_status.state == DeviceStateCanopen.STATE_OPERATION_ENABLED:

                # self.sendData("[STATE_OPERATION_ENABLED]", 1)
                if (rospy.Time.now().to_sec() - self.prev_hb_time) >= (1 / self.HB_RATE):
                    #for debug only!!!
                    # self.isInitial_Finish = True
                    # print(self.motion_req_goal)
                    ####

                    if self.isInitial_Finish:
                        if(self.motion_req_goal != self.motion.IDEL.value):
                            self.sendData("_[BUSY_AcCONTROL]", 1)
                        else:
                            if(self.up_button == 0) or (self.down_button == 0):
                                self.sendData("_[BUSY_MaCONTROL]", 1)
                            else:
                                self.sendData("_[IDL]", 1)
                    else:
                        if(self.isInitial_Trigger):
                            self.sendData("_[INITIALIZING]", 1)
                    self.prev_hb_time = rospy.Time.now().to_sec()
                
                # # Initial Lifter
                if (not self.isInitial_Trigger) and (self.fst_data_come):
                    self.sendData("_[INIT]", 1)
                    self.motion_req_goal = self.motion.DOWN.value
                    self.clear_parameter()
                    self.isInitial_Trigger = True
                    self.isInitial_Finish = False
                else: pass

                if self.fst_data_come:
                    # self.sendData("[ControlSequenc]", 1)
                    self.ControlSequenc()

                self.ControlState_seq = self.ControlState.FINAL.value
            else:
                pass
        elif self.ControlState_seq == self.ControlState.FINAL.value:
            # self.sendData("[FINAL]", 1)
            # self.sendData("[++++++++++++++++++++++]", 1)
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: FINAL")
            self.ControlState_seq = self.ControlState.INIT.value
        else:
            rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: UNKNOW")
        

        





        

        if (rospy.Time.now().to_sec() - self.statusword_stmp) >= (2):
            self.current_motor_state = "UNKNOW"
            self.motor_status.state = DeviceStateCanopen.STATE_UNKNOW
            self.ControlState_seq = self.ControlState.INIT.value

        # if (rospy.Time.now().to_sec() - self.prev_led_control_time) >= (1 / self.LED_CONTROL_RATE):
        #     # self.ButtonLEDControl(motion_req_goal)
        #     self.prev_led_control_time = rospy.Time.now().to_sec()
        

        # if(rospy.Time.now().to_sec() - self.prev_iostate_time) >= (1 / self.IOSTATE_RATE):
        #     # self.IOStateASCII()
        #     self.prev_iostate_time = rospy.Time.now().to_sec()

        
        

        
    def init_Motor(self, reset_node):
        # success = False
        # if reset_node:
        #     self.NMT_service(0x00, "Reset Node")
        #     time.sleep(1.0)
        
        self.MotorSwitched(self.motor_1_id, "Fault Reset")
        # self.NMT_service(0x00, "Reset Node")
        # self.NMT_service(0x00, "Switch to the <Operational> state")
        self.MotorSwitched(self.motor_1_id, "Shutdown")
        self.MotorSwitched(self.motor_1_id, "Switch ON")
        self.MotorSwitched(self.motor_1_id, "Enable Operation")





    def ControlSequenc(self):
        # ControlSequence
        if not self.motion_req_complete:
            if self.control_seq == self.control_state.INIT.value:
                self.clear_parameter()
                self.control_seq = self.control_state.CHECK_MANUAL.value

            elif self.control_seq == self.control_state.CHECK_MANUAL.value:
                self.control_seq = self.control_state.CHECK_AUTO.value

            elif self.control_seq == self.control_state.CHECK_AUTO.value:
                self.control_seq = self.control_state.MOVE_AUTO.value

            elif self.control_seq == self.control_state.MOVE_AUTO.value:
                if not self.motion_ctrl_complete:
                    # print("START MOTION CTRL")
                    if self.motion_req_goal == self.motion.STOP.value:
                        self.LiftMovement(self.motor_1_id, "STOP")
                        self.motion_result = self.motion_results.mstop.value
                        self.motion_ctrl_complete = True

                    elif self.motion_req_goal == self.motion.UP.value:
                        if self.motion_seq == self.motion_seqs.check_obj.value:
                            if not self.isSkipCheckOBJ:
                                if self.obj_detector != 1:
                                    self.motion_seq = self.motion_seqs.check_env.value
                                else:
                                    self.motion_result = self.motion_results.notFoundOBJ.value
                                    self.motion_seq = self.motion_seqs.go_finish.value
                                    self.motion_ctrl_complete = True
                            else:
                                self.motion_seq = self.motion_seqs.check_env.value
                        elif self.motion_seq == self.motion_seqs.check_env.value:
                            if self.limh_detector != 1:
                                self.motion_seq = self.motion_seqs.go_ctrl.value
                            elif (self.limh_detector == 1) and (self.closer_detector == 1):
                                self.LiftMovement(self.motor_1_id, "STOP")
                                self.motion_result = self.motion_results.limitH_NotcloseOBJ.value
                                self.motion_seq = self.motion_seqs.go_stop.value
                                self.motion_ctrl_complete = True
                            elif (self.limh_detector == 1) and (self.closer_detector != 1):
                                self.LiftMovement(self.motor_1_id, "STOP")
                                self.motion_result = self.motion_results.limitH_closeOBJ.value
                                self.motion_seq = self.motion_seqs.go_stop.value
                                self.motion_ctrl_complete = True
                            else:
                                self.motion_seq = self.motion_seqs.go_ctrl.value
                        elif self.motion_seq == self.motion_seqs.go_ctrl.value:
                            self.LiftMovement(self.motor_1_id, "UP")
                            self.motion_seq = self.motion_seqs.go_finish.value
                        elif self.motion_seq == self.motion_seqs.go_stop.value:
                            self.LiftMovement(self.motor_1_id, "STOP")
                            self.motion_seq = self.motion_seqs.go_finish.value
                        elif self.motion_seq == self.motion_seqs.go_finish.value:
                            self.motion_seq = self.motion_seqs.check_env.value
                        else:
                            print("UP State Unknow")

                    elif self.motion_req_goal == self.motion.DOWN.value:
                        # print("GO DOWN CMD")
                        if self.motion_seq == self.motion_seqs.check_obj.value:
                            self.motion_seq = self.motion_seqs.check_env.value
                        elif self.motion_seq == self.motion_seqs.check_env.value:
                            if self.liml_detector == 1:
                                self.motion_seq = self.motion_seqs.go_ctrl.value
                            else:
                                self.LiftMovement(self.motor_1_id, "STOP")
                                if self.closer_detector == 1:
                                    self.motion_result = self.motion_results.limitL_NotcloseOBJ.value
                                else:
                                    self.motion_result = self.motion_results.limitL_closeOBJ.value
                                self.motion_seq = self.motion_seqs.go_stop.value
                                self.motion_ctrl_complete = True
                        elif self.motion_seq == self.motion_seqs.go_ctrl.value:
                            self.LiftMovement(self.motor_1_id, "DOWN")
                            self.motion_seq = self.motion_seqs.go_finish.value
                        elif self.motion_seq == self.motion_seqs.go_stop.value:
                            self.LiftMovement(self.motor_1_id, "STOP")
                            self.motion_seq = self.motion_seqs.go_finish.value
                        elif self.motion_seq == self.motion_seqs.go_finish.value:
                            self.motion_seq = self.motion_seqs.check_env.value
                        else:
                            print("DOWN State Unknow")
                else:
                    self.control_seq = self.control_state.FINISH.value
            
            elif self.control_seq == self.control_state.MANUAL_INTERUPT.value:
                # print("MANAUAL INTERUPT")
                self.LiftMovement(self.motor_1_id, "STOP")
                self.motion_result = self.motion_results.manualInterupt.value
                self.control_seq = self.control_state.FINISH.value
            
            elif self.control_seq == self.control_state.FINISH.value:
                self.motion_req_complete = True
                self.motion_ctrl_complete = True
                # print("FINISH")
                self.control_seq = self.control_state.INIT.value
            
            #//***************************************//
            #//*                                     *//
            #//*        Check Button Interupt        *//
            #//*                                     *//
            #//***************************************//
            # print("CHEK MANUAL")
            self.checkButtonInterupt()
            
        else:
            if not self.send_result:
                self.send_result = True
                if not self.isInitial_Finish:
                    if (self.isInitial_Trigger) and (self.liml_detector != 1):
                        self.isInitial_Success = True
                    else:
                        self.isInitial_Success = False
                    self.isInitial_Finish = True
                    self.sendData("_INIT_Success["+str(self.isInitial_Success) + "]_Result["+str(self.motion_result-1)+"]", 1)
                    self.sendData("_[INIT_FINISH]", 1)
                    self.sendData("_AcRDY", 1)
                else:
                    self.sendData("_AcResult_Goal["+str(self.motion_req_goalSTR)+"]_Result["+str(self.motion_result-1)+"]", 1)
                
                self.motion_req_goal = self.motion.IDEL.value


    def clear_parameter(self):
        self.motion_req_complete = False
        self.motion_seq = self.motion_seqs.check_obj.value
        self.motion_result = self.motion_results.pending.value
        self.motion_ctrl_complete = False
        
        self.send_result = False
    
    def ResetSystem(self):
        print("{} Driver: calling reset function".format(self.device_name))
        self.isReset = True
        self.fst_data_come = False
        self.motion_req_goal = self.motion.IDEL.value
        self.control_seq = self.control_state.INIT.value
        self.isInitial_Trigger = False
        self.isInitial_Finish = False
        self.isInitial_Success = False
        self.clear_parameter()

        self.down_press_time = 0
        self.down_stmp_time = 0
        self.init_down_stmp = False

        self.up_press_time = 0
        self.up_stmp_time = 0
        self.init_up_stmp = False
        # time.sleep(3)
        while(1):
            self.checkKeyButtonSpecial()
            if (self.up_button == 1) or (self.down_button == 1):
                break
            # print("Please release UP and DOWN button")
            self.sendData("_[PLEASE RELEASE UP & DOWN BUTTON FOR RST]", 1)
            time.sleep(1)
            # self.control_seq = self.control_state.MANUAL_INTERUPT.value

    
    def checkButtonInterupt(self):
        if (self.up_button == 0) or (self.down_button == 0):
            print("MANUAL DETECTEDD!!!")
            self.control_seq = self.control_state.MANUAL_INTERUPT.value
        
    
    def checkKeyButtonSpecial(self):
        self.reqDigitalInputs(self.motor_1_id)
        # Manual Control
        if self.isInitial_Finish:
            if(self.motion_req_goal == self.motion.IDEL.value):
                if (self.up_button == 0) and (self.down_button == 0):
                    self.LiftMovement(self.motor_1_id, "STOP")
                elif (self.up_button == 0) and (self.down_button == 1):
                    self.LiftMovement(self.motor_1_id, "UP")
                elif (self.up_button == 1) and (self.down_button == 0):
                    self.LiftMovement(self.motor_1_id, "DOWN")
                else:
                    self.LiftMovement(self.motor_1_id, "STOP")
                # print("MANUAL_TRIG")
                # self.LiftMovement(self.motor_1_id, "STOP")


        # Stamp button time 
        if self.up_button == 0:
            if not self.init_up_stmp:
                self.up_stmp_time = rospy.Time.now().to_sec()
                self.init_up_stmp = True
            else: pass
            self.up_press_time = rospy.Time.now().to_sec() - self.up_stmp_time
        else:
            self.up_press_time = 0
            self.up_stmp_time = 0
            self.init_up_stmp = False
        
        if self.down_button == 0:
            if not self.init_down_stmp:
                self.down_stmp_time = rospy.Time.now().to_sec()
                self.init_down_stmp = True
            else: pass
            self.down_press_time = rospy.Time.now().to_sec() - self.down_stmp_time
        else:
            self.down_press_time = 0
            self.down_stmp_time = 0
            self.init_down_stmp = False
        
        # print("up_press_time:{}, down_press_time:{}".format(self.up_press_time, self.down_press_time))
        
        if(self.down_press_time > 3) and (self.up_press_time > 3):
            print("Manual Reset")
            self.sendData("_[MANUAL_RST]", 1)
            self.ResetSystem()
    

    def LiftMovement(self, MotorID, dir):
        if dir == "UP":
            if self.limh_detector == 0:
                # print("LiftMovement -- > UP")
                self.sendData("_[LiftMovement -- > UP]", 1)
                self.SDO_MotorSpin(MotorID, -1800)
            else:
                # print("Limit High Detect")
                self.sendData("_[Limit High Detect]", 1)
                self.SDO_MotorSpin(MotorID, 0)
            # self.SDO_MotorSpin(MotorID, -2000)
        elif dir == "DOWN":
            if self.liml_detector == 1:
                # print("LiftMovement -- > DOWN")
                self.sendData("_[LiftMovement -- > DOWN]", 1)
                self.SDO_MotorSpin(MotorID, 1800)
            else:
                # print("Limit Low Detect")
                self.sendData("_[Limit Low Detect]", 1)
                self.SDO_MotorSpin(MotorID, 0)
            # self.SDO_MotorSpin(MotorID, 2000)
        elif dir == "STOP":
            # print("STOP")
            self.SDO_MotorSpin(MotorID, 0)
        else:
            self.SDO_MotorSpin(MotorID, 0)



    def sendData(self, data, counter):
        msg = String()
        msg.data = "#Rx"+self.device_name+data +"$"
        print("{} Driver: send data --> {}".format(self.device_name, str(msg.data)))
        for x in range(counter):
            self.tx_pub.publish(msg)


    def reqDigitalInputs(self, MotorID):
        # request Digital IO input status RO CiA301 decive profile 
        # LD Servo Driver CANOPEN Protocal-en.pdf, Page 56
        # 200Bh/01, Digital IO input status, UINT16, RO
        data_frame = [0x40, 0x0b, 0x20, 0x01, 0x00, 0x00, 0x00, 0x00]
        self.SendToCan(0x600 + MotorID, data_frame)

        


    def decimal_to_binary(decimal_num):
        binary_str = format(int(decimal_num), '08b')
        return binary_str
    

    def SDO_MotorSpin(self, MotorID, target_vel, index_motor=-1):
        success = False

        #Dec to Hex 4 byte LSB->MSB
        vel_hex = struct.pack('<i', int(target_vel))

        # for Driver -> ZLAC8015D
        if self.device_name == "ZLAC8015D":
            data_frame = [0x23, 0xff, 0x60, index_motor, vel_hex[0], vel_hex[1], vel_hex[2], vel_hex[3]]
            # print(data_frame)
        # for CANOPEN Motor driver -> SmartrisLefertDrives, OrientalmotorBLVD_KRD
        else:
            data_frame = [0x23, 0xff, 0x60, 0x00, vel_hex[0], vel_hex[1], vel_hex[2], vel_hex[3]]
        
        # if self.isSim:
        #     pass
        # else:
        #     success = self.SendToCan(0x600 + MotorID, data_frame)
        
        success = self.SendToCan(0x600 + MotorID, data_frame)

        return success
    

     # Follow instructions HP-5143E.pdf page 17 [NMT Communication Objects]
    def NMT_service(self, MotorID, cmd):
        success = True
        COB_ID = 0x00
        Byte0_cmd = 0x00
        Byte1_NodeID = MotorID
        if cmd == "Switch to the <Operational> state":
            Byte0_cmd = 0x01
        elif cmd == "Switch to the <Stoped> state":
            Byte0_cmd = 0x02
        elif cmd == "Switch to the <Pre-operational> state":
            Byte0_cmd = 0x80
        elif cmd == "Reset Node":
            Byte0_cmd = 0x81
        elif cmd == "Reset Communication":
            Byte0_cmd = 0x82
        else:
            success = False
        
        if success:
            data_frame = [Byte0_cmd, MotorID]
            success = self.SendToCan(COB_ID, data_frame)
        else:
            pass

        return success
    
    
    def MotorSwitched(self, MotorID, cmd):
        success = True
        data = 0x00
        # follow HP-5143E.pdf page 34 [6 Status Machine control commands]
        if cmd == "Shutdown":                        #Transitions 2, 6, 8   “Shutdown” command received from controlword.
            data = 0x06
        elif cmd == "Switch ON":                     #Transitions 3         “Switch On” command received from controlword.
            data = 0x07
        elif cmd == "Switch ON + Enable Operation":  #Transitions 3, 4*     
            data = 0x0F
        elif cmd == "Disable Voltage":               #Transitions 7, 9, 10, 12
            data = 0x00
        elif cmd == "Quick Stop":                    #Transitions 7, 10, 11
            data = 0x02
        elif cmd == "Disable Operation":             #Transitions 5         “Disable operation” command received from controlword.
            data = 0x03
        elif cmd == "Enable Operation":              #Transitions 4, 16     “Enable Operation” command received from controlword.
            data = 0x0F 
        elif cmd == "Fault Reset":                   #Transitions 15
            data = 0x80
        else:
            success = False
        # * Automatic transition to enable operation state after executing switched on state functionality.
        if success:
            data_frame = [0x2B, 0x40, 0x60, 0x00, data, 0x00, 0x00, 0x00]
            success = self.SendToCan(0x600 + MotorID, data_frame)
            if success:
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: Succcess set Status Machine control commands Motor-ID {}, cmd {}".format(MotorID, cmd))
            else:
                rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Fail set Status Machine control commands Motor-ID {}, cmd {}".format(MotorID, cmd))
        else:
            rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Not found Status Machine control commands cmd {}".format(cmd))

        return success



    def SendToCan(self, MotorID, DataFrame):
        success = True
        if not self.use_matrix_navgo_bypass:
            try:
                # data_frame = struct.pack('<i', int(req_value_left))
                message = can.Message(  arbitration_id=MotorID, 
                                        is_extended_id=False, 
                                        data=DataFrame)
                self.bus.send(message, timeout=1.0)
            except:
                print("cannot send to canbus canbus down")
                success = False
                # sys.exit(0)
                # sys.exit(1) 
        else:
            message = Frame()
            message.id = MotorID
            message.is_rtr = False  
            message.is_extended = False
            message.is_error = False
            message.dlc = len(DataFrame)
            message.data = DataFrame

        return success
  
        
   
if __name__ == '__main__':
    UpdateOdom()
    rospy.spin()