# enum UVC_VERSION
# {
#     NONE_VERSION      = 0,
#     ALWAYS_ON_VERSION = 1, (go traget and turn on uvc alongside)
#     POINT_ON_VERSION  = 2  (on uvc and check motion each point, off uvc when go traget)
# };

# enum ModeState
# {
#     ON_MODE         = 1,
#     OFF_MODE        = 2
# };

#goal  
int8 uvc_version       
int8 uvc_mode
int64 uvc_warm_time_secs
int64 point_no
---

#result
# enum RESULT
# {
#     RESULT_PROCESS_FAIL    = 0,
#     RESULT_PROCESS_SUCCESS  = 1
# };

# enum UVC_STATE
# {
#     UVC_RESULT_INIT                         = 0,
#     UVC_SUCCESS_TURN_ON                     = 1,
#     UVC_NOT_ALLOWED_ON_VOLTAGGE_BALANCE     = 2,
#     UVC_NOT_ALLOWED_ON_LOW_BATTERY          = 3,
#     UVC_UNKNOW                              = 4,
#     UVC_SERVICE_ERROR                       = 5,
#     UVC_HARDWARE_ERROR                      = 6,
#     UVC_INTERLOCK_INACTIVE                  = 7,
#     UVC_CANNT_TURN_OFF                      = 8,
#     UVC_SUCCESS_TURN_OFF                    = 9,
#     UVC_TABLET_LOSS_COMMUNICATE             = 10,
#     UVC_PIR_CUTOFF_CE_VER                   = 11
# };

# ** if turn on success will ***only*** return  result    = RESULT::RESULT_PROCESS_SUCCES  = 1 and
#                                               uvc_state = UVC_STATE::UVC_SUCCESS_TURN_ON = 1

int64 result
string result_message
int64 uvc_state
---


#feedback
# enum SequenceState
# {
#     INIT                = 0,
#     TURN_ON_UVC         = 1,
#     TURN_OFF_UVC        = 2,   
#     WAIT_ALL_UVC_ON,    = 3,
#     WARM_UVC_LAMP       = 4,
#     FINISH              = 5,
#     COMMAND_NOT_FOUND   = 6
# };
int64 sequence
int64 warming_countdown
