#!/usr/bin/env python2
import rospy
import dynamic_reconfigure.client
from std_msgs.msg import Int32
from web_interface_msgs.msg import Zones
class DynamicsCostmap:
    def __init__(self):
        self.robot_zone = rospy.Subscriber("/robot_zone", Zones, self.cbZone)
        self.local_costmap_dynamics_client = dynamic_reconfigure.client.Client("/move_base/local_costmap/inflation_layer", config_callback=self.local_callback)
        self.global_costmap_dynamics_client = dynamic_reconfigure.client.Client("/move_base/global_costmap/inflation_layer", config_callback=self.global_callback)
        
        # sonar_layer 
        self.global_sonar_dyc = dynamic_reconfigure.client.Client("/move_base/global_costmap/sonar_layer", config_callback=self.global_sonar_callback)
        self.local_sonar_dyc = dynamic_reconfigure.client.Client("/move_base/local_costmap/sonar_layer", config_callback=self.local_sonar_callback)

        # Teb_plannner 
        self.Teb_dyc = dynamic_reconfigure.client.Client("/move_base/TebLocalPlannerROS", config_callback=self.teb_callback) 


        self.current_zone = 0
        self.old_zone = 0

        self.set_inflation_radius = 0.6
        self.set_cost_scaling_factor = 10.0

        self.isTrigger = False
        self.old_set_cost_scaling_factor = 0.0

        # self.r = rospy.sleep(0.1)
        r = rospy.Rate(0.5)
        
        while not rospy.is_shutdown():
            self.update_costmap()
            r.sleep()

    def local_callback(self, config):
        rospy.loginfo("config set to {cost_scaling_factor}, {inflation_radius}".format(**config))
    
    def global_callback(self, config):
        rospy.loginfo("config set to {cost_scaling_factor}, {inflation_radius}".format(**config))
    
    # sonar_layer
    def global_sonar_callback(self, config):
        rospy.loginfo("config set {enabled}".format(**config))

    def local_sonar_callback(self, config):
        rospy.loginfo("config set {enabled}".format(**config))
    
    # teb_planner 
    def teb_callback(self, config):
        rospy.loginfo("config set {max_vel_x}, {max_vel_theta}".format(**config))
        
    def cbZone(self, msg):
        self.current_zone = msg.zone_id
        #docking, yellow
        # if self.current_zone != self.old_zone:
        # print(msg.zone_id)
        if self.current_zone == 19: 
            self.set_inflation_radius = 0.15
            self.set_cost_scaling_factor = 2.0
        else:
            self.set_inflation_radius = 0.55
            self.set_cost_scaling_factor = 10.0
        
        if self.set_cost_scaling_factor != self.old_set_cost_scaling_factor:
            self.isTrigger = True
            self.old_set_cost_scaling_factor = self.set_cost_scaling_factor
            # print("[dynamic_zone]: change zone costmap")
	        # print("isTrigger", self.isTrigger)
        else:
            #self.isTrigger = False
	        pass  
            
	print(self.old_set_cost_scaling_factor)
            
                
    
    def update_costmap(self):
	
        if self.isTrigger == True:
            # print("[dynamic_zone]: change zone costmappppppppp")
            self.local_costmap_dynamics_client.update_configuration({"cost_scaling_factor":self.set_cost_scaling_factor,
                                                               "inflation_radius":self.set_inflation_radius})
            self.global_costmap_dynamics_client.update_configuration({"cost_scaling_factor":self.set_cost_scaling_factor,
                                                               "inflation_radius":self.set_inflation_radius})

            self.isTrigger = False
        else:
            pass


if __name__ == '__main__':
    rospy.init_node('dynamic_params')
    DynamicsCostmap()
    rospy.spin()



