
# uint8 STATE_FAULT = 0
# uint8 STATE_FAULT_REACTION_ACTIVE = 1
# uint8 STATE_QUICK_STOP_ACTIVE = 2
# uint8 STATE_OPERATION_ENABLED = 3
# uint8 STATE_READY_TO_SWITCH_ON = 4
# uint8 STATE_SWITCH_ON = 5
# uint8 STATE_NOT_READY_SWITCH_ON = 6
# uint8 STATE_SWITCH_ON_DISABLED = 7
# uint8 STATE_UNKNOW = 99

# uint8 state
# string text
# uint8[] status_word
# string binary
# uint8[] fault_state
# bool shaft_lock
# string HWTO

DeviceStateCanopen_info[] devices