uint8 COLOR_BLACK   = 0
uint8 COLOR_RED     = 1
uint8 COLOR_GREEN   = 2
uint8 COLOR_BLUE    = 3
uint8 COLOR_WHITE   = 4
uint8 COLOR_YELLOW  = 5
uint8 COLOR_VIOLET  = 6
uint8 COLOR_SKY     = 7
uint8 COLOR_ORANGE  = 8

uint8 MODE_OFF      = 0
uint8 MODE_BLINK    = 1
uint8 MODE_SET      = 2
uint8 MODE_DOCKING  = 3
uint8 MODE_MOVEMENT = 4
uint8 MODE_ERROR_DEVICE = 5
uint8 MODE_PAUSE    = 6
uint8 MODE_LOST_CONNECT = 7

uint8 led_color
uint8 led_mode