#!/usr/bin/env python
import rospy
from sensor_msgs.msg import *
from std_msgs.msg import *
from std_srvs.srv import *
from geometry_msgs.msg import *

import os
import sys
import csv
import time
import datetime

class BatteryLogging:
    def __init__(self):
        # self.counter = 0
        # self.pub = rospy.Publisher("/number_count", Int64, queue_size=10)
        self.pub_acc_io = rospy.Publisher("/accelerometer", Vector3, queue_size=10)
        self.battery_state = rospy.Subscriber("/battery_state", BatteryState, self.callback_battery_state)
        self.robot_mode = rospy.Subscriber("/robot_mode", Int8, self.callback_robot_mode)
        self.uvc_state = rospy.Subscriber("/aragorn_io/uvc_state", Int8, self.callback_uvc_state)
        self.battery_temp = rospy.Subscriber("/battery_temperature", Temperature, self.callback_battery_temp)
        self.sub_imu = rospy.Subscriber("/imu/data_raw", Imu, self.callback_imu)
        # self.reset_service = rospy.Service("/reset_counter", SetBool, self.callback_reset_counter)
        self.batt_state = BatteryState()
        self.batt_temp = Temperature()
        self.acc_msg = Vector3()
        self.pub_acc = False

        self.today = datetime.date.today()
        self.serial_no = os.environ["MATRIX_UVD_SERIAL_NO"]
        self.fname = self.serial_no + "_battery_log_15m_" + str(self.today) +".csv"
        self.filelog = csv.writer(open(self.fname, "wb"))
        self.i = 0
        
        self.uvc_state = 0.0
        self.turn_on_uvc = 0.0 
        self._isBatt_comup = False

        self.sequence_uvc = 1 #turn on uvc 
        self.init_time = False
        self.balance_time = 300.000 #sec
        self.on_time = 1200.00 #sec
        self.time_out = 0.0000
        self.setWait_state_time = 40
        self.wait_uvc_state_time_out = 0.000 #sec
        self.rst_uvc_couter = 0

        rospy.wait_for_service("/aragorn_io/uvc")
        # self.uvc_server = rospy.ServiceProxy('/aragorn_io/uvc', SetBool)
        

    

        if os.stat(self.fname).st_size == 0:
            self.filelog.writerow([ "Date",
                                    "Time",
                                    "voltage(V)",
                                    "current(A)",
                                    "capacity(Ah)",
                                    "percentage",
                                    "s1(V)",
                                    "s2(V)",
                                    "s3(V)",
                                    "s4(V)",
                                    "s5(V)",
                                    "s6(V)",
                                    "s7(V)",
                                    "s8(V)",
                                    "turn_uvc",
                                    "lamp_on",
                                    "batt_temperature"]) 

        rate = rospy.Rate(1)

        # rospy.on_shutdown(self.shutdown_mode)
	
       
        while not rospy.is_shutdown():
            if self._isBatt_comup and self.pub_acc:
                self.logging_csv()
            rate.sleep()
        
        

    # def shutdown_mode(self):
        # self.uvc_server(False)
	


    def callback_imu(self, msg):
        self.acc_msg.x = msg.angular_velocity.x
        self.acc_msg.y = msg.angular_velocity.y
        self.acc_msg.z = msg.angular_velocity.z
        # self.pub_acc_io.publish(self.acc_msg)
	# print(self.acc_msg.x)
        self.pub_acc = True

    
    def callback_robot_mode(self, msg):
        if msg.data == 9:
            self.turn_on_uvc = 1.0
        else:
            self.turn_on_uvc = 0.0 

    def callback_uvc_state(self, msg):
        if msg.data == 1:
            self.uvc_state = 1.0
        else:
            self.uvc_state = 0.0 

    def callback_battery_state(self, msg):
        self.batt_state = msg
        self._isBatt_comup = True
        # print(self.batt_state.cell_voltage[0])
    
    def callback_battery_temp(self, msg):
        self.batt_temp = msg

    
    def logging_csv(self):

	self.pub_acc_io.publish(self.acc_msg)

        print(self.serial_no)
        now = time.strftime("%H"+":"+"%M"+":"+"%S")
        print("logging",now)
        self.filelog.writerow([ str(self.today), 
                                str(now), 
                                '{0:0.3f}'.format(self.batt_state.voltage),
                                '{0:0.3f}'.format(self.batt_state.current), 
                                '{0:0.3f}'.format(self.batt_state.capacity),
                                '{0:0.3f}'.format(self.batt_state.percentage),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[0]),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[1]),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[2]),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[3]),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[4]),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[5]),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[6]),
                                '{0:0.3f}'.format(self.batt_state.cell_voltage[7]),
                                '{0:0.3f}'.format(self.turn_on_uvc),
                                '{0:0.3f}'.format(self.uvc_state),
                                '{0:0.3f}'.format(self.batt_temp.temperature)
                                ])
	uvc_server = rospy.ServiceProxy('/aragorn_io/uvc', SetBool)

	# print("1")

        
        if self.batt_state.percentage >= 0.1500:

            if self.sequence_uvc == 0:
                if not self.init_time:
                    set_uvc = uvc_server(False) # turn off uvc
                    if self.uvc_state == 0:
                        self.time_out = time.time() + self.balance_time
                        self.init_time = True
                else:
                    if time.time() >= self.time_out:
                        self.sequence_uvc = 1
                        self.init_time = False
            elif self.sequence_uvc == 1:
                if not self.init_time:
                    if self.rst_uvc_couter <= 2:
                        # turn on uvc
                        set_uvc = uvc_server(True) 
                        # set time out wait uvc state confirm uvc on
                        self.wait_uvc_state_time_out = time.time() + self.setWait_state_time
                        # wait uvc state confirm turn on 
                        while(1):
                            if self.uvc_state == 1:
                                self.time_out = time.time() + self.on_time
                                self.init_time = True
                                self.rst_uvc_couter = 0
                                self.wait_uvc_state_time_out = 0
                                print("confirm uvc on success !!!!")
                                break
                            else:
                                # check time out 
                                if time.time() >= self.wait_uvc_state_time_out:
                                    set_uvc = uvc_server(False) 
                                    self.rst_uvc_couter = self.rst_uvc_couter + 1 
                                    self.init_time = False
                                    break
                                else:
                                    print("wait uvc state confirm on", int(abs(self.wait_uvc_state_time_out-time.time())))
                            time.sleep(1)
                            
                else:
                    if time.time() >= self.time_out:
                        self.sequence_uvc = 0
                        self.init_time = False
            
            # print debug 
            if self.init_time:
                print("current sequence:", self.sequence_uvc, "countdown change stage:", int(abs(self.time_out-time.time())),"sec")
            else:
                print("wait init time state = true")

        else:
            if self.uvc_state == 1:
                set_uvc = uvc_server(False) # turn off uvc
            else: 
                pass
            print("battery lower than 15%")
        
        print("battery_state", self.batt_state.percentage)
        print(" ")
        print(" ")
	

                

if __name__ == '__main__':
    rospy.init_node('battery_log')
    BatteryLogging()
    rospy.spin()
