#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import rospy, roslaunch
import numpy as np
import rospkg
import subprocess
import os
import sys
from enum import Enum
from std_msgs.msg import UInt8, Bool, Int8

import actionlib
from actionlib_msgs.msg import *


from ir_auto_docking.msg import AutodockOperateAction, AutodockOperateGoal
from web_interface_msgs.msg import DockingAction
from web_interface_msgs.msg import RouteFollowAction
from mission_msgs.msg import MissionOperateAction
from mission_msgs.msg import MissionRunAction
from move_base_msgs.msg import MoveBaseAction
from aragorn_io_action.msg import ScanMotionAction
from aragorn_io_action.msg import UVCAction
from std_srvs.srv import SetBool




class CoreNodeController():
    def __init__(self):
        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace('aragorn_bringup/script', '')

        self.rospack = rospkg.RosPack()

        # self.tablet_discon = rospy.Service("/aragorn_launchctl/tablet_discon", self.cbTabletDiscon)

        # self.sub_start_up = rospy.Subscriber('/aragorn_io/diagnostics', Bool, self.cbStartRobot, queue_size=1)
        self.sub_mode = rospy.Subscriber('/aragorn/robot_mode', Int8, self.cbModeLaunch, queue_size=1)
        # self.sub_emer = rospy.Subscriber('/aragorn_io/emergency', Int8, self.cbEmer, queue_size=1)

        self.Launcher = Enum('Launcher', 'launch_dynamics_param launch_robot_status launch_autodock launch_vel_filter launch_sound launch_motor launch_imu launch_bms launch_camera launch_rear_camera launch_io launch_io_action launch_remote launch_core launch_lidar launch_lidar_unique launch_diagnostics launch_led launch_web launch_localization launch_manual_docking')
        self.CurrentMode = Enum('CurrentMode', 'idle start_motor shutdown_motor shutdown_robot emergency fucn_1 down_stairs tablet_loss_commu uvc_on uvc_off ready_to_start docking_mode_on docking_mode_off error_device charger_on charger_off reset emergency_case_active emergency_charge')

        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
        
        self.move_base = actionlib.SimpleActionClient("move_base", MoveBaseAction)
        
        # self.MoveBase = actionlib.SimpleActionClient("move_base", MoveBaseAction)
        self.IR_Manual_Docking = actionlib.SimpleActionClient("manualdocking_server", AutodockOperateAction)
        self.IR_Docking = actionlib.SimpleActionClient("autodocking_server", AutodockOperateAction)
        self.IST_Docking = actionlib.SimpleActionClient("ist_docking", DockingAction)
        self.IST_RouteFollow = actionlib.SimpleActionClient("ist_route_follow", RouteFollowAction)
        self.IST_Mission_server = actionlib.SimpleActionClient("missions_server", MissionRunAction)
        self.IST_Mission_operate = actionlib.SimpleActionClient("missions_operate", MissionOperateAction)
        self.ScanMotion = actionlib.SimpleActionClient("scan_motion_server", ScanMotionAction)
        self.UVC = actionlib.SimpleActionClient("uvc_server", UVCAction)
        

        self.launch_motor_launched = False
        self.launch_vel_filter_launched = False
        self.launch_sound_launched = False
        self.launch_io_launched = False
        self.launch_io_action_launched = False
        self.launch_bms_launched = False
        self.launch_imu_launched = False
        self.launch_camera_launched = False
        self.launch_rear_camera_launched = False
        self.launch_remote_launched = False
        self.launch_core_launched = False
        self.launch_lidar_launched = False
        self.launch_diagnostics_launched = False
        self.launch_led_launched = False
        self.launch_web_launched = False
        self.launch_localization_launched = False
        self.launch_lidar_unique_launched = False
        self.launch_autodock_launched = False
        self.launch_robot_status_launched = False
        self.launch_dynamics_param_launched = False
        self.launch_manual_docking_launched = False

        self.is_triggered = False

        self.current_mode = self.CurrentMode.idle.value

        self.serial_no = os.environ["MATRIX_UVD_SERIAL_NO"]
        self.model_type = self.serial_no[8]

        self.remote_launch = ""

        self.initial_robot()

        loop_rate = rospy.Rate(10) # 10hz
        while not rospy.is_shutdown():
            if self.is_triggered == True:
                self.fnControlNode()
            
            loop_rate.sleep()
    
    # def emergency_case(self):
    #     self.MoveBase.cancel_all_goals()
    #     self.IR_Docking.cancel_all_goals()
    #     self.IST_Docking.cancel_all_goals()
    #     self.IST_RouteFollow.cancel_all_goals()
    #     self.IST_Mission_server.cancel_all_goals()
    #     self.IST_Mission_operate.cancel_all_goals()
    #     self.ScanMotion.cancel_all_goals()
    #     self.UVC.cancel_all_goals()

    # def cbTabletDiscon(self, req):
    #     if req.data:
    #         self.fnLaunch(self.Launcher.launch_motor.value, False)

    #         self.move_base.cancel_all_goals()
    #         self.IR_Docking.cancel_all_goals()
    #         self.IST_Docking.cancel_all_goals()
    #         self.IST_RouteFollow.cancel_all_goals()
    #         self.IST_Mission_server.cancel_all_goals()
    #         self.IST_Mission_operate.cancel_all_goals()
    #         self.ScanMotion.cancel_all_goals()
    #         self.UVC.cancel_all_goals()

    #         self.fnLaunch(self.Launcher.launch_io_action.value, False)
    #     else:
    #         pass
        
    #     return True, "[aragorn_launchctl]:Tablet discon mode trigger!!!"


    def cbModeLaunch(self, mode_msg):
        # rospy.loginfo("Start core_controller with mode %d", mode_msg)
        if(self.current_mode == mode_msg.data):
            pass
        else:
            self.current_mode = mode_msg.data
            self.is_triggered = True
    
    def initial_robot(self):
        os.system("roscore")
        # os.system("killall -9 rosout")
        # os.system("killall -9 rosmaster")
        # rospy.sleep(2)
        
        # select tf robot 
        if self.model_type == "B":
            self.remote_launch = "/launch/include/tf/tf_"+ self.serial_no + ".launch"
        else:
            # model A common tf
            if (self.serial_no =="20210006A") or (self.serial_no =="20210009A"):
                self.remote_launch = "/launch/aragorn_remote.launch"
            else:
                self.remote_launch = "/launch/include/tf/tf_"+ self.serial_no + ".launch"
        self.fnLaunch(self.Launcher.launch_remote.value, True)

        # select configure lidar 
        if self.serial_no == "20210001B":
            try:
                self.fnLaunch(self.Launcher.launch_lidar_unique.value, True)
            
            except:
                rospy.logerr("[startup_robot]:launch Lidar error")
                self.fnLaunch(self.Launcher.launch_lidar_unique.value, False)
                # pass
        else:
            self.fnLaunch(self.Launcher.launch_lidar.value, True)
        
        self.fnLaunch(self.Launcher.launch_sound.value, True)

        try:
            self.fnLaunch(self.Launcher.launch_io.value, True)
        
        except:
            rospy.logerr("[startup_robot]:launch IO")
            self.fnLaunch(self.Launcher.launch_io.value, False)

        self.fnLaunch(self.Launcher.launch_io_action.value, True)
        self.fnLaunch(self.Launcher.launch_camera.value, True)

        try:
            self.fnLaunch(self.Launcher.launch_bms.value, True)
        
        except:
            rospy.logerr("[startup_robot]:launch BMS error")
            self.fnLaunch(self.Launcher.launch_bms.value, False)

        self.fnLaunch(self.Launcher.launch_imu.value, True)
        self.fnLaunch(self.Launcher.launch_localization.value, True)
        self.fnLaunch(self.Launcher.launch_autodock.value, True)
        self.fnLaunch(self.Launcher.launch_manual_docking.value, True)
        self.fnLaunch(self.Launcher.launch_robot_status.value, True)
        self.fnLaunch(self.Launcher.launch_dynamics_param.value, True)
        
        rospy.sleep(5)
        
        self.fnLaunch(self.Launcher.launch_diagnostics.value, True)
        self.fnLaunch(self.Launcher.launch_vel_filter.value, True)


    
    def fnControlNode(self):
        # Start_robot mode
        if self.current_mode == self.CurrentMode.start_motor.value:
            rospy.loginfo("[Launch control]: Now trigger for Start motor drive")
            self.fnLaunch(self.Launcher.launch_io_action.value, True)
            self.fnLaunch(self.Launcher.launch_autodock.value, True)
            self.fnLaunch(self.Launcher.launch_manual_docking.value, True)
            self.fnLaunch(self.Launcher.launch_motor.value, True)
            
            # rospy.sleep(5)
            # self.fnLaunch(self.Launcher.launch_localization.value, True)
        
        elif self.current_mode == self.CurrentMode.ready_to_start.value:
            self.fnLaunch(self.Launcher.launch_motor.value, False)

        elif self.current_mode == self.CurrentMode.fucn_1.value:
            rospy.loginfo("[Launch control]: Now trigger for fucn_1 mauldocking")
            goal = AutodockOperateGoal()
            goal.order = 1
            self.IR_Manual_Docking.send_goal(goal)

            
        elif self.current_mode == self.CurrentMode.reset.value:
            rospy.loginfo("[Launch control]: Now trigger for reset io state and off motor control")
            self.fnLaunch(self.Launcher.launch_motor.value, False)
            
            self.IR_Manual_Docking.cancel_all_goals()
            self.move_base.cancel_all_goals()
            self.IR_Docking.cancel_all_goals()
            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()
            self.IST_Mission_server.cancel_all_goals()
            self.IST_Mission_operate.cancel_all_goals()
            self.ScanMotion.cancel_all_goals()
            self.UVC.cancel_all_goals()

            self.fnLaunch(self.Launcher.launch_io_action.value, False)
            self.fnLaunch(self.Launcher.launch_autodock.value, False)
            self.fnLaunch(self.Launcher.launch_manual_docking.value, False)

            # self.fnLaunch(self.Launcher.launch_motor.value, False)
            # self.fnLaunch(self.Launcher.launch_io_action.value, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
        
        elif self.current_mode == self.CurrentMode.emergency.value:
            rospy.loginfo("[Launch control]: Now trigger for Stop motor drive")
            # self.fnLaunch(self.Launcher.launch_localization.value, False)
            # rospy.sleep(5)
            self.fnLaunch(self.Launcher.launch_motor.value, False)
            
            self.IR_Manual_Docking.cancel_all_goals()
            self.move_base.cancel_all_goals()
            self.IR_Docking.cancel_all_goals()
            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()
            self.IST_Mission_server.cancel_all_goals()
            self.IST_Mission_operate.cancel_all_goals()
            self.ScanMotion.cancel_all_goals()
            self.UVC.cancel_all_goals()

            self.fnLaunch(self.Launcher.launch_io_action.value, False)
            self.fnLaunch(self.Launcher.launch_autodock.value, False)
            self.fnLaunch(self.Launcher.launch_manual_docking.value, False)
            # a = subprocess.run(["rosservice", "call", "/aragorn_io/led_status"])
	
	    # elif self.current_mode == self.CurrentMode.fucn_1.value:
        #     rospy.loginfo("[Launch control]: Now trigger for Relocalization")
        #     self.fnLaunch(self.Launcher.launch_localization.value, False)
        #     rospy.sleep(5)
        #     self.fnLaunch(self.Launcher.launch_localization.value, True)
        
        elif self.current_mode == self.CurrentMode.down_stairs.value:
            rospy.loginfo("[Launch control]: Now trigger for Down stairs")
            self.fnLaunch(self.Launcher.launch_motor.value, False)
        
        elif self.current_mode == self.CurrentMode.tablet_loss_commu.value:
            rospy.loginfo("[Launch control]: Now trigger for Tablet loss comunicate")
            self.fnLaunch(self.Launcher.launch_motor.value, False)
            self.move_base.cancel_all_goals()
            self.IR_Docking.cancel_all_goals()
            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()
            self.IST_Mission_server.cancel_all_goals()
            self.IST_Mission_operate.cancel_all_goals()
            self.ScanMotion.cancel_all_goals()
            self.UVC.cancel_all_goals()
            self.fnLaunch(self.Launcher.launch_io_action.value, False)

        elif self.current_mode == self.CurrentMode.emergency_charge.value:
            rospy.loginfo("[Launch control]: Now trigger for emergency charge")
            self.fnLaunch(self.Launcher.launch_motor.value, False)
            self.move_base.cancel_all_goals()
            self.IR_Docking.cancel_all_goals()
            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()
            self.IST_Mission_server.cancel_all_goals()
            self.IST_Mission_operate.cancel_all_goals()
            self.ScanMotion.cancel_all_goals()
            self.UVC.cancel_all_goals()
            self.fnLaunch(self.Launcher.launch_io_action.value, False)

        
        # Off_robot mode
        elif self.current_mode == self.CurrentMode.shutdown_robot.value:
            rospy.loginfo("Now trigger for shutdown Robot")

            self.fnLaunch(self.Launcher.launch_motor.value, False)
            
            
            self.move_base.cancel_all_goals()
            self.IR_Docking.cancel_all_goals()
            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()
            self.IST_Mission_server.cancel_all_goals()
            self.IST_Mission_operate.cancel_all_goals()
            self.ScanMotion.cancel_all_goals()
            self.UVC.cancel_all_goals()

            self.fnLaunch(self.Launcher.launch_io_action.value, False)
            self.fnLaunch(self.Launcher.launch_autodock.value, False)

            if self.model_type == "B":
                self.remote_launch = "/launch/include/tf/tf_"+ self.serial_no + ".launch"
            else:
                # model A common tf
                if (self.serial_no =="20210001A") or (self.serial_no =="20210005A"):
                    self.remote_launch = "/launch/include/tf/tf_"+ self.serial_no + ".launch"
                else:
                    self.remote_launch = "/launch/aragorn_remote.launch"
            self.fnLaunch(self.Launcher.launch_remote.value, False)

            # select configure lidar 
            if self.serial_no == "20210001B":
                self.fnLaunch(self.Launcher.launch_lidar_unique.value, False)
            else:
                self.fnLaunch(self.Launcher.launch_lidar.value, False)
            
            self.fnLaunch(self.Launcher.launch_sound.value, False)
            self.fnLaunch(self.Launcher.launch_io.value, False)
            self.fnLaunch(self.Launcher.launch_io_action.value, False)
            self.fnLaunch(self.Launcher.launch_camera.value, False)
            self.fnLaunch(self.Launcher.launch_bms.value, False)
            self.fnLaunch(self.Launcher.launch_imu.value, False)
            self.fnLaunch(self.Launcher.launch_localization.value, False)
            self.fnLaunch(self.Launcher.launch_autodock.value, False)
            self.fnLaunch(self.Launcher.launch_robot_status.value, False)
            self.fnLaunch(self.Launcher.launch_dynamics_param.value, False)
            self.fnLaunch(self.Launcher.launch_diagnostics.value, False)
            self.fnLaunch(self.Launcher.launch_vel_filter.value, False)

            os.system("rosnode kill --all")
            os.system('echo \"a\" | sudo -S shutdown now')
        
        self.is_triggered = False

    def fnLaunch(self, launch_num, is_start):
        if launch_num == self.Launcher.launch_manual_docking.value:
            if is_start == True:
                if self.launch_manual_docking_launched == False:
                    self.launch_manual_docking = roslaunch.scriptapi.ROSLaunch()
                    self.launch_manual_docking = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_manualdock.launch"])
                    self.launch_manual_docking_launched = True
                    self.launch_manual_docking.start()
                else:
                    pass
            else:
                if self.launch_manual_docking_launched == True:
                    self.launch_manual_docking_launched = False
                    self.launch_manual_docking.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_dynamics_param.value:
            if is_start == True:
                if self.launch_dynamics_param_launched == False:
                    self.launch_dynamics_param = roslaunch.scriptapi.ROSLaunch()
                    self.launch_dynamics_param = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_dynamic_param.launch"])
                    self.launch_dynamics_param_launched = True
                    self.launch_dynamics_param.start()
                else:
                    pass
            else:
                if self.launch_dynamics_param_launched == True:
                    self.launch_dynamics_param_launched = False
                    self.launch_dynamics_param.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_robot_status.value:
            if is_start == True:
                if self.launch_robot_status_launched == False:
                    self.launch_robot_status = roslaunch.scriptapi.ROSLaunch()
                    self.launch_robot_status = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_robot_status.launch"])
                    self.launch_robot_status_launched = True
                    self.launch_robot_status.start()
                else:
                    pass
            else:
                if self.launch_robot_status_launched == True:
                    self.launch_robot_status_launched = False
                    self.launch_robot_status.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_autodock.value:
            if is_start == True:
                if self.launch_autodock_launched == False:
                    self.launch_autodock = roslaunch.scriptapi.ROSLaunch()
                    self.launch_autodock = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_autodock.launch"])
                    self.launch_autodock_launched = True
                    self.launch_autodock.start()
                else:
                    pass
            else:
                if self.launch_autodock_launched == True:
                    self.launch_autodock_launched = False
                    self.launch_autodock.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_lidar_unique.value:
            if is_start == True:
                if self.launch_lidar_unique_launched == False:
                    self.launch_lidar_unique = roslaunch.scriptapi.ROSLaunch()
                    self.launch_lidar_unique = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_lidar_filter_unique.launch"])
                    self.launch_lidar_unique_launched = True
                    self.launch_lidar_unique.start()
                else:
                    pass
            else:
                if self.launch_lidar_unique_launched == True:
                    self.launch_lidar_unique_launched = False
                    self.launch_lidar_unique.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_motor.value:
            if is_start == True:
                if self.launch_motor_launched == False:
                    self.launch_motor = roslaunch.scriptapi.ROSLaunch()
                    self.launch_motor = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_motor.launch"])
                    self.launch_motor_launched = True
                    self.launch_motor.start()
                else:
                    pass
            else:
                if self.launch_motor_launched == True:
                    self.launch_motor_launched = False
                    self.launch_motor.shutdown()
                else:
                    pass
        
        if launch_num == self.Launcher.launch_sound.value:
            if is_start == True:
                if self.launch_sound_launched == False:
                    self.launch_sound = roslaunch.scriptapi.ROSLaunch()
                    self.launch_sound = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_sound.launch"])
                    self.launch_sound_launched = True
                    self.launch_sound.start()
                else:
                    pass
            else:
                if self.launch_sound_launched == True:
                    self.launch_sound_launched = False
                    self.launch_sound.shutdown()
                else:
                    pass

                    
        if launch_num == self.Launcher.launch_vel_filter.value:
            if is_start == True:
                if self.launch_vel_filter_launched == False:
                    self.launch_vel_filter = roslaunch.scriptapi.ROSLaunch()
                    self.launch_vel_filter = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('laser_vel_filter') + "/launch/laser_vel_filter.launch"])
                    self.launch_vel_filter_launched = True
                    self.launch_vel_filter.start()
                else:
                    pass
            else:
                if self.launch_vel_filter_launched == True:
                    self.launch_vel_filter_launched = False
                    self.launch_vel_filter.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_imu.value:
            if is_start == True:
                if self.launch_imu_launched == False:
                    self.launch_imu = roslaunch.scriptapi.ROSLaunch()
                    self.launch_imu = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_imu.launch"])
                    self.launch_imu_launched = True
                    self.launch_imu.start()
                else:
                    pass
            else:
                if self.launch_imu_launched == True:
                    self.launch_imu_launched = False
                    self.launch_imu.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_bms.value:
            if is_start == True:
                if self.launch_bms_launched == False:
                    self.launch_bms = roslaunch.scriptapi.ROSLaunch()
                    self.launch_bms = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_bms.launch"])
                    self.launch_bms_launched = True
                    self.launch_bms.start()
                else:
                    pass
            else:
                if self.launch_bms_launched == True:
                    self.launch_bms_launched = False
                    self.launch_bms.shutdown()
                else:
                    pass


        if launch_num == self.Launcher.launch_camera.value:
            if is_start == True:
                if self.launch_camera_launched == False:
                    self.launch_camera = roslaunch.scriptapi.ROSLaunch()
                    self.launch_camera = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_camera.launch"])
                    self.launch_camera_launched = True
                    self.launch_camera.start()
                else:
                    pass
            else:
                if self.launch_camera_launched == True:
                    self.launch_camera_launched = False
                    self.launch_camera.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_localization.value:
            if is_start == True:
                if self.launch_localization_launched == False:
                    self.launch_localization = roslaunch.scriptapi.ROSLaunch()
                    self.launch_localization = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_localization.launch"])
                    self.launch_localization_launched = True
                    self.launch_localization.start()
                else:
                    pass
            else:
                if self.launch_localization_launched == True:
                    self.launch_localization_launched = False
                    self.launch_localization.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_web.value:
            if is_start == True:
                if self.launch_web_launched == False:
                    self.launch_web = roslaunch.scriptapi.ROSLaunch()
                    self.launch_web = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('web_interface') + "/launch/my.launch"])
                    self.launch_web_launched = True
                    self.launch_web.start()
                else:
                    pass
            else:
                if self.launch_web_launched == True:
                    self.launch_web_launched = False
                    self.launch_web.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_diagnostics.value:
            if is_start == True:
                if self.launch_diagnostics_launched == False:
                    self.launch_diagnostics = roslaunch.scriptapi.ROSLaunch()
                    self.launch_diagnostics = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup')  + "/launch/aragorn_diagnostics.launch"])
                    self.launch_diagnostics_launched = True
                    self.launch_diagnostics.start()
                else:
                    pass
            else:
                if self.launch_diagnostics_launched == True:
                    self.launch_diagnostics_launched = False
                    self.launch_diagnostics.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_led.value:
            if is_start == True:
                if self.launch_led_launched == False:
                    self.launch_led = roslaunch.scriptapi.ROSLaunch()
                    self.launch_led = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_control') + "/launch/aragorn_led_status.launch"])
                    self.launch_led_launched = True
                    self.launch_led.start()
                else:
                    pass
            else:
                if self.launch_led_launched == True:
                    self.launch_led_launched = False
                    self.launch_led.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_io.value:
            if is_start == True:
                if self.launch_io_launched == False:
                    self.launch_io = roslaunch.scriptapi.ROSLaunch()
                    self.launch_io = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_io.launch"])
                    self.launch_io_launched = True
                    self.launch_io.start()
                else:
                    pass
            else:
                if self.launch_io_launched == True:
                    self.launch_io_launched = False
                    self.launch_io.shutdown()
                else:
                    pass
        
        if launch_num == self.Launcher.launch_io_action.value:
            if is_start == True:
                if self.launch_io_action_launched == False:
                    self.launch_io_action = roslaunch.scriptapi.ROSLaunch()
                    self.launch_io_action = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_io_action.launch"])
                    self.launch_io_action_launched = True
                    self.launch_io_action.start()
                else:
                    pass
            else:
                if self.launch_io_action_launched == True:
                    self.launch_io_action_launched = False
                    self.launch_io_action.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_core.value:
            if is_start == True:
                if self.launch_core_launched == False:
                    self.launch_core = roslaunch.scriptapi.ROSLaunch()
                    self.launch_core = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_core.launch"])
                    self.launch_core_launched = True
                    self.launch_core.start()
                else:
                    pass
            else:
                if self.launch_core_launched == True:
                    self.launch_core_launched = False
                    self.launch_core.shutdown()
                else:
                    pass

        elif launch_num == self.Launcher.launch_remote.value:
            if is_start == True:
                if self.launch_remote_launched == False:
                    self.launch_remote = roslaunch.scriptapi.ROSLaunch()
                    self.launch_remote = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + self.remote_launch])
                    self.launch_remote_launched = True
                    self.launch_remote.start()
                else:
                    pass
            else:
                if self.launch_remote_launched == True:
                    self.launch_remote_launched = False
                    self.launch_remote.shutdown()
                else:
                    pass

        elif launch_num == self.Launcher.launch_lidar.value:
            if is_start == True:
                if self.launch_lidar_launched == False:
                    self.launch_lidar = roslaunch.scriptapi.ROSLaunch()
                    self.launch_lidar = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('aragorn_bringup') + "/launch/aragorn_lidar_filter.launch"])
                    self.launch_lidar_launched = True
                    self.launch_lidar.start()
                else:
                    pass
            else:
                if self.launch_lidar_launched == True:
                    self.launch_lidar_launched = False
                    self.launch_lidar.shutdown()
                else:
                    pass
    def main(self):
        rospy.spin()
    
if __name__=='__main__':
    rospy.init_node('core_node_controller')
    node = CoreNodeController()
    node.main()