hostname: "localhost"
username: "istdbUser"
password: "interface2563"
database: "istuvd"
oauth2_tablename: "oauth_access_tokens"
mapname_table: "ros_map_server"
mapdata_table: "ros_map_bin"
ros_options_table: "ros_options"
ros_gui_maps_table: "ros_maps"
