#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
import roslaunch
import numpy as np
import rospkg
import subprocess
import os
import sys
#import nmcli
import time
from enum import Enum
from std_msgs.msg import UInt8, Bool, Int8

import actionlib
from actionlib_msgs.msg import *


# from ir_auto_docking.msg import AutodockOperateAction, AutodockOperateGoal
from web_interface_msgs.msg import DockingAction
from web_interface_msgs.msg import RouteFollowAction
# from mission_msgs.msg import MissionOperateAction
# from mission_msgs.msg import MissionRunAction
from move_base_msgs.msg import MoveBaseAction
from matrix_msgs.msg import SHLOperationAction, CenterVShapeTrackingAction, BoxOperationAction, ARTrackOperationAction, ROHMChargerOperationAction, SerialOperationAction, SwapEnviOperationAction, XbeeCommunicationAction, RobotMode
from matrix_schedule_operation.msg import ScheduleAction
from matrix_msgs.msg import *
from matrix_msgs.srv import *
from autodock_core.msg import AutoDockingAction

# from matrix_io_action.msg import ScanMotionAction
# from matrix_io_action.msg import UVCAction
from std_srvs.srv import SetBool, SetBoolResponse
from media_player.srv import *

from dynamic_reconfigure.server import Server
from matrix_system.cfg import MatrixLaunchControllerConfig


class CoreNodeController():
    def __init__(self):

        self.serial_no = os.environ["serial_no"]
        self.model = os.environ["model"]
        self.sub_model = os.environ["sub_model"]
        self.hw_ver = os.environ["hw_ver"]
        self.imu_model = os.environ["imu_model"]

        self.model_launch_pkg = "matrix_" + self.model + "_bringup"

        # get param for skip launch
        self.skip_bms_base = rospy.get_param('~skip_bms_base', False)
        self.skip_bms_plugin = rospy.get_param('~skip_bms_plugin', False)
        self.skip_camera1 = rospy.get_param('~skip_camera1', False)
        self.skip_camera2 = rospy.get_param('~skip_camera2', False)
        self.skip_camera3 = rospy.get_param('~skip_camera3', False)
        self.skip_camera_rear = rospy.get_param('~skip_camera_rear', False)
        self.skip_base = rospy.get_param('~skip_base', False)
        self.skip_diagnostics = rospy.get_param('~skip_diagnostics', False)
        self.skip_imu = rospy.get_param('~skip_imu', False)
        self.skip_lidar_front = rospy.get_param('~skip_lidar_front', False)
        self.skip_lidar_rear = rospy.get_param('~skip_lidar_rear', False)
        self.skip_localization = rospy.get_param('~skip_localization', False)
        self.skip_mcu01 = rospy.get_param('~skip_mcu01', False)
        self.skip_mcu02 = rospy.get_param('~skip_mcu02', False)
        self.skip_movement_state = rospy.get_param(
            '~skip_movement_state', False)
        self.skip_sound = rospy.get_param('~skip_sound', False)
        self.skip_tf = rospy.get_param('~skip_tf', False)
        self.skip_docking = rospy.get_param('~skip_docking', False)
        self.skip_dynamic_param = rospy.get_param('~skip_dynamic_param', False)
        self.skip_aragorn_bridge = rospy.get_param(
            '~skip_aragorn_bridge', False)
        self.skip_mode_controller = rospy.get_param(
            '~skip_mode_controller', False)
        self.skip_communication = rospy.get_param('~skip_communication', False)
        self.skip_serial_operation = rospy.get_param(
            '~skip_serial_operation', False)
        self.skip_swapmap_operation = rospy.get_param(
            '~skip_swapmap_operation', False)
        self.skip_lidar_merger = rospy.get_param('~skip_lidar_merger', False)
        self.skip_docking_operation = rospy.get_param(
            '~skip_docking_operation', False)
        self.skip_plugin_device = rospy.get_param('~skip_plugin_device', False)
        self.skip_ar3mark_operation_rear = rospy.get_param(
            '~skip_ar3mark_operation_rear', False)
        self.skip_ar3mark_operation_front = rospy.get_param(
            '~skip_ar3mark_operation_front', False)
        self.skip_bumper = rospy.get_param('~skip_bumper_operation', False)
        self.skip_docking_ar_operation = rospy.get_param(
            '~skip_docking_ar_operation', False)
        self.skip_wall_follower_operation = rospy.get_param(
            '~skip_wall_follower_operation', False)
        self.skip_offline_control_operation = rospy.get_param(
            '~skip_offline_control_operation', False)
        self.skip_cvshape_operation = rospy.get_param(
            '~skip_cvshape_operation', False)
        self.skip_io_operation = rospy.get_param('~skip_io_operation', False)
        self.skip_sim = rospy.get_param('~skip_sim', True)

        self.matrixflow_ready = rospy.get_param('~matrixflow_ready', 1)
        self.matrixflow_start_motor = rospy.get_param(
            '~matrixflow_start_motor', 1)
        self.matrixflow_emergency = rospy.get_param('~matrixflow_emergency', 2)
        self.matrixflow_cancel_movement = rospy.get_param(
            '~matrixflow_cancel_movement', 0)
        self.matrixflow_cancel_all = rospy.get_param(
            '~matrixflow_cancel_all', 3)

        self.matrixflow_state = [self.matrixflow_ready, self.matrixflow_start_motor,
                                 self.matrixflow_emergency, self.matrixflow_cancel_movement, self.matrixflow_cancel_all]
        self.matrixflow_state_de = [self.matrixflow_ready, self.matrixflow_start_motor,
                                    self.matrixflow_emergency, self.matrixflow_cancel_movement, self.matrixflow_cancel_all]
        self.matrixflow_state_prev = [self.matrixflow_ready, self.matrixflow_start_motor,
                                      self.matrixflow_emergency, self.matrixflow_cancel_movement, self.matrixflow_cancel_all]
        self._isInitialDynamics = False

        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace(
            'matrix_system/script', '')

        self.rospack = rospkg.RosPack()

        # self.tablet_discon = rospy.Service("/matrix_launchctl/tablet_discon", self.cbTabletDiscon)

        # self.sub_start_up = rospy.Subscriber('/matrix_io/diagnostics', Bool, self.cbStartRobot, queue_size=1)
        self.sub_mode = rospy.Subscriber(
            '/matrix_mode_controller/mode', RobotMode, self.cbModeLaunch, queue_size=1)
        self.sub_SoftStartIMU = rospy.Subscriber(
            '/matrix_io/soft_start_imu', Bool, self.cbSoftStartIMU, queue_size=1)
        # self.sub_emer = rospy.Subscriber('/matrix_io/emergency', Int8, self.cbEmer, queue_size=1)

        self.cancel_service_server = rospy.Service(
            'matrix_launch_controller/cancel_action', SetBool, self.cbCancelAction)
        self.action_cantroller_server = rospy.Service(
            'matrix_launch_controller/action_controller', ActionController, self.cbActionControllerServer)

        self.srv = Server(MatrixLaunchControllerConfig, self.cbDynamics)

        # self.Launcher = Enum('Launcher', 'launch_plugin_device launch_docking_operation launch_lidar_merger launch_aragorn_bridge launch_dynamics_param launch_movement_state launch_autodock launch_vel_filter launch_sound launch_base launch_imu launch_bms_base launch_bms_plugin launch_camera_rear launch_camera1 launch_camera2 launch_mcu01 launch_mcu02 launch_tf launch_lidar_front launch_lidar_rear  launch_diagnostics launch_localization launch_mode_controller launch_communication launch_serial_operation launch_swapmap_operation')
        self.Launcher = Enum('Launcher', 'launch_sim launch_io_operation launch_cvshape_operation launch_wall_follower_operation launch_offline_control_operation launch_init launch_plugin_device launch_docking_ar_operation launch_bumper launch_ar3mark_operation_front launch_ar3mark_operation_rear launch_docking_operation launch_lidar_merger launch_aragorn_bridge launch_dynamics_param launch_movement_state launch_autodock launch_vel_filter launch_sound launch_base launch_imu launch_bms_base launch_bms_plugin launch_camera_rear launch_camera1 launch_camera2 launch_camera3 launch_mcu01 launch_mcu02 launch_tf launch_lidar_front launch_lidar_rear launch_diagnostics launch_localization launch_mode_controller launch_communication launch_serial_operation launch_swapmap_operation')

        # class Launcher(Enum, self):
        #     launch_init = 0
        #     launch_plugin_device = 1
        #     launch_docking_operation = 2
        #     launch_lidar_merger = 3
        #     launch_aragorn_bridge = 4
        #     launch_dynamics_param = 5
        #     launch_movement_state = 6
        #     launch_autodock = 7
        #     launch_vel_filter = 8
        #     launch_sound = 9
        #     launch_base = 10
        #     launch_imu = 11
        #     launch_bms_base = 12
        #     launch_bms_plugin = 13
        #     launch_camera_rear = 14
        #     launch_camera1 = 15
        #     launch_camera2 = 16
        #     launch_mcu01 = 17
        #     launch_mcu02 = 18
        #     launch_tf = 19
        #     launch_lidar_front = 20
        #     launch_lidar_rear = 21
        #     launch_diagnostics = 22
        #     launch_localization = 23
        #     launch_mode_controller = 24
        #     launch_communication = 25
        #     launch_serial_operation = 26
        #     launch_swapmap_operation = 27

        self.CurrentMode = Enum('CurrentMode', 'idle start_motor shutdown_motor shutdown_robot emergency fucn_1 down_stairs tablet_loss_commu uvc_on uvc_off ready_to_start docking_mode_on docking_mode_off error_device charger_on charger_off reset emergency_case_active emergency_charge robot_operation_begin robot_operation_finish')

        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)

        self.Launcher_state = Enum('Launcher_state', 'start stop skip')

        self.move_base = actionlib.SimpleActionClient(
            "move_base", MoveBaseAction)
        # self.serial_operation = actionlib.SimpleActionClient("matrix_serial_operation", SerialOperationAction)
        # self.serial_operation_485 = actionlib.SimpleActionClient("matrix_serial_operation_485", SerialOperationAction)
        self.serial_operation = actionlib.SimpleActionClient(
            "matrix_serial_operation", SerialOperationAction)
        self.serial_operation_485 = actionlib.SimpleActionClient(
            "matrix_serial_operation_485", SerialOperationAction)
        self.movement_operation = actionlib.SimpleActionClient(
            "matrix_xbeemovement_server", XbeeCommunicationAction)
        self.artrack_operation = actionlib.SimpleActionClient(
            "matrix_artrack_operation", ARTrackOperationAction)
        self.swapenvi_operation = actionlib.SimpleActionClient(
            "matrix_swapenvi_operation", SwapEnviOperationAction)
        self.docking_operation = actionlib.SimpleActionClient(
            "matrix_docking_operation", ROHMChargerOperationAction)
        self.schedule_operation = actionlib.SimpleActionClient(
            "matrix_schedule_operation", ScheduleAction)
        self.ar3mark_operation = actionlib.SimpleActionClient(
            "autodock_action", AutoDockingAction)
        self.handlemat_operation = actionlib.SimpleActionClient(
            "matoperate_server", BoxOperationAction)
        self.ardocking_operation = actionlib.SimpleActionClient(
            "matrix_docking_ar_operation", ARDockingOperationAction)
        self.offcontrol_operation = actionlib.SimpleActionClient(
            "matrix_offline_control_operation", OfflineControlOperationAction)
        self.wallfollowing_operation = actionlib.SimpleActionClient(
            "matrix_wall_following_operation", WallFollowingAction)
        self.cvshape_operation = actionlib.SimpleActionClient(
            "matrix_cvshape_operation", CenterVShapeTrackingAction)
        self.cvshape2dir_operation = actionlib.SimpleActionClient(
            "matrix_cvshape_2dir_operation", CenterVShapeTrackingAction)
        self.dockingmulti_operation = actionlib.SimpleActionClient(
            "matrix_docking_multi_methods_operation", ARDockingOperationMultiMethodsAction)
        self.shelf_lift_operation = actionlib.SimpleActionClient(
            "matrix_shelf_lift_operation", SHLOperationAction) 
        # self.io_operation = actionlib.SimpleActionClient("matrix_cvshape_operation", OfflineControlOperationAction)
        # self.matrix_movement = actionlib.SimpleActionClient("move_base", MoveBaseAction)

        # self.MoveBase = actionlib.SimpleActionClient("move_base", MoveBaseAction)
        # self.IR_Manual_Docking = actionlib.SimpleActionClient("manualdocking_server", AutodockOperateAction)
        # self.IR_Docking = actionlib.SimpleActionClient("autodocking_server", AutodockOperateAction)
        self.IST_Docking = actionlib.SimpleActionClient(
            "ist_docking", DockingAction)
        self.IST_RouteFollow = actionlib.SimpleActionClient(
            "ist_route_follow", RouteFollowAction)
        # self.IST_Mission_server = actionlib.SimpleActionClient("missions_server", MissionRunAction)
        # self.IST_Mission_operate = actionlib.SimpleActionClient("missions_operate", MissionOperateAction)
        # self.ScanMotion = actionlib.SimpleActionClient("scan_motion_server", ScanMotionAction)
        # self.UVC = actionlib.SimpleActionClient("uvc_server", UVCAction)

        self.launch_base_launched = False
        self.launch_vel_filter_launched = False
        self.launch_sound_launched = False
        self.launch_mcu01_launched = False
        self.launch_mcu02_launched = False
        self.launch_bms_base_launched = False
        self.launch_bms_plugin_launched = False
        self.launch_imu_launched = False
        self.launch_camera1_launched = False
        self.launch_camera2_launched = False
        self.launch_camera3_launched = False
        self.launch_camera_rear_launched = False
        self.launch_tf_launched = False
        self.launch_lidar_front_launched = False
        self.launch_lidar_rear_launched = False
        self.launch_diagnostics_launched = False
        self.launch_localization_launched = False
        self.launch_autodock_launched = False
        self.launch_movement_state_launched = False
        self.launch_dynamics_param_launched = False
        self.launch_manual_docking_launched = False
        self.launch_aragorn_bridge_launched = False
        self.launch_mode_controller_launched = False
        self.launch_communication_launched = False
        self.launch_serial_operation_launched = False
        self.launch_swapmap_operation_launched = False
        self.launch_lidar_merger_launched = False
        self.launch_docking_operation_launched = False
        self.launch_plugin_device_launched = False
        self.launch_ar3mark_operation_rear_launched = False
        self.launch_ar3mark_operation_front_launched = False
        self.launch_bumper_launched = False
        self.launch_docking_ar_operation_launched = False
        self.launch_wall_follower_operation_launched = False
        self.launch_offline_control_operation_launched = False
        self.launch_cvshape_operation_launched = False
        self.launch_io_operation_launched = False
        self.launch_sim_launched = False

        self.is_triggered = False
        self.is_service_triggerd = False

        self.current_mode = self.CurrentMode.idle.value

        self.AllowStartIMU = False

        self.debugTest = True

        # self.model_type = self.serial_no[8]

        self.remote_launch = ""

        # print "down can0"
        # os.system('echo \"a\" | sudo -S ip link set can0 down')
        # time.sleep(1)
        # print "bringup can0"
        # os.system('echo \"a\" | sudo -S ip link set can0 up type can bitrate 250000')
        # print "can0 bringup success!!!"

        self.initial_robot()

        self.fnControlNode_srv = ActionControllerRequest()

        loop_rate = rospy.Rate(10)  # 10hz
        while not rospy.is_shutdown():
            if self.is_triggered == True:
                self.fnControlNode()

            if self.is_service_triggerd == True:
                self.fnControlNodeService()

            loop_rate.sleep()
        
        # if self.hw_ver == "smr200A":
        #     # os.system('echo \"a\" | sudo -S ip link set can0 up type can bitrate 250000')
        #     self.init_canbus("can0", 250000)
        # elif (self.hw_ver == "smr100A") or (self.hw_ver == "smr100L") or (self.hw_ver == "sdr100C")or (self.hw_ver == "sdr100D"):
        #     self.init_canbus("can0", 500000)
        # else:
        #     pass
        

    # def emergency_case(self):
    #     self.MoveBase.cancel_all_goals()
    #     self.IR_Docking.cancel_all_goals()
    #     self.IST_Docking.cancel_all_goals()
    #     self.IST_RouteFollow.cancel_all_goals()
    #     self.IST_Mission_server.cancel_all_goals()
    #     self.IST_Mission_operate.cancel_all_goals()
    #     self.ScanMotion.cancel_all_goals()
    #     self.UVC.cancel_all_goals()

    # def cbTabletDiscon(self, req):
    #     if req.data:
    #         self.fnLaunch(self.Launcher.launch_base.value, False)

    #         self.move_base.cancel_all_goals()
    #         self.IR_Docking.cancel_all_goals()
    #         self.IST_Docking.cancel_all_goals()
    #         self.IST_RouteFollow.cancel_all_goals()
    #         self.IST_Mission_server.cancel_all_goals()
    #         self.IST_Mission_operate.cancel_all_goals()
    #         self.ScanMotion.cancel_all_goals()
    #         self.UVC.cancel_all_goals()

    #         self.fnLaunch(self.Launcher.launch_mcu01_action.value, False)
    #     else:
    #         pass

    #     return True, "[matrix_launchctl]:Tablet discon mode trigger!!!"

    def cbSoftStartIMU(self, msg):
        pass
        # if msg.data and self.serial_no == "SMR020020220002A":
        #     self.fnLaunch(self.Launcher.launch_imu.value, self.skip_imu, True)
        # else:
        #     pass

    def cbCancelAction(self, req):
        if req.data:
            try:
                os.system('killall -9 vlc')
            except:
                pass

            try:
                media_playerSRV = rospy.ServiceProxy(
                    'media_player_server', MediaPlayer)
                srv_req = MediaPlayerRequest()

                srv_req.cmd = "clear"

                srv_res = media_playerSRV(srv_req)
            except:
                pass

            # os.system('echo \"a\" | sudo -S service ONodeREDUser stop')

            self.move_base.cancel_all_goals()
            self.serial_operation.cancel_all_goals()
            self.serial_operation_485.cancel_all_goals()
            self.movement_operation.cancel_all_goals()
            self.artrack_operation.cancel_all_goals()
            self.swapenvi_operation.cancel_all_goals()
            self.docking_operation.cancel_all_goals()
            self.schedule_operation.cancel_all_goals()
            self.ar3mark_operation.cancel_all_goals()
            self.handlemat_operation.cancel_all_goals()
            self.ardocking_operation.cancel_all_goals()
            self.offcontrol_operation.cancel_all_goals()
            self.wallfollowing_operation.cancel_all_goals()
            self.cvshape_operation.cancel_all_goals()
            self.cvshape2dir_operation.cancel_all_goals()
            self.dockingmulti_operation.cancel_all_goals()
            self.shelf_lift_operation.cancel_all_goals()

            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()

            # os.system('echo \"a\" | sudo -S service ONodeREDUser start')
            # os.system('echo \"a\" | sudo -S service ONodeREDUser restart')
            self.MatrixFlowController(self.matrixflow_state[4])

            rospy.logwarn("cancel node success")

        return True, "Success"

    def cbDynamics(self, config, level):

        if not config.restore_default:
            if config.manual_matrixflow_setup != 0:
                self.MatrixFlowController(config.manual_matrixflow_setup)
                config.matrixflow_ready = self.matrixflow_state_prev[0]
                config.matrixflow_start_motor = 0
                config.matrixflow_emergency = 0
                config.matrixflow_cancel_movement = 0
                config.matrixflow_cancel_all = 0
                self._isInitialDynamics = False
            else:
                if not self._isInitialDynamics:
                    config.matrixflow_ready = self.matrixflow_state_prev[0]
                    config.matrixflow_start_motor = self.matrixflow_state_prev[1]
                    config.matrixflow_emergency = self.matrixflow_state_prev[2]
                    config.matrixflow_cancel_movement = self.matrixflow_state_prev[3]
                    config.matrixflow_cancel_all = self.matrixflow_state_prev[4]
                    self._isInitialDynamics = True
                else:
                    pass
        else:
            config.manual_matrixflow_setup = 0
            config.matrixflow_ready = self.matrixflow_state_de[0]
            config.matrixflow_start_motor = self.matrixflow_state_de[1]
            config.matrixflow_emergency = self.matrixflow_state_de[2]
            config.matrixflow_cancel_movement = self.matrixflow_state_de[3]
            config.matrixflow_cancel_all = self.matrixflow_state_de[4]
            config.restore_default = False

        self.matrixflow_state[0] = config.matrixflow_ready
        self.matrixflow_state[1] = config.matrixflow_start_motor
        self.matrixflow_state[2] = config.matrixflow_emergency
        self.matrixflow_state[3] = config.matrixflow_cancel_movement
        self.matrixflow_state[4] = config.matrixflow_cancel_all

        return config

    def MatrixFlowController(self, mode):
        success = True
        if mode == 0:  # NONE
            pass
        elif mode == 1:  # START
            os.system('echo \"a\" | sudo -S systemctl start ONodeREDUser.service')
        elif mode == 2:  # STOP
            os.system('echo \"a\" | sudo -S systemctl stop ONodeREDUser.service')
        elif mode == 3:  # RESTART
            os.system(
                'echo \"a\" | sudo -S systemctl restart ONodeREDUser.service')
        else:
            rospy.logwarn(
                "[Matrix Launch control]: Not found mode: {}".format(mode))

        return success

    def cbActionControllerServer(self, req):
        rospy.loginfo(
            "[Matrix Launch control]: Request cmd %s, action_name %s ", req.cmd, req.action_name)
        self.fnControlNode_srv = req
        self.is_service_triggerd = True
        success = True
        return success, ""

    # fix bug only use "Signal in main thread"
    def fnControlNodeService(self):
        if self.is_service_triggerd:
            if self.fnControlNode_srv.cmd == ActionControllerRequest.CMD_ACTION_START or self.fnControlNode_srv.cmd == ActionControllerRequest.CMD_ACTION_KILL:
                # get lauch state
                action_launch_state = False
                if self.fnControlNode_srv.cmd == ActionControllerRequest.CMD_ACTION_START:
                    action_launch_state = True
                else:
                    pass

                # get Action launch file
                action_name = self.Launcher.launch_init.value
                if self.fnControlNode_srv.action_name == ActionControllerRequest.AC_AR3_REAR:
                    action_name = self.Launcher.launch_ar3mark_operation_rear.value
                elif self.fnControlNode_srv.action_name == ActionControllerRequest.AC_AR3_FRONT:
                    action_name = self.Launcher.launch_ar3mark_operation_front.value
                else:
                    rospy.logerr(
                        "[Matrix Launch control]: Not found action name %s, please in matix_msgs/ActionController.srv ", self.fnControlNode_srv.action_name)

                # launch control
                if action_name != self.Launcher.launch_init.value:
                    try:
                        self.fnLaunch(action_name, False, False)
                        rospy.loginfo("kill launch success")
                        self.fnLaunch(action_name, False, action_launch_state)
                        success = True
                    except ValueError:
                        rospy.logerr(
                            "[Matrix Launch control]: call launch error %s", self.fnControlNode_srv.action_name)
                        success = False
                    self.fnLaunch(action_name, False, action_launch_state)
                else:
                    success = False

            elif self.fnControlNode_srv.cmd == ActionControllerRequest.CMD_ACTION_CANCEL:
                if self.fnControlNode_srv.action_name == ActionControllerRequest.AC_MOVEMENT:
                    try:
                        self.MatrixFlowController(self.matrixflow_state[3])
                        self.move_base.cancel_all_goals()
                        self.movement_operation.cancel_all_goals()
                        self.docking_operation.cancel_all_goals()
                        self.ar3mark_operation.cancel_all_goals()
                        self.ardocking_operation.cancel_all_goals()
                        self.IST_Docking.cancel_all_goals()
                        self.IST_RouteFollow.cancel_all_goals()
                        self.offcontrol_operation.cancel_all_goals()
                        self.wallfollowing_operation.cancel_all_goals()
                        self.cvshape_operation.cancel_all_goals()
                        self.cvshape2dir_operation.cancel_all_goals()
                        self.dockingmulti_operation.cancel_all_goals()
                        self.shelf_lift_operation.cancel_all_goals()

                        self.IST_Docking.cancel_all_goals()
                        self.IST_RouteFollow.cancel_all_goals()
                    except:
                        rospy.logerr(
                            "[Matrix Launch control]: error while cancelling action %s", self.fnControlNode_srv.action_name)

                elif self.fnControlNode_srv.action_name == "STOP_ALL":
                    try:
                        os.system('killall -9 vlc')
                    except:
                        pass

                    try:
                        media_playerSRV = rospy.ServiceProxy(
                            'media_player_server', MediaPlayer)
                        srv_req = MediaPlayerRequest()

                        srv_req.cmd = "clear"

                        srv_res = media_playerSRV(srv_req)
                    except:
                        pass

                    # os.system('echo \"a\" | sudo -S service ONodeREDUser stop')

                    self.move_base.cancel_all_goals()
                    self.serial_operation.cancel_all_goals()
                    self.serial_operation_485.cancel_all_goals()
                    self.movement_operation.cancel_all_goals()
                    self.artrack_operation.cancel_all_goals()
                    self.swapenvi_operation.cancel_all_goals()
                    self.docking_operation.cancel_all_goals()
                    self.schedule_operation.cancel_all_goals()
                    self.ar3mark_operation.cancel_all_goals()
                    self.handlemat_operation.cancel_all_goals()
                    self.ardocking_operation.cancel_all_goals()
                    self.offcontrol_operation.cancel_all_goals()
                    self.wallfollowing_operation.cancel_all_goals()
                    self.cvshape_operation.cancel_all_goals()
                    self.cvshape2dir_operation.cancel_all_goals()
                    self.dockingmulti_operation.cancel_all_goals()
                    self.shelf_lift_operation.cancel_all_goals()

                    self.IST_Docking.cancel_all_goals()
                    self.IST_RouteFollow.cancel_all_goals()

                    # os.system('echo \"a\" | sudo -S service ONodeREDUser start')
                    self.MatrixFlowController(self.matrixflow_state[4])
                    success = True

                else:
                    rospy.logerr(
                        "[Matrix Launch control]: Not found action name %s, please in matix_msgs/ActionController.srv ", self.fnControlNode_srv.action_name)
                    success = False

            #  elif self.fnControlNode_srv.cmd == "MatrixFlowDesigner_setup":
            #     if self.fnControlNode_srv.arg0 == "start":
            #         os.system('echo \"a\" | sudo -S service ONodeREDUser start')
            #     elif self.fnControlNode_srv.arg0 == "stop":
            #         os.system('echo \"a\" | sudo -S service ONodeREDUser stop')
            #     elif self.fnControlNode_srv.arg0 == "restart":
            #         os.system('echo \"a\" | sudo -S service ONodeREDUser restart')
            #     else:
            #         pass
            else:
                rospy.logerr(
                    "[Matrix Launch control]: Not found cmd %s, please in matix_msgs/ActionController.srv ", self.fnControlNode_srv.cmd)
                success = False

            self.is_service_triggerd = False
        else:
            pass

    # def funcCancelAction(self):
    #     self.move_base.cancel_all_goals()
    #     self.serial_operation.cancel_all_goals()
    #     self.movement_operation.cancel_all_goals()
    #     self.artrack_operation.cancel_all_goals()
    #     self.swapenvi_operation.cancel_all_goals()
    #     self.docking_operation.cancel_all_goals()
    #     self.schedule_operation.cancel_all_goals()
    #     self.ar3mark_operation.cancel_all_goals()
    #     os.system('echo \"a\" | sudo -S service ONodeREDUser restart')
        
    def init_canbus(self, can_device, bitrate):
        print ("[matrix_launch_controller]: Force down {}".format(can_device))
        os.system('echo \"a\" | sudo -S ip link set '+ can_device +' down')
        print("")
        # time.sleep(1.0)
        print ("[matrix_launch_controller]: Bringup {}".format(can_device))
        os.system('echo \"a\" | sudo -S ip link set '+ can_device +' up type can bitrate ' + str(bitrate))
        # time.sleep(0.5)
        # self.NMT_service(0x00, "Reset Node")
        # print("")
        print ("[matrix_launch_controller]: {} bringup success!!!".format(can_device))


    def cbModeLaunch(self, mode_msg):
        # rospy.loginfo("Start core_controller with mode %d", mode_msg)
        if (self.current_mode == mode_msg.robot_mode):
            pass
        else:
            self.current_mode = mode_msg.robot_mode
            self.is_triggered = True

    def initial_robot(self):
        if self.debugTest:

            if self.hw_ver == "smr200A":
                # os.system('echo \"a\" | sudo -S ip link set can0 up type can bitrate 250000')
                self.init_canbus("can0", 250000)
            elif (self.hw_ver == "smr100A") or (self.hw_ver == "smr100L") or (self.hw_ver == "sdr100C")or (self.hw_ver == "sdr100D"):
                self.init_canbus("can0", 500000)
            elif self.hw_ver == "smr1000D":
                self.init_canbus("can0", 1000000)
            else:
                pass

            self.fnLaunch(self.Launcher.launch_camera1.value,
                          self.skip_camera1, True)
            # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_camera2.value,
                          self.skip_camera2, True)
            # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_camera3.value,
                          self.skip_camera3, True)
            # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_camera_rear.value,
                          self.skip_camera_rear, True)

            # rospy.sleep(5)

            self.fnLaunch(self.Launcher.launch_sound.value,
                          self.skip_sound, True)
            # rospy.sleep(1)
            # print(self.Launcher.launch_tf.value)
            self.fnLaunch(self.Launcher.launch_tf.value, self.skip_tf, True)
            # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_base.value,
                          self.skip_base, True)
            # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_lidar_front.value,
                          self.skip_lidar_front, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_lidar_rear.value,
                          self.skip_lidar_rear, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_lidar_merger.value,
                          self.skip_lidar_merger, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_mcu01.value,
                          self.skip_mcu01, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_mcu02.value,
                          self.skip_mcu02, True)
            # # rospy.sleep(1)
            # self.fnLaunch(self.Launcher.launch_camera1.value, self.skip_camera1, True)
            # # rospy.sleep(1)
            # self.fnLaunch(self.Launcher.launch_camera2.value, self.skip_camera2, True)
            # # rospy.sleep(1)
            # self.fnLaunch(self.Launcher.launch_camera3.value, self.skip_camera3, True)
            # # rospy.sleep(1)
            # self.fnLaunch(self.Launcher.launch_camera_rear.value, self.skip_camera_rear, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_bms_base.value,
                          self.skip_bms_base, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_bms_plugin.value,
                          self.skip_bms_plugin, True)
            # # rospy.sleep(1)

            self.fnLaunch(self.Launcher.launch_localization.value,
                          self.skip_localization, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_movement_state.value,
                          self.skip_movement_state, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_dynamics_param.value,
                          self.skip_dynamic_param, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_aragorn_bridge.value,
                          self.skip_aragorn_bridge, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_mode_controller.value,
                          self.skip_mode_controller, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_communication.value,
                          self.skip_communication, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_serial_operation.value,
                          self.skip_serial_operation, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_swapmap_operation.value,
                          self.skip_swapmap_operation, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_docking_operation.value,
                          self.skip_docking_operation, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_docking_ar_operation.value,
                          self.skip_docking_ar_operation, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_plugin_device.value,
                          self.skip_plugin_device, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_wall_follower_operation.value,
                          self.skip_wall_follower_operation, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_offline_control_operation.value,
                          self.skip_offline_control_operation, True)
            # # rospy.sleep(1)
            self.fnLaunch(self.Launcher.launch_cvshape_operation.value,
                          self.skip_cvshape_operation, True)

            # ------Simulation-------#
            self.fnLaunch(self.Launcher.launch_sim.value,
                          self.skip_sim, True)

            # # rospy.sleep(1)
            # # os.system('echo \"a\" | sudo -S service ONodeREDUser start')
            # # # rospy.sleep(1)

            if self.imu_model.find("razor9dof") != -1:
                rospy.sleep(10)
                self.fnLaunch(self.Launcher.launch_imu.value,
                              self.skip_imu, True)
                rospy.sleep(5)
            else:
                self.fnLaunch(self.Launcher.launch_imu.value,
                              self.skip_imu, True)

            self.fnLaunch(self.Launcher.launch_diagnostics.value,
                          self.skip_diagnostics, True)
            # rospy.sleep(10)
            # rospy.sleep(1)

        # try:
        #     os.system('echo \"a\" | sudo -S ip link set can0 up type can bitrate 250000')
        #     self.fnLaunch(self.Launcher.launch_sound.value, self.skip_sound, True)
        #     rospy.sleep(1)
        #     # print(self.Launcher.launch_tf.value)
        #     self.fnLaunch(self.Launcher.launch_tf.value, self.skip_tf, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_base.value, self.skip_base, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_lidar_front.value, self.skip_lidar_front, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_lidar_rear.value, self.skip_lidar_rear, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_lidar_merger.value, self.skip_lidar_merger, True)
        #     rospy.sleep(1)
        #     # self.fnLaunch(self.Launcher.launch_sound.value, self.skip_sound, True)
        #     self.fnLaunch(self.Launcher.launch_mcu01.value, self.skip_mcu01, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_mcu02.value, self.skip_mcu02, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_camera1.value, self.skip_camera1, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_camera2.value, self.skip_camera2, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_camera3.value, self.skip_camera3, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_camera_rear.value, self.skip_camera_rear, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_bms_base.value, self.skip_bms_base, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_bms_plugin.value, self.skip_bms_plugin, True)
        #     rospy.sleep(1)

        #     self.fnLaunch(self.Launcher.launch_localization.value, self.skip_localization, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_movement_state.value, self.skip_movement_state, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_dynamics_param.value, self.skip_dynamic_param, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_aragorn_bridge.value, self.skip_aragorn_bridge, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_mode_controller.value, self.skip_mode_controller, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_communication.value, self.skip_communication, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_serial_operation.value, self.skip_serial_operation, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_swapmap_operation.value, self.skip_swapmap_operation, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_docking_operation.value, self.skip_docking_operation, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_docking_ar_operation.value, self.skip_docking_ar_operation, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_plugin_device.value, self.skip_plugin_device, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_wall_follower_operation.value, self.skip_wall_follower_operation, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_offline_control_operation.value, self.skip_offline_control_operation, True)
        #     rospy.sleep(1)
        #     self.fnLaunch(self.Launcher.launch_cvshape_operation.value, self.skip_cvshape_operation, True)
        #     rospy.sleep(1)
        #     os.system('echo \"a\" | sudo -S service ONodeREDUser start')
        #     rospy.sleep(1)

        #     if self.serial_no.find("SMR") != -1:
        #         rospy.sleep(10)
        #         self.fnLaunch(self.Launcher.launch_imu.value, self.skip_imu, True)
        #         rospy.sleep(5)
        #     else:
        #         self.fnLaunch(self.Launcher.launch_imu.value, self.skip_imu, True)

        #     self.fnLaunch(self.Launcher.launch_diagnostics.value, self.skip_diagnostics, True)
        #     # rospy.sleep(10)
        #     rospy.sleep(1)

        # except:
        #     pass

    def fnControlNode(self):
        # Start_robot mode
        if self.current_mode == RobotMode.START_MOTOR:
            rospy.loginfo(
                "[Matrix Launch control]: Now trigger for Start motor drive")
            self.MatrixFlowController(self.matrixflow_state[1])
            # os.system('echo \"a\" | sudo -S service ONodeREDUser start')
            # self.fnLaunch(self.Launcher.launch_plugin_device.value,
            #               self.skip_plugin_device, True)
            # self.fnLaunch(self.Launcher.launch_laser_odom.value, self.skip_laser_odom, False)
            # self.fnLaunch(self.Launcher.launch_base.value, self.skip_core, True)

        elif self.current_mode == self.CurrentMode.ready_to_start.value:
            self.MatrixFlowController(self.matrixflow_state[0])
            # self.fnLaunch(self.Launcher.launch_base.value, self.skip_core, False)
            # self.fnLaunch(self.Launcher.launch_laser_odom.value, self.skip_laser_odom, True)

        elif self.current_mode == self.CurrentMode.fucn_1.value:
            rospy.loginfo(
                "[Matrix Launch control]: Now trigger for fucn_1 mauldocking")
            # goal = AutodockOperateGoal()
            # goal.order = 1
            # self.IR_Manual_Docking.send_goal(goal)

        elif self.current_mode == self.CurrentMode.reset.value:
            rospy.loginfo(
                "[Matrix Launch control]: Now trigger for reset io state and off motor control")
            # self.fnLaunch(self.Launcher.launch_base.value, self.skip_core, False)

            # self.IR_Manual_Docking.cancel_all_goals()
            # self.move_base.cancel_all_goals()
            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()

            # self.fnLaunch(self.Launcher.launch_mcu01_action.value, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
            # self.fnLaunch(self.Launcher.launch_manual_docking.value, False)

            # self.fnLaunch(self.Launcher.launch_base.value, False)
            # self.fnLaunch(self.Launcher.launch_mcu01_action.value, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)

        elif self.current_mode == RobotMode.EMERGENCY:
            rospy.loginfo(
                "[Matrix Launch control]: Now trigger for Stop motor drive")
            # self.fnLaunch(self.Launcher.launch_localization.value, False)
            # rospy.sleep(5)
            # os.system('echo \"a\" | sudo -S ip link set can0 down')
            # self.fnLaunch(self.Launcher.launch_base.value, self.skip_core, False)
            # self.fnLaunch(self.Launcher.launch_laser_odom.value, self.skip_laser_odom, False)
            try:
                self.MatrixFlowController(self.matrixflow_state[2])
                # os.system('echo \"a\" | sudo -S service ONodeREDUser stop')
                media_playerSRV = rospy.ServiceProxy(
                    'media_player_server', MediaPlayer)
                srv_req = MediaPlayerRequest()

                srv_req.cmd = "clear"

                srv_res = media_playerSRV(srv_req)
            except:
                pass

            try:
                os.system('killall -9 vlc')
            except:
                pass

            # self.IR_Manual_Docking.cancel_all_goals()
            self.move_base.cancel_all_goals()
            self.serial_operation.cancel_all_goals()
            self.movement_operation.cancel_all_goals()
            self.artrack_operation.cancel_all_goals()
            self.swapenvi_operation.cancel_all_goals()
            self.docking_operation.cancel_all_goals()
            self.schedule_operation.cancel_all_goals()
            self.ar3mark_operation.cancel_all_goals()
            self.handlemat_operation.cancel_all_goals()
            self.ardocking_operation.cancel_all_goals()
            self.offcontrol_operation.cancel_all_goals()
            self.wallfollowing_operation.cancel_all_goals()
            self.cvshape_operation.cancel_all_goals()
            self.cvshape2dir_operation.cancel_all_goals()
            self.dockingmulti_operation.cancel_all_goals()

            # self.fnLaunch(self.Launcher.launch_plugin_device.value,
            #               self.skip_plugin_device, False)

            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()

            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()

            # self.fnLaunch(self.Launcher.launch_mcu01_action.value, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
            # self.fnLaunch(self.Launcher.launch_manual_docking.value, False)
            # a = subprocess.run(["rosservice", "call", "/matrix_io/led_status"])

            # elif self.current_mode == self.CurrentMode.fucn_1.value:
        #     rospy.loginfo("[Matrix Launch control]: Now trigger for Relocalization")
        #     self.fnLaunch(self.Launcher.launch_localization.value, False)
        #     rospy.sleep(5)
        #     self.fnLaunch(self.Launcher.launch_localization.value, True)

        elif self.current_mode == self.CurrentMode.down_stairs.value:
            rospy.loginfo(
                "[Matrix Launch control]: Now trigger for Down stairs")
            self.fnLaunch(self.Launcher.launch_base.value,
                          self.skip_core, False)

        elif self.current_mode == self.CurrentMode.tablet_loss_commu.value:
            rospy.loginfo(
                "[Matrix Launch control]: Now trigger for Tablet loss comunicate")
            # self.fnLaunch(self.Launcher.launch_base.value, self.skip_core, False)
            # self.move_base.cancel_all_goals()
            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()
            # self.fnLaunch(self.Launcher.launch_mcu01_action.value, False)

        elif self.current_mode == self.CurrentMode.emergency_charge.value:
            rospy.loginfo(
                "[Matrix Launch control]: Now trigger for emergency charge")
            # self.fnLaunch(self.Launcher.launch_base.value, self.skip_core, False)

            # self.move_base.cancel_all_goals()
            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()
            # self.fnLaunch(self.Launcher.launch_mcu01_action.value, False)

        # Off_robot mode
        elif self.current_mode == self.CurrentMode.shutdown_robot.value:
            rospy.loginfo("Now trigger for shutdown Robot")

            self.fnLaunch(self.Launcher.launch_tf.value, self.skip_tf, False)
            self.fnLaunch(self.Launcher.launch_lidar_front.value,
                          self.skip_lidar_f, False)
            self.fnLaunch(self.Launcher.launch_lidar_r.value,
                          self.skip_lidar_r, False)
            self.fnLaunch(self.Launcher.launch_sound.value,
                          self.skip_sound, False)
            self.fnLaunch(self.Launcher.launch_mcu01.value,
                          self.skip_mcu1, False)
            self.fnLaunch(self.Launcher.launch_mcu02.value,
                          self.skip_mcu2, False)
            self.fnLaunch(self.Launcher.launch_camera.value,
                          self.skip_camera, False)
            self.fnLaunch(self.Launcher.launch_bms_base.value,
                          self.skip_bms, False)
            self.fnLaunch(self.Launcher.launch_imu.value, self.skip_imu, False)
            self.fnLaunch(self.Launcher.launch_localization.value,
                          self.skip_localization, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
            # self.fnLaunch(self.Launcher.launch_manual_docking.value, False)
            self.fnLaunch(self.Launcher.launch_movement_state.value,
                          self.skip_movement_state, False)
            # self.fnLaunch(self.Launcher.launch_dynamics_param.value, False)
            self.fnLaunch(self.Launcher.launch_diagnostics.value,
                          self.skip_diagnostics, False)
            # self.fnLaunch(self.Launcher.launch_vel_filter.value, False)
            self.fnLaunch(self.Launcher.launch_base.value,
                          self.skip_core, False)
            os.system("rosnode kill --all")
            os.system('echo \"a\" | sudo -S shutdown now')

        self.is_triggered = False

    def fnLaunch(self, launch_num, skip, is_start):

        # if launch_num == self.Launcher.launch_manual_docking.value:
        #     if is_start == True:
        #         if self.launch_manual_docking_launched == False:
        #             self.launch_manual_docking = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_manual_docking = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_manualdock.launch"])
        #             self.launch_manual_docking_launched = True
        #             self.launch_manual_docking.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_manual_docking_launched == True:
        #             self.launch_manual_docking_launched = False
        #             self.launch_manual_docking.shutdown()
        #         else:
        #             pass

        if launch_num == self.Launcher.launch_aragorn_bridge.value:
            if is_start == True:
                if self.launch_aragorn_bridge_launched == False:
                    self.launch_aragorn_bridge = roslaunch.scriptapi.ROSLaunch()
                    self.launch_aragorn_bridge = roslaunch.parent.ROSLaunchParent(
                        self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_aragorn_bridge.launch"])
                    self.launch_aragorn_bridge_launched = True
                    self.launch_aragorn_bridge.start()
                else:
                    pass
            else:
                if self.launch_aragorn_bridge_launched == True:
                    self.launch_aragorn_bridge_launched = False
                    self.launch_aragorn_bridge.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_dynamics_param.value:
            if is_start == True:
                if self.launch_dynamics_param_launched == False:
                    self.launch_dynamics_param = roslaunch.scriptapi.ROSLaunch()
                    self.launch_dynamics_param = roslaunch.parent.ROSLaunchParent(
                        self.uuid, [self.rospack.get_path('matrix_dynamic_parameter') + "/launch/dynamic_parameters.launch"])
                    self.launch_dynamics_param_launched = True
                    self.launch_dynamics_param.start()
                else:
                    pass
            else:
                if self.launch_dynamics_param_launched == True:
                    self.launch_dynamics_param_launched = False
                    self.launch_dynamics_param.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_movement_state.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_movement_state_launched == False:
                        self.launch_movement_state = roslaunch.scriptapi.ROSLaunch()
                        self.launch_movement_state = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_movement_state.launch"])
                        self.launch_movement_state_launched = True
                        self.launch_movement_state.start()
                    else:
                        pass
                else:
                    if self.launch_movement_state_launched == True:
                        self.launch_movement_state_launched = False
                        self.launch_movement_state.shutdown()
                    else:
                        pass
            else:
                pass

        # if launch_num == self.Launcher.launch_autodock.value:
        #     if is_start == True:
        #         if self.launch_autodock_launched == False:
        #             self.launch_autodock = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_autodock = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_autodock.launch"])
        #             self.launch_autodock_launched = True
        #             self.launch_autodock.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_autodock_launched == True:
        #             self.launch_autodock_launched = False
        #             self.launch_autodock.shutdown()
        #         else:
        #             pass

        if launch_num == self.Launcher.launch_base.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_base_launched == False:
                        self.launch_base = roslaunch.scriptapi.ROSLaunch()
                        self.launch_base = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/base.launch"])
                        self.launch_base_launched = True
                        self.launch_base.start()
                    else:
                        pass
                else:
                    if self.launch_base_launched == True:
                        self.launch_base_launched = False
                        self.launch_base.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_sound.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_sound_launched == False:
                        self.launch_sound = roslaunch.scriptapi.ROSLaunch()
                        self.launch_sound = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_sound.launch"])
                        self.launch_sound_launched = True
                        self.launch_sound.start()
                    else:
                        pass
                else:
                    if self.launch_sound_launched == True:
                        self.launch_sound_launched = False
                        self.launch_sound.shutdown()
                    else:
                        pass
            else:
                pass

        # if launch_num == self.Launcher.launch_vel_filter.value:
        #     if is_start == True:
        #         if self.launch_vel_filter_launched == False:
        #             self.launch_vel_filter = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_vel_filter = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('laser_vel_filter') + "/launch/laser_vel_filter.launch"])
        #             self.launch_vel_filter_launched = True
        #             self.launch_vel_filter.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_vel_filter_launched == True:
        #             self.launch_vel_filter_launched = False
        #             self.launch_vel_filter.shutdown()
        #         else:
        #             pass

        if launch_num == self.Launcher.launch_imu.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_imu_launched == False:
                        self.launch_imu = roslaunch.scriptapi.ROSLaunch()
                        self.launch_imu = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/imu.launch"])
                        self.launch_imu_launched = True
                        self.launch_imu.start()
                    else:
                        pass
                else:
                    if self.launch_imu_launched == True:
                        self.launch_imu_launched = False
                        self.launch_imu.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_bms_base.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_bms_base_launched == False:
                        self.launch_bms_base = roslaunch.scriptapi.ROSLaunch()
                        self.launch_bms_base = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/bms_base.launch"])
                        self.launch_bms_base_launched = True
                        self.launch_bms_base.start()
                    else:
                        pass
                else:
                    if self.launch_bms_base_launched == True:
                        self.launch_bms_base_launched = False
                        self.launch_bms_base.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_bms_plugin.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_bms_plugin_launched == False:
                        self.launch_bms_plugin = roslaunch.scriptapi.ROSLaunch()
                        self.launch_bms_plugin = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/bms_plugin.launch"])
                        self.launch_bms_plugin_launched = True
                        self.launch_bms_plugin.start()
                    else:
                        pass
                else:
                    if self.launch_bms_plugin_launched == True:
                        self.launch_bms_plugin_launched = False
                        self.launch_bms_plugin.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_camera1.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_camera1_launched == False:
                        self.launch_camera1 = roslaunch.scriptapi.ROSLaunch()
                        self.launch_camera1 = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/camera1.launch"])
                        self.launch_camera1_launched = True
                        self.launch_camera1.start()
                    else:
                        pass
                else:
                    if self.launch_camera1_launched == True:
                        self.launch_camera1_launched = False
                        self.launch_camera1.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_camera2.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_camera2_launched == False:
                        self.launch_camera2 = roslaunch.scriptapi.ROSLaunch()
                        self.launch_camera2 = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/camera2.launch"])
                        self.launch_camera2_launched = True
                        self.launch_camera2.start()
                    else:
                        pass
                else:
                    if self.launch_camera2_launched == True:
                        self.launch_camera2_launched = False
                        self.launch_camera2.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_camera3.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_camera3_launched == False:
                        self.launch_camera3 = roslaunch.scriptapi.ROSLaunch()
                        self.launch_camera3 = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/camera3.launch"])
                        self.launch_camera3_launched = True
                        self.launch_camera3.start()
                    else:
                        pass
                else:
                    if self.launch_camera3_launched == True:
                        self.launch_camera3_launched = False
                        self.launch_camera3.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_camera_rear.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_camera_rear_launched == False:
                        self.launch_camera_rear = roslaunch.scriptapi.ROSLaunch()
                        self.launch_camera_rear = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/camera_rear.launch"])
                        self.launch_camera_rear_launched = True
                        self.launch_camera_rear.start()
                    else:
                        pass
                else:
                    if self.launch_camera_rear_launched == True:
                        self.launch_camera_rear_launched = False
                        self.launch_camera_rear.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_localization.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_localization_launched == False:
                        self.launch_localization = roslaunch.scriptapi.ROSLaunch()
                        self.launch_localization = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/localization.launch"])
                        self.launch_localization_launched = True
                        self.launch_localization.start()
                    else:
                        pass
                else:
                    if self.launch_localization_launched == True:
                        self.launch_localization_launched = False
                        self.launch_localization.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_diagnostics.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_diagnostics_launched == False:
                        self.launch_diagnostics = roslaunch.scriptapi.ROSLaunch()
                        self.launch_diagnostics = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/diagnostics.launch"])
                        self.launch_diagnostics_launched = True
                        self.launch_diagnostics.start()
                    else:
                        pass
                else:
                    if self.launch_diagnostics_launched == True:
                        self.launch_diagnostics_launched = False
                        self.launch_diagnostics.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_mcu01.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_mcu01_launched == False:
                        self.launch_mcu01 = roslaunch.scriptapi.ROSLaunch()
                        self.launch_mcu01 = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/mcu01.launch"])
                        self.launch_mcu01_launched = True
                        self.launch_mcu01.start()
                    else:
                        pass
                else:
                    if self.launch_mcu01_launched == True:
                        self.launch_mcu01_launched = False
                        self.launch_mcu01.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_mcu02.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_mcu02_launched == False:
                        self.launch_mcu02 = roslaunch.scriptapi.ROSLaunch()
                        self.launch_mcu02 = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/mcu02.launch"])
                        self.launch_mcu02_launched = True
                        self.launch_mcu02.start()
                    else:
                        pass
                else:
                    if self.launch_mcu02_launched == True:
                        self.launch_mcu02_launched = False
                        self.launch_mcu02.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_tf.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_tf_launched == False:
                        self.launch_tf = roslaunch.scriptapi.ROSLaunch()
                        self.launch_tf = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/tf.launch"])
                        self.launch_tf_launched = True
                        self.launch_tf.start()
                    else:
                        pass
                else:
                    if self.launch_tf_launched == True:
                        self.launch_tf_launched = False
                        self.launch_tf.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_lidar_front.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_lidar_front_launched == False:
                        self.launch_lidar_front = roslaunch.scriptapi.ROSLaunch()
                        self.launch_lidar_front = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/lidar_front.launch"])
                        self.launch_lidar_front_launched = True
                        self.launch_lidar_front.start()
                    else:
                        pass
                else:
                    if self.launch_lidar_front_launched == True:
                        self.launch_lidar_front_launched = False
                        self.launch_lidar_front.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_lidar_rear.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_lidar_rear_launched == False:
                        self.launch_lidar_rear = roslaunch.scriptapi.ROSLaunch()
                        self.launch_lidar_rear = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/lidar_rear.launch"])
                        self.launch_lidar_rear_launched = True
                        self.launch_lidar_rear.start()
                    else:
                        pass
                else:
                    if self.launch_lidar_rear_launched == True:
                        self.launch_lidar_rear_launched = False
                        self.launch_lidar_rear.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_lidar_merger.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_lidar_merger_launched == False:
                        self.launch_lidar_merger = roslaunch.scriptapi.ROSLaunch()
                        self.launch_lidar_merger = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/lidar_merger.launch"])
                        self.launch_lidar_merger_launched = True
                        self.launch_lidar_merger.start()
                    else:
                        pass
                else:
                    if self.launch_lidar_merger_launched == True:
                        self.launch_lidar_merger_launched = False
                        self.launch_lidar_merger.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_mode_controller.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_mode_controller_launched == False:
                        self.launch_mode_controller = roslaunch.scriptapi.ROSLaunch()
                        self.launch_mode_controller = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_mode_controller.launch"])
                        self.launch_mode_controller_launched = True
                        self.launch_mode_controller.start()
                    else:
                        pass
                else:
                    if self.launch_mode_controller_launched == True:
                        self.launch_mode_controller_launched = False
                        self.launch_mode_controller.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_communication.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_communication_launched == False:
                        self.launch_communication = roslaunch.scriptapi.ROSLaunch()
                        self.launch_communication = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(
                            'matrix_communications') + "/launch/communiacations_without_xbee.launch"])
                        self.launch_communication_launched = True
                        self.launch_communication.start()
                    else:
                        pass
                else:
                    if self.launch_communication_launched == True:
                        self.launch_communication_launched = False
                        self.launch_communication.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_serial_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_serial_operation_launched == False:
                        self.launch_serial_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_serial_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/serial_operation.launch"])
                        self.launch_serial_operation_launched = True
                        self.launch_serial_operation.start()
                    else:
                        pass
                else:
                    if self.launch_serial_operation_launched == True:
                        self.launch_serial_operation_launched = False
                        self.launch_serial_operation.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_swapmap_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_swapmap_operation_launched == False:
                        self.launch_swapmap_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_swapmap_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/swapmap_operation.launch"])
                        self.launch_swapmap_operation_launched = True
                        self.launch_swapmap_operation.start()
                    else:
                        pass
                else:
                    if self.launch_swapmap_operation_launched == True:
                        self.launch_swapmap_operation_launched = False
                        self.launch_swapmap_operation.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_docking_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_docking_operation_launched == False:
                        self.launch_docking_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_docking_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/docking_operation.launch"])
                        self.launch_docking_operation_launched = True
                        self.launch_docking_operation.start()
                    else:
                        pass
                else:
                    if self.launch_docking_operation_launched == True:
                        self.launch_docking_operation_launched = False
                        self.launch_docking_operation.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_plugin_device.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_plugin_device_launched == False:
                        self.launch_plugin_device = roslaunch.scriptapi.ROSLaunch()
                        self.launch_plugin_device = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/plugin_device.launch"])
                        self.launch_plugin_device_launched = True
                        self.launch_plugin_device.start()
                    else:
                        pass
                else:
                    if self.launch_plugin_device_launched == True:
                        self.launch_plugin_device_launched = False
                        self.launch_plugin_device.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_ar3mark_operation_rear.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_ar3mark_operation_rear_launched == False:
                        self.launch_ar3mark_operation_rear = roslaunch.scriptapi.ROSLaunch()
                        self.launch_ar3mark_operation_rear = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/ar3mark_operation_rear.launch"])
                        self.launch_ar3mark_operation_rear_launched = True
                        self.launch_ar3mark_operation_rear.start()
                    else:
                        pass
                else:
                    if self.launch_ar3mark_operation_rear_launched == True:
                        self.launch_ar3mark_operation_rear_launched = False
                        self.launch_ar3mark_operation_rear.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_ar3mark_operation_front.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_ar3mark_operation_front_launched == False:
                        self.launch_ar3mark_operation_front = roslaunch.scriptapi.ROSLaunch()
                        self.launch_ar3mark_operation_front = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/ar3mark_operation_rear.launch"])
                        self.launch_ar3mark_operation_front_launched = True
                        self.launch_ar3mark_operation_front.start()
                    else:
                        pass
                else:
                    if self.launch_ar3mark_operation_front_launched == True:
                        self.launch_ar3mark_operation_front_launched = False
                        self.launch_ar3mark_operation_front.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_bumper.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_bumper_launched == False:
                        self.launch_bumper = roslaunch.scriptapi.ROSLaunch()
                        self.launch_bumper = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/bumper.launch"])
                        self.launch_bumper_launched = True
                        self.launch_bumper.start()
                    else:
                        pass
                else:
                    if self.launch_bumper_launched == True:
                        self.launch_bumper_launched = False
                        self.launch_bumper.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_docking_ar_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_docking_ar_operation_launched == False:
                        self.launch_docking_ar_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_docking_ar_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/docking_ar_operation.launch"])
                        self.launch_docking_ar_operation_launched = True
                        self.launch_docking_ar_operation.start()
                    else:
                        pass
                else:
                    if self.launch_docking_ar_operation_launched == True:
                        self.launch_docking_ar_operation_launched = False
                        self.launch_docking_ar_operation.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_wall_follower_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_wall_follower_operation_launched == False:
                        self.launch_wall_follower_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_wall_follower_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/wall_follower_operation.launch"])
                        self.launch_wall_follower_operation_launched = True
                        self.launch_wall_follower_operation.start()
                    else:
                        pass
                else:
                    if self.launch_wall_follower_operation_launched == True:
                        self.launch_wall_follower_operation_launched = False
                        self.launch_wall_follower_operation.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_offline_control_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_offline_control_operation_launched == False:
                        self.launch_offline_control_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_offline_control_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/offline_control_operation.launch"])
                        self.launch_offline_control_operation_launched = True
                        self.launch_offline_control_operation.start()
                    else:
                        pass
                else:
                    if self.launch_offline_control_operation_launched == True:
                        self.launch_offline_control_operation_launched = False
                        self.launch_offline_control_operation.shutdown()
                    else:
                        pass
            else:
                pass
        # launch_cvshape_operation
        elif launch_num == self.Launcher.launch_cvshape_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_cvshape_operation_launched == False:
                        self.launch_cvshape_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_cvshape_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/cvshape_operation.launch"])
                        self.launch_cvshape_operation_launched = True
                        self.launch_cvshape_operation.start()
                    else:
                        pass
                else:
                    if self.launch_cvshape_operation_launched == True:
                        self.launch_cvshape_operation_launched = False
                        self.launch_cvshape_operation.shutdown()
                    else:
                        pass
            else:
                pass

        # launch_io_operation
        elif launch_num == self.Launcher.launch_io_operation.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_io_operation_launched == False:
                        self.launch_io_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_io_operation = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/launch_io_operation"])
                        self.launch_io_operation_launched = True
                        self.launch_io_operation.start()
                    else:
                        pass
                else:
                    if self.launch_io_operation_launched == True:
                        self.launch_io_operation_launched = False
                        self.launch_io_operation.shutdown()
                    else:
                        pass
            else:
                pass

        # launch_sim
        elif launch_num == self.Launcher.launch_sim.value:
            if (skip == False):
                if is_start == True:
                    if self.launch_sim_launched == False:
                        self.launch_sim = roslaunch.scriptapi.ROSLaunch()
                        self.launch_sim = roslaunch.parent.ROSLaunchParent(
                            self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/sim.launch"])
                        self.launch_sim_launched = True
                        self.launch_sim.start()
                    else:
                        pass
                else:
                    if self.launch_sim_launched == True:
                        self.launch_sim_launched = False
                        self.launch_sim.shutdown()
                    else:
                        pass
            else:
                pass

    def main(self):
        rospy.spin()


if __name__ == '__main__':
    rospy.init_node('core_node_controller', anonymous=True)
    node = CoreNodeController()
    node.main()
