#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy, roslaunch
import numpy as np
import rospkg
import subprocess
import os
import sys
import time
from enum import Enum
from std_msgs.msg import UInt8, Bool, Int8

import actionlib
from actionlib_msgs.msg import *


# from ir_auto_docking.msg import AutodockOperateAction, AutodockOperateGoal
from web_interface_msgs.msg import DockingAction
from web_interface_msgs.msg import RouteFollowAction
# from mission_msgs.msg import MissionOperateAction
# from mission_msgs.msg import MissionRunAction
from move_base_msgs.msg import MoveBaseAction
from matrix_msgs.msg import ARDockingOperationAction, ARTrackOperationAction, ROHMChargerOperationAction, SerialOperationAction, SwapEnviOperationAction, XbeeCommunicationAction, RobotMode
from matrix_schedule_operation.msg import ScheduleAction
from matrix_msgs.srv import *
from autodock_core.msg import AutoDockingAction

# from matrix_io_action.msg import ScanMotionAction
# from matrix_io_action.msg import UVCAction
from std_srvs.srv import SetBool, SetBoolResponse
from media_player.srv import *



class CoreNodeController():
    def __init__(self):

        self.serial_no = os.environ["serial_no"]
        self.model = os.environ["model"]

        self.model_launch_pkg = "matrix_" + self.model + "_bringup"
        
        #get param for skip launch
        self.skip_bms = rospy.get_param('~skip_bms', False)
        self.skip_camera = rospy.get_param('~skip_camera', False)
        self.skip_core = rospy.get_param('~skip_core', False)
        self.skip_diagnostics = rospy.get_param('~skip_diagnostics', False)
        self.skip_imu = rospy.get_param('~skip_imu', False)
        self.skip_lidar_f = rospy.get_param('~skip_lidar_f', False)
        self.skip_lidar_r = rospy.get_param('~skip_lidar_r', False)
        self.skip_localization = rospy.get_param('~skip_localization', False)
        self.skip_mcu1 = rospy.get_param('~skip_mcu1', False)
        self.skip_mcu2 = rospy.get_param('~skip_mcu2', False)
        self.skip_movement_state = rospy.get_param('~skip_movement_state', False)
        self.skip_sound = rospy.get_param('~skip_sound', False)
        self.skip_tf = rospy.get_param('~skip_tf', False)
        self.skip_docking = rospy.get_param('~skip_docking', False)
        self.skip_dynamic_param = rospy.get_param('~skip_dynamic_param', False)
        self.skip_laser_odom = rospy.get_param('~skip_laser_odom', False)
        self.skip_aragorn_bridge = rospy.get_param('~skip_aragorn_bridge', False)
        self.skip_mode_controller = rospy.get_param('~skip_mode_controller', False)
        self.skip_communication = rospy.get_param('~skip_communication', False)
        self.skip_serial_operation = rospy.get_param('~skip_serial_operation', False)
        self.skip_swapmap_operation = rospy.get_param('~skip_swapmap_operation', False)
        self.skip_lidar_merger = rospy.get_param('~skip_lidar_merger', False)
        self.skip_docking_operation = rospy.get_param('~skip_docking_operation', False)
        self.skip_ar3mark_operation_rear = rospy.get_param('~skip_ar3mark_operation_rear', False)
        self.skip_ar3mark_operation_front = rospy.get_param('~skip_ar3mark_operation_front', False)
        self.skip_bumper = rospy.get_param('~skip_bumper_operation', False)
        self.skip_docking_ar_operation = rospy.get_param('~skip_docking_ar_operation', False)

        self.ros_package_path = os.path.dirname(os.path.realpath(__file__))
        self.ros_package_path = self.ros_package_path.replace('matrix_system/script', '')

        self.rospack = rospkg.RosPack()

        # self.tablet_discon = rospy.Service("/matrix_launchctl/tablet_discon", self.cbTabletDiscon)

        # self.sub_start_up = rospy.Subscriber('/matrix_io/diagnostics', Bool, self.cbStartRobot, queue_size=1)
        self.sub_mode = rospy.Subscriber('/matrix_mode_controller/mode', RobotMode, self.cbModeLaunch, queue_size=1)
        # self.sub_emer = rospy.Subscriber('/matrix_io/emergency', Int8, self.cbEmer, queue_size=1)

        self.cancel_service_server = rospy.Service('matrix_launch_controller/cancel_action', SetBool, self.cbCancelAction)
        self.action_cantroller_server = rospy.Service('matrix_launch_controller/action_controller', ActionController, self.cbActionControllerServer)

        self.Launcher = Enum('Launcher', 'launch_init launch_docking_ar_operation launch_bumper launch_ar3mark_operation_front launch_ar3mark_operation_rear launch_docking_operation launch_lidar_merger launch_aragorn_bridge launch_laser_odom launch_dynamics_param launch_movement_state launch_autodock launch_vel_filter launch_sound launch_core launch_imu launch_bms launch_camera launch_camera1 launch_camera2 launch_mcu1 launch_mcu2 launch_tf launch_lidar_f launch_lidar_r launch_lidar2  launch_diagnostics launch_localization launch_mode_controller launch_communication launch_serial_operation launch_swapmap_operation')

        self.CurrentMode = Enum('CurrentMode', 'idle start_motor shutdown_motor shutdown_robot emergency fucn_1 down_stairs tablet_loss_commu uvc_on uvc_off ready_to_start docking_mode_on docking_mode_off error_device charger_on charger_off reset emergency_case_active emergency_charge robot_operation_begin robot_operation_finish')

        self.uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)

        self.Launcher_state = Enum('Launcher_state', 'start stop skip')

        
        self.move_base = actionlib.SimpleActionClient("move_base", MoveBaseAction)
        self.serial_operation = actionlib.SimpleActionClient("matrix_serial_operation", SerialOperationAction)
        self.movement_operation = actionlib.SimpleActionClient("matrix_xbeemovement_server", XbeeCommunicationAction)
        self.artrack_operation = actionlib.SimpleActionClient("matrix_artrack_operation", ARTrackOperationAction)
        self.swapenvi_operation = actionlib.SimpleActionClient("matrix_swapenvi_operation", SwapEnviOperationAction)
        self.docking_operation = actionlib.SimpleActionClient("matrix_docking_operation", ROHMChargerOperationAction)
        self.schedule_operation = actionlib.SimpleActionClient("matrix_schedule_operation", ScheduleAction)
        self.ar3mark_operation  = actionlib.SimpleActionClient("autodock_action", AutoDockingAction)
        self.ardocking_operation = actionlib.SimpleActionClient("matrix_docking_ar_operation", ARDockingOperationAction)
        # self.matrix_movement = actionlib.SimpleActionClient("move_base", MoveBaseAction)
        
        # self.MoveBase = actionlib.SimpleActionClient("move_base", MoveBaseAction)
        # self.IR_Manual_Docking = actionlib.SimpleActionClient("manualdocking_server", AutodockOperateAction)
        # self.IR_Docking = actionlib.SimpleActionClient("autodocking_server", AutodockOperateAction)
        self.IST_Docking = actionlib.SimpleActionClient("ist_docking", DockingAction)
        self.IST_RouteFollow = actionlib.SimpleActionClient("ist_route_follow", RouteFollowAction)
        # self.IST_Mission_server = actionlib.SimpleActionClient("missions_server", MissionRunAction)
        # self.IST_Mission_operate = actionlib.SimpleActionClient("missions_operate", MissionOperateAction)
        # self.ScanMotion = actionlib.SimpleActionClient("scan_motion_server", ScanMotionAction)
        # self.UVC = actionlib.SimpleActionClient("uvc_server", UVCAction)
        

        self.launch_core_launched = False
        self.launch_vel_filter_launched = False
        self.launch_sound_launched = False
        self.launch_mcu1_launched = False
        self.launch_mcu2_launched = False
        self.launch_mcu1_action_launched = False
        self.launch_bms_launched = False
        self.launch_imu_launched = False
        self.launch_camera_launched = False
        self.launch_rear_camera_launched = False
        self.launch_tf_launched = False
        # self.launch_core_launched = False
        self.launch_lidar_f_launched = False
        self.launch_lidar_r_launched = False
        self.launch_diagnostics_launched = False
        self.launch_led_launched = False
        self.launch_web_launched = False
        self.launch_localization_launched = False
        self.launch_lidar_f_unique_launched = False
        self.launch_autodock_launched = False
        self.launch_movement_state_launched = False
        self.launch_dynamics_param_launched = False
        self.launch_manual_docking_launched = False
        self.launch_laser_odom_launched = False
        self.launch_aragorn_bridge_launched = False
        self.launch_mode_controller_launched = False
        self.launch_communication_launched = False
        self.launch_serial_operation_launched = False
        self.launch_swapmap_operation_launched = False
        self.launch_lidar_merger_launched = False
        self.launch_docking_operation_launched = False
        self.launch_ar3mark_operation_rear_launched = False
        self.launch_ar3mark_operation_front_launched = False
        self.launch_bumper_launched = False
        self.launch_docking_ar_operation_launched = False
        

        self.is_triggered = False

        self.current_mode = self.CurrentMode.idle.value

        
        # self.model_type = self.serial_no[8]

        self.remote_launch = ""

        # print "down can0"
        # os.system('echo \"a\" | sudo -S ip link set can0 down')
        # time.sleep(1)
        # print "bringup can0"
        # os.system('echo \"a\" | sudo -S ip link set can0 up type can bitrate 250000')
        # print "can0 bringup success!!!"


        self.initial_robot()

        loop_rate = rospy.Rate(10) # 10hz
        while not rospy.is_shutdown():
            if self.is_triggered == True:
                self.fnControlNode()
            
            loop_rate.sleep()
    
    # def emergency_case(self):
    #     self.MoveBase.cancel_all_goals()
    #     self.IR_Docking.cancel_all_goals()
    #     self.IST_Docking.cancel_all_goals()
    #     self.IST_RouteFollow.cancel_all_goals()
    #     self.IST_Mission_server.cancel_all_goals()
    #     self.IST_Mission_operate.cancel_all_goals()
    #     self.ScanMotion.cancel_all_goals()
    #     self.UVC.cancel_all_goals()

    # def cbTabletDiscon(self, req):
    #     if req.data:
    #         self.fnLaunch(self.Launcher.launch_core.value, False)

    #         self.move_base.cancel_all_goals()
    #         self.IR_Docking.cancel_all_goals()
    #         self.IST_Docking.cancel_all_goals()
    #         self.IST_RouteFollow.cancel_all_goals()
    #         self.IST_Mission_server.cancel_all_goals()
    #         self.IST_Mission_operate.cancel_all_goals()
    #         self.ScanMotion.cancel_all_goals()
    #         self.UVC.cancel_all_goals()

    #         self.fnLaunch(self.Launcher.launch_mcu1_action.value, False)
    #     else:
    #         pass
        
    #     return True, "[matrix_launchctl]:Tablet discon mode trigger!!!"

    def cbCancelAction(self, req):
        if req.data:
            try:
                media_playerSRV = rospy.ServiceProxy('media_player_server', MediaPlayer)
                srv_req = MediaPlayerRequest()

                srv_req.cmd = "clear"

                srv_res = media_playerSRV(srv_req) 
            except:
                pass
            # os.system('echo \"a\" | sudo -S service ONodeREDUser stop')
            self.move_base.cancel_all_goals()
            self.serial_operation.cancel_all_goals()
            self.movement_operation.cancel_all_goals()
            self.artrack_operation.cancel_all_goals()
            self.swapenvi_operation.cancel_all_goals()
            self.docking_operation.cancel_all_goals()
            self.schedule_operation.cancel_all_goals()
            self.ar3mark_operation.cancel_all_goals()
            self.ardocking_operation.cancel_all_goals()

            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()
            # os.system('echo \"a\" | sudo -S service ONodeREDUser start')
            # os.system('echo \"a\" | sudo -S service ONodeREDUser restart')
        
        return True, "Success"
    
    def cbActionControllerServer(self, req):
        rospy.loginfo("[Launch control]: Request cmd %s, action_name %s ", req.cmd, req.action_name)
        success = False
        if req.cmd == ActionControllerRequest.CMD_ACTION_START or req.cmd == ActionControllerRequest.CMD_ACTION_KILL:
            # get lauch state
            action_launch_state = False
            if req.cmd == ActionControllerRequest.CMD_ACTION_START:
                action_launch_state = True
            else:
                pass
            
            # get Action launch file
            action_name = self.Launcher.launch_init.value
            if req.action_name == ActionControllerRequest.AC_AR3_REAR:
                action_name = self.Launcher.launch_ar3mark_operation_rear.value
            elif req.action_name == ActionControllerRequest.AC_AR3_FRONT:
                action_name = self.Launcher.launch_ar3mark_operation_front.value
            else:
                rospy.logerr("[Launch control]: Not found action name %s, please in matix_msgs/ActionController.srv ", req.action_name)
            
            # launch control
            if action_name != self.Launcher.launch_init.value:
                try:
                    self.fnLaunch(action_name, False, action_launch_state)
                    success = True
                except:
                    rospy.logerr("[Launch control]: call launch error %s", req.action_name)
                    success = False
            else:
                success = False
                
        elif req.cmd == ActionControllerRequest.CMD_ACTION_CANCEL:
            if req.action_name == ActionControllerRequest.AC_MOVEMENT:
                try:
                    self.move_base.cancel_all_goals()
                    self.movement_operation.cancel_all_goals()
                    self.docking_operation.cancel_all_goals()
                    self.ar3mark_operation.cancel_all_goals()
                    self.ardocking_operation.cancel_all_goals()
                    self.IST_Docking.cancel_all_goals()
                    self.IST_RouteFollow.cancel_all_goals()
                except:
                    rospy.logerr("[Launch control]: error while cancelling action %s", req.action_name)
            else:
                rospy.logerr("[Launch control]: Not found action name %s, please in matix_msgs/ActionController.srv ", req.action_name)
                success = False
        
        else:
            rospy.logerr("[Launch control]: Not found cmd %s, please in matix_msgs/ActionController.srv ", req.cmd)
            success = False
        
        return success

    
    # def funcCancelAction(self):
    #     self.move_base.cancel_all_goals()
    #     self.serial_operation.cancel_all_goals()
    #     self.movement_operation.cancel_all_goals()
    #     self.artrack_operation.cancel_all_goals()
    #     self.swapenvi_operation.cancel_all_goals()
    #     self.docking_operation.cancel_all_goals()
    #     self.schedule_operation.cancel_all_goals()
    #     self.ar3mark_operation.cancel_all_goals()
    #     os.system('echo \"a\" | sudo -S service ONodeREDUser restart')



    def cbModeLaunch(self, mode_msg):
        # rospy.loginfo("Start core_controller with mode %d", mode_msg)
        if(self.current_mode == mode_msg.robot_mode):
            pass
        else:
            self.current_mode = mode_msg.robot_mode
            self.is_triggered = True
    
    def initial_robot(self):
        # pass
        self.fnLaunch(self.Launcher.launch_tf.value, self.skip_tf, True)
        self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, True)
        self.fnLaunch(self.Launcher.launch_lidar_f.value, self.skip_lidar_f, True)
        self.fnLaunch(self.Launcher.launch_lidar_r.value, self.skip_lidar_r, True)
        self.fnLaunch(self.Launcher.launch_lidar_merger.value, self.skip_lidar_merger, True)
        self.fnLaunch(self.Launcher.launch_sound.value, self.skip_sound, True)
        self.fnLaunch(self.Launcher.launch_mcu1.value, self.skip_mcu1, True)
        # self.fnLaunch(self.Launcher.launch_mcu2.value, self.skip_mcu2, True)
        self.fnLaunch(self.Launcher.launch_camera.value, self.skip_camera, True)
        self.fnLaunch(self.Launcher.launch_bms.value, self.skip_bms, True)
        self.fnLaunch(self.Launcher.launch_imu.value, self.skip_imu, True)
        # self.fnLaunch(self.Launcher.launch_laser_odom.value, self.skip_laser_odom, True)
        self.fnLaunch(self.Launcher.launch_localization.value, self.skip_localization, True)
        self.fnLaunch(self.Launcher.launch_movement_state.value, self.skip_movement_state, True)
        self.fnLaunch(self.Launcher.launch_dynamics_param.value, self.skip_dynamic_param, True)
        # self.fnLaunch(self.Launcher.launch_diagnostics.value, self.skip_diagnostics, True)
        self.fnLaunch(self.Launcher.launch_aragorn_bridge.value, self.skip_aragorn_bridge, True)
        self.fnLaunch(self.Launcher.launch_mode_controller.value, self.skip_mode_controller, True)
        self.fnLaunch(self.Launcher.launch_communication.value, self.skip_communication, True)
        self.fnLaunch(self.Launcher.launch_serial_operation.value, self.skip_serial_operation, True)
        self.fnLaunch(self.Launcher.launch_swapmap_operation.value, self.skip_swapmap_operation, True)
        self.fnLaunch(self.Launcher.launch_docking_operation.value, self.skip_docking_operation, True)

        # on when use
        self.fnLaunch(self.Launcher.launch_ar3mark_operation_rear.value, self.skip_ar3mark_operation_rear, False)
        self.fnLaunch(self.Launcher.launch_ar3mark_operation_front.value, self.skip_ar3mark_operation_front, False)

        self.fnLaunch(self.Launcher.launch_bumper.value, self.skip_bumper, True)
        self.fnLaunch(self.Launcher.launch_docking_ar_operation.value, self.skip_docking_ar_operation, True)

        self.fnLaunch(self.Launcher.launch_diagnostics.value, self.skip_diagnostics, True)

        try:
            os.system('echo \"a\" | sudo -S service ONodeREDUser start')
        except:
            pass

    
    def fnControlNode(self):
        # Start_robot mode
        if self.current_mode == RobotMode.START_MOTOR:
            rospy.loginfo("[Launch control]: Now trigger for Start motor drive")
            # os.system('echo \"a\" | sudo -S service ONodeREDUser start')
            # self.fnLaunch(self.Launcher.launch_laser_odom.value, self.skip_laser_odom, False)
            # self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, True)
            

        elif self.current_mode == RobotMode.READY_TO_START:
            pass
            # os.system('echo \"a\" | sudo -S service ONodeREDUser start')
            # self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, False)
            # self.fnLaunch(self.Launcher.launch_laser_odom.value, self.skip_laser_odom, True)

        elif self.current_mode == self.CurrentMode.fucn_1.value:
            rospy.loginfo("[Launch control]: Now trigger for fucn_1 mauldocking")
            # goal = AutodockOperateGoal()
            # goal.order = 1
            # self.IR_Manual_Docking.send_goal(goal)

            
        elif self.current_mode == self.CurrentMode.reset.value:
            rospy.loginfo("[Launch control]: Now trigger for reset io state and off motor control")
            # self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, False)
            
            # self.IR_Manual_Docking.cancel_all_goals()
            # self.move_base.cancel_all_goals()
            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()

            # self.fnLaunch(self.Launcher.launch_mcu1_action.value, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
            # self.fnLaunch(self.Launcher.launch_manual_docking.value, False)

            # self.fnLaunch(self.Launcher.launch_core.value, False)
            # self.fnLaunch(self.Launcher.launch_mcu1_action.value, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
        
        elif self.current_mode == RobotMode.EMERGENCY:
            rospy.loginfo("[Launch control]: Now trigger for Stop motor drive")
            # self.fnLaunch(self.Launcher.launch_localization.value, False)
            # rospy.sleep(5)
            # os.system('echo \"a\" | sudo -S ip link set can0 down')
            # self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, False)
            # self.fnLaunch(self.Launcher.launch_laser_odom.value, self.skip_laser_odom, False)
            # try:
            #     os.system('echo \"a\" | sudo -S service ONodeREDUser stop')
            #     media_playerSRV = rospy.ServiceProxy('media_player_server', MediaPlayer)
            #     srv_req = MediaPlayerRequest()

            #     srv_req.cmd = "clear"

            #     srv_res = media_playerSRV(srv_req) 
            # except:
            #     pass
            # self.IR_Manual_Docking.cancel_all_goals()

            self.move_base.cancel_all_goals()
            self.serial_operation.cancel_all_goals()
            self.movement_operation.cancel_all_goals()
            self.artrack_operation.cancel_all_goals()
            self.swapenvi_operation.cancel_all_goals()
            self.docking_operation.cancel_all_goals()
            self.schedule_operation.cancel_all_goals()
            self.ar3mark_operation.cancel_all_goals()
            self.ardocking_operation.cancel_all_goals()

            self.IST_Docking.cancel_all_goals()
            self.IST_RouteFollow.cancel_all_goals()
            
            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()

            # self.fnLaunch(self.Launcher.launch_mcu1_action.value, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
            # self.fnLaunch(self.Launcher.launch_manual_docking.value, False)
            # a = subprocess.run(["rosservice", "call", "/matrix_io/led_status"])
	
	    # elif self.current_mode == self.CurrentMode.fucn_1.value:
        #     rospy.loginfo("[Launch control]: Now trigger for Relocalization")
        #     self.fnLaunch(self.Launcher.launch_localization.value, False)
        #     rospy.sleep(5)
        #     self.fnLaunch(self.Launcher.launch_localization.value, True)
        
        elif self.current_mode == self.CurrentMode.down_stairs.value:
            rospy.loginfo("[Launch control]: Now trigger for Down stairs")
            self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, False)
        
        elif self.current_mode == self.CurrentMode.tablet_loss_commu.value:
            rospy.loginfo("[Launch control]: Now trigger for Tablet loss comunicate")
            # self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, False)
            # self.move_base.cancel_all_goals()
            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()
            # self.fnLaunch(self.Launcher.launch_mcu1_action.value, False)

        elif self.current_mode == self.CurrentMode.emergency_charge.value:
            rospy.loginfo("[Launch control]: Now trigger for emergency charge")
            # self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, False)
           
            # self.move_base.cancel_all_goals()
            # self.IR_Docking.cancel_all_goals()
            # self.IST_Docking.cancel_all_goals()
            # self.IST_RouteFollow.cancel_all_goals()
            # self.IST_Mission_server.cancel_all_goals()
            # self.IST_Mission_operate.cancel_all_goals()
            # self.ScanMotion.cancel_all_goals()
            # self.UVC.cancel_all_goals()
            # self.fnLaunch(self.Launcher.launch_mcu1_action.value, False)

        
        # Off_robot mode
        elif self.current_mode == self.CurrentMode.shutdown_robot.value:
            rospy.loginfo("Now trigger for shutdown Robot")

            self.fnLaunch(self.Launcher.launch_tf.value, self.skip_tf, False)
            self.fnLaunch(self.Launcher.launch_lidar_f.value, self.skip_lidar_f, False)
            self.fnLaunch(self.Launcher.launch_lidar_r.value, self.skip_lidar_r, False)
            self.fnLaunch(self.Launcher.launch_sound.value, self.skip_sound, False)
            self.fnLaunch(self.Launcher.launch_mcu1.value, self.skip_mcu1, False)
            self.fnLaunch(self.Launcher.launch_mcu2.value, self.skip_mcu2, False)
            self.fnLaunch(self.Launcher.launch_camera.value, self.skip_camera, False)
            self.fnLaunch(self.Launcher.launch_bms.value, self.skip_bms, False)
            self.fnLaunch(self.Launcher.launch_imu.value, self.skip_imu, False)
            self.fnLaunch(self.Launcher.launch_localization.value, self.skip_localization, False)
            # self.fnLaunch(self.Launcher.launch_autodock.value, False)
            # self.fnLaunch(self.Launcher.launch_manual_docking.value, False)
            self.fnLaunch(self.Launcher.launch_movement_state.value, self.skip_movement_state, False)
            # self.fnLaunch(self.Launcher.launch_dynamics_param.value, False)
            self.fnLaunch(self.Launcher.launch_diagnostics.value, self.skip_diagnostics, False)
            # self.fnLaunch(self.Launcher.launch_vel_filter.value, False)
            self.fnLaunch(self.Launcher.launch_core.value, self.skip_core, False)
            os.system("rosnode kill --all")
            os.system('echo \"a\" | sudo -S shutdown now')
        
        self.is_triggered = False

    def fnLaunch(self, launch_num, skip, is_start):
        # if launch_num == self.Launcher.launch_manual_docking.value:
        #     if is_start == True:
        #         if self.launch_manual_docking_launched == False:
        #             self.launch_manual_docking = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_manual_docking = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_manualdock.launch"])
        #             self.launch_manual_docking_launched = True
        #             self.launch_manual_docking.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_manual_docking_launched == True:
        #             self.launch_manual_docking_launched = False
        #             self.launch_manual_docking.shutdown()
        #         else:
        #             pass
        
        if launch_num == self.Launcher.launch_aragorn_bridge.value:
            if is_start == True:
                if self.launch_aragorn_bridge_launched == False:
                    self.launch_aragorn_bridge = roslaunch.scriptapi.ROSLaunch()
                    self.launch_aragorn_bridge = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_aragorn_bridge.launch"])
                    self.launch_aragorn_bridge_launched = True
                    self.launch_aragorn_bridge.start()
                else:
                    pass
            else:
                if self.launch_aragorn_bridge_launched == True:
                    self.launch_aragorn_bridge_launched = False
                    self.launch_aragorn_bridge.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_dynamics_param.value:
            if is_start == True:
                if self.launch_dynamics_param_launched == False:
                    self.launch_dynamics_param = roslaunch.scriptapi.ROSLaunch()
                    self.launch_dynamics_param = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_dynamic_parameter') + "/launch/dynamic_parameters.launch"])
                    self.launch_dynamics_param_launched = True
                    self.launch_dynamics_param.start()
                else:
                    pass
            else:
                if self.launch_dynamics_param_launched == True:
                    self.launch_dynamics_param_launched = False
                    self.launch_dynamics_param.shutdown()
                else:
                    pass
        
        if launch_num == self.Launcher.launch_laser_odom.value:
            if is_start == True:
                if self.launch_laser_odom_launched == False:
                    self.launch_laser_odom = roslaunch.scriptapi.ROSLaunch()
                    self.launch_laser_odom = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_laser_odom.launch"])
                    self.launch_laser_odom_launched = True
                    self.launch_laser_odom.start()
                else:
                    pass
            else:
                if self.launch_laser_odom_launched == True:
                    self.launch_laser_odom_launched = False
                    self.launch_laser_odom.shutdown()
                else:
                    pass

        if launch_num == self.Launcher.launch_movement_state.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_movement_state_launched == False:
                        self.launch_movement_state = roslaunch.scriptapi.ROSLaunch()
                        self.launch_movement_state = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_movement_state.launch"])
                        self.launch_movement_state_launched = True
                        self.launch_movement_state.start()
                    else:
                        pass
                else:
                    if self.launch_movement_state_launched == True:
                        self.launch_movement_state_launched = False
                        self.launch_movement_state.shutdown()
                    else:
                        pass
            else:
                pass

        # if launch_num == self.Launcher.launch_autodock.value:
        #     if is_start == True:
        #         if self.launch_autodock_launched == False:
        #             self.launch_autodock = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_autodock = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_autodock.launch"])
        #             self.launch_autodock_launched = True
        #             self.launch_autodock.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_autodock_launched == True:
        #             self.launch_autodock_launched = False
        #             self.launch_autodock.shutdown()
        #         else:
        #             pass

        # if launch_num == self.Launcher.launch_lidar_f_unique.value:
        #     if is_start == True:
        #         if self.launch_lidar_f_unique_launched == False:
        #             self.launch_lidar_f_unique = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_lidar_f_unique = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_lidar_filter_unique.launch"])
        #             self.launch_lidar_f_unique_launched = True
        #             self.launch_lidar_f_unique.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_lidar_f_unique_launched == True:
        #             self.launch_lidar_f_unique_launched = False
        #             self.launch_lidar_f_unique.shutdown()
        #         else:
        #             pass

        if launch_num == self.Launcher.launch_core.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_core_launched == False:
                        self.launch_core = roslaunch.scriptapi.ROSLaunch()
                        self.launch_core = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/base.launch"])
                        self.launch_core_launched = True
                        self.launch_core.start()
                    else:
                        pass
                else:
                    if self.launch_core_launched == True:
                        self.launch_core_launched = False
                        self.launch_core.shutdown()
                    else:
                        pass
            else:
                pass
        
        if launch_num == self.Launcher.launch_sound.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_sound_launched == False:
                        self.launch_sound = roslaunch.scriptapi.ROSLaunch()
                        self.launch_sound = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_sound.launch"])
                        self.launch_sound_launched = True
                        self.launch_sound.start()
                    else:
                        pass
                else:
                    if self.launch_sound_launched == True:
                        self.launch_sound_launched = False
                        self.launch_sound.shutdown()
                    else:
                        pass
            else:
                pass

                    
        # if launch_num == self.Launcher.launch_vel_filter.value:
        #     if is_start == True:
        #         if self.launch_vel_filter_launched == False:
        #             self.launch_vel_filter = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_vel_filter = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('laser_vel_filter') + "/launch/laser_vel_filter.launch"])
        #             self.launch_vel_filter_launched = True
        #             self.launch_vel_filter.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_vel_filter_launched == True:
        #             self.launch_vel_filter_launched = False
        #             self.launch_vel_filter.shutdown()
        #         else:
        #             pass

        if launch_num == self.Launcher.launch_imu.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_imu_launched == False:
                        self.launch_imu = roslaunch.scriptapi.ROSLaunch()
                        self.launch_imu = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/imu.launch"])
                        self.launch_imu_launched = True
                        self.launch_imu.start()
                    else:
                        pass
                else:
                    if self.launch_imu_launched == True:
                        self.launch_imu_launched = False
                        self.launch_imu.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_bms.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_bms_launched == False:
                        self.launch_bms = roslaunch.scriptapi.ROSLaunch()
                        self.launch_bms = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/pzem_bms.launch"])
                        self.launch_bms_launched = True
                        self.launch_bms.start()
                    else:
                        pass
                else:
                    if self.launch_bms_launched == True:
                        self.launch_bms_launched = False
                        self.launch_bms.shutdown()
                    else:
                        pass
            else:
                pass


        if launch_num == self.Launcher.launch_camera.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_camera_launched == False:
                        self.launch_camera = roslaunch.scriptapi.ROSLaunch()
                        self.launch_camera = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/camera.launch"])
                        self.launch_camera_launched = True
                        self.launch_camera.start()
                    else:
                        pass
                else:
                    if self.launch_camera_launched == True:
                        self.launch_camera_launched = False
                        self.launch_camera.shutdown()
                    else:
                        pass
            else:
                pass

        if launch_num == self.Launcher.launch_localization.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_localization_launched == False:
                        self.launch_localization = roslaunch.scriptapi.ROSLaunch()
                        self.launch_localization = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/localization.launch"])
                        self.launch_localization_launched = True
                        self.launch_localization.start()
                    else:
                        pass
                else:
                    if self.launch_localization_launched == True:
                        self.launch_localization_launched = False
                        self.launch_localization.shutdown()
                    else:
                        pass
            else:
                pass

        # if launch_num == self.Launcher.launch_web.value:
        #     if is_start == True:
        #         if self.launch_web_launched == False:
        #             self.launch_web = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_web = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('web_interface') + "/launch/my.launch"])
        #             self.launch_web_launched = True
        #             self.launch_web.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_web_launched == True:
        #             self.launch_web_launched = False
        #             self.launch_web.shutdown()
        #         else:
        #             pass

        if launch_num == self.Launcher.launch_diagnostics.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_diagnostics_launched == False:
                        self.launch_diagnostics = roslaunch.scriptapi.ROSLaunch()
                        self.launch_diagnostics = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system')  + "/launch/matrix_diagnostics.launch"])
                        self.launch_diagnostics_launched = True
                        self.launch_diagnostics.start()
                    else:
                        pass
                else:
                    if self.launch_diagnostics_launched == True:
                        self.launch_diagnostics_launched = False
                        self.launch_diagnostics.shutdown()
                    else:
                        pass
            else:
                pass

        # if launch_num == self.Launcher.launch_led.value:
        #     if is_start == True:
        #         if self.launch_led_launched == False:
        #             self.launch_led = roslaunch.scriptapi.ROSLaunch()
        #             self.launch_led = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_control') + "/launch/matrix_led_status.launch"])
        #             self.launch_led_launched = True
        #             self.launch_led.start()
        #         else:
        #             pass
        #     else:
        #         if self.launch_led_launched == True:
        #             self.launch_led_launched = False
        #             self.launch_led.shutdown()
        #         else:
        #             pass

        if launch_num == self.Launcher.launch_mcu1.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_mcu1_launched == False:
                        self.launch_mcu1 = roslaunch.scriptapi.ROSLaunch()
                        self.launch_mcu1 = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/io.launch"])
                        self.launch_mcu1_launched = True
                        self.launch_mcu1.start()
                    else:
                        pass
                else:
                    if self.launch_mcu1_launched == True:
                        self.launch_mcu1_launched = False
                        self.launch_mcu1.shutdown()
                    else:
                        pass
            else:
                pass
        
        if launch_num == self.Launcher.launch_mcu2.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_mcu2_launched == False:
                        self.launch_mcu2= roslaunch.scriptapi.ROSLaunch()
                        self.launch_mcu2= roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_mcu2.launch"])
                        self.launch_mcu2_launched = True
                        self.launch_mcu2.start()
                    else:
                        pass
                else:
                    if self.launch_mcu2_launched == True:
                        self.launch_mcu2_launched = False
                        self.launch_mcu2.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_tf.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_tf_launched == False:
                        self.launch_tf = roslaunch.scriptapi.ROSLaunch()
                        self.launch_tf = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/tf.launch"])
                        self.launch_tf_launched = True
                        self.launch_tf.start()
                    else:
                        pass
                else:
                    if self.launch_tf_launched == True:
                        self.launch_tf_launched = False
                        self.launch_tf.shutdown()
                    else:
                        pass
            else:
                pass

        elif launch_num == self.Launcher.launch_lidar_f.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_lidar_f_launched == False:
                        self.launch_lidar_f = roslaunch.scriptapi.ROSLaunch()
                        self.launch_lidar_f = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/lidar_front.launch"])
                        self.launch_lidar_f_launched = True
                        self.launch_lidar_f.start()
                    else:
                        pass
                else:
                    if self.launch_lidar_f_launched == True:
                        self.launch_lidar_f_launched = False
                        self.launch_lidar_f.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_lidar_r.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_lidar_r_launched == False:
                        self.launch_lidar_r = roslaunch.scriptapi.ROSLaunch()
                        self.launch_lidar_r = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/lidar_rear.launch"])
                        self.launch_lidar_r_launched = True
                        self.launch_lidar_r.start()
                    else:
                        pass
                else:
                    if self.launch_lidar_r_launched == True:
                        self.launch_lidar_r_launched = False
                        self.launch_lidar_r.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_lidar_merger.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_lidar_merger_launched == False:
                        self.launch_lidar_merger = roslaunch.scriptapi.ROSLaunch()
                        self.launch_lidar_merger = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/lidar_merger.launch"])
                        self.launch_lidar_merger_launched = True
                        self.launch_lidar_merger.start()
                    else:
                        pass
                else:
                    if self.launch_lidar_merger_launched == True:
                        self.launch_lidar_merger_launched = False
                        self.launch_lidar_merger.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_mode_controller.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_mode_controller_launched == False:
                        self.launch_mode_controller = roslaunch.scriptapi.ROSLaunch()
                        self.launch_mode_controller = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_system') + "/launch/matrix_mode_controller.launch"])
                        self.launch_mode_controller_launched = True
                        self.launch_mode_controller.start()
                    else:
                        pass
                else:
                    if self.launch_mode_controller_launched == True:
                        self.launch_mode_controller_launched = False
                        self.launch_mode_controller.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_communication.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_communication_launched == False:
                        self.launch_communication = roslaunch.scriptapi.ROSLaunch()
                        self.launch_communication = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path('matrix_communications') + "/launch/communiacations.launch"])
                        self.launch_communication_launched = True
                        self.launch_communication.start()
                    else:
                        pass
                else:
                    if self.launch_communication_launched == True:
                        self.launch_communication_launched = False
                        self.launch_communication.shutdown()
                    else:
                        pass
            else:
                pass
        

        elif launch_num == self.Launcher.launch_serial_operation.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_serial_operation_launched == False:
                        self.launch_serial_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_serial_operation = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/serial_operation.launch"])
                        self.launch_serial_operation_launched = True
                        self.launch_serial_operation.start()
                    else:
                        pass
                else:
                    if self.launch_serial_operation_launched == True:
                        self.launch_serial_operation_launched = False
                        self.launch_serial_operation.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_swapmap_operation.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_swapmap_operation_launched == False:
                        self.launch_swapmap_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_swapmap_operation = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/swapmap_operation.launch"])
                        self.launch_swapmap_operation_launched = True
                        self.launch_swapmap_operation.start()
                    else:
                        pass
                else:
                    if self.launch_swapmap_operation_launched == True:
                        self.launch_swapmap_operation_launched = False
                        self.launch_swapmap_operation.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_docking_operation.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_docking_operation_launched == False:
                        self.launch_docking_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_docking_operation = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/docking_operation.launch"])
                        self.launch_docking_operation_launched = True
                        self.launch_docking_operation.start()
                    else:
                        pass
                else:
                    if self.launch_docking_operation_launched == True:
                        self.launch_docking_operation_launched = False
                        self.launch_docking_operation.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_ar3mark_operation_rear.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_ar3mark_operation_rear_launched == False:
                        self.launch_ar3mark_operation_rear = roslaunch.scriptapi.ROSLaunch()
                        self.launch_ar3mark_operation_rear = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/ar3mark_operation_rear.launch"])
                        self.launch_ar3mark_operation_rear_launched = True
                        self.launch_ar3mark_operation_rear.start()
                    else:
                        pass
                else:
                    if self.launch_ar3mark_operation_rear_launched == True:
                        self.launch_ar3mark_operation_rear_launched = False
                        self.launch_ar3mark_operation_rear.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_ar3mark_operation_front.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_ar3mark_operation_front_launched == False:
                        self.launch_ar3mark_operation_front = roslaunch.scriptapi.ROSLaunch()
                        self.launch_ar3mark_operation_front = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/ar3mark_operation_rear.launch"])
                        self.launch_ar3mark_operation_front_launched = True
                        self.launch_ar3mark_operation_front.start()
                    else:
                        pass
                else:
                    if self.launch_ar3mark_operation_front_launched == True:
                        self.launch_ar3mark_operation_front_launched = False
                        self.launch_ar3mark_operation_front.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_bumper.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_bumper_launched == False:
                        self.launch_bumper = roslaunch.scriptapi.ROSLaunch()
                        self.launch_bumper = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/bumper.launch"])
                        self.launch_bumper_launched = True
                        self.launch_bumper.start()
                    else:
                        pass
                else:
                    if self.launch_bumper_launched == True:
                        self.launch_bumper_launched = False
                        self.launch_bumper.shutdown()
                    else:
                        pass
            else:
                pass
        
        elif launch_num == self.Launcher.launch_docking_ar_operation.value:
            if(skip == False):
                if is_start == True:
                    if self.launch_docking_ar_operation_launched == False:
                        self.launch_docking_ar_operation = roslaunch.scriptapi.ROSLaunch()
                        self.launch_docking_ar_operation = roslaunch.parent.ROSLaunchParent(self.uuid, [self.rospack.get_path(self.model_launch_pkg) + "/launch/docking_ar_operation.launch"])
                        self.launch_docking_ar_operation_launched = True
                        self.launch_docking_ar_operation.start()
                    else:
                        pass
                else:
                    if self.launch_docking_ar_operation_launched == True:
                        self.launch_docking_ar_operation_launched = False
                        self.launch_docking_ar_operation.shutdown()
                    else:
                        pass
            else:
                pass


    def main(self):
        rospy.spin()
    
if __name__=='__main__':
    rospy.init_node('core_node_controller')
    node = CoreNodeController()
    node.main()