#!/usr/bin/env python

import rospy
import rospkg
import os
from aragorn_msg.srv import MapSaver, MapSaverResponse
from std_msgs.msg import String
import commands
from subprocess import call

rospack = rospkg.RosPack()

def callback_save_map(req):
    ros_cmd = "rosrun map_server map_saver -f "
    pkg = rospack.get_path('aragorn_navigation')
    map_location = "/maps/"
    name_map = req.map_name
    cmd = ros_cmd + pkg +map_location + name_map
    print(" ")
    print(cmd)
    print(" ")
    os.system(cmd)
    print(" ")
    
    return MapSaverResponse("sucess")


def mapsaver_server():
    rospy.init_node('map_saver_server')
    s = rospy.Service('aragorn/map_saver', MapSaver, callback_save_map)
    print("Ready to save map ")
    rospy.spin()

if __name__ == '__main__':
     mapsaver_server()