#!/usr/bin/env python3

import rospy
from std_msgs.msg import Int64, String, Bool
from std_srvs.srv import SetBool
from geometry_msgs.msg import *
from nav_msgs.msg import *
from matrix_msgs.msg import *
from can_msgs.msg import *

from dynamic_reconfigure.server import Server
from matrix_canopen_motor.cfg import MotorConfig

import math
import time 
from enum import Enum
from struct import *


import can
from can import *
import struct 

import os
import sys

import threading
import time
try:
    import _thread
except:
    import thread as _thread

mutex = threading.Lock()

# from dataclasses import dataclass


class NumberCounter:
    def __init__(self):

        # canbus read param
        if not rospy.has_param("~device_name"):
            rospy.set_param("~device_name", "OrientalmotorBLVD_KRD") 
        if not rospy.has_param("~dual_driver_motor"):
            rospy.set_param("~dual_driver_motor", False) 
        if not rospy.has_param("~use_matrix_navgo_bypass"):
            rospy.set_param("~use_matrix_navgo_bypass", False)
        if not rospy.has_param("~can_device"):
            rospy.set_param("~can_device", "can0")
        if not rospy.has_param("~canbus_bitrate"):
            rospy.set_param("~canbus_bitrate", 500000)
        if not rospy.has_param("~dual_motor_id"):
            rospy.set_param("~dual_motor_id", 1)
        if not rospy.has_param("~motor_1_id"):
            rospy.set_param("~motor_1_id", 1)
        if not rospy.has_param("~motor_2_id"):
            rospy.set_param("~motor_2_id", 2)
        if not rospy.has_param("~accel_time"):
            rospy.set_param("~accel_time", 100)
        if not rospy.has_param("~decel_time"):
            rospy.set_param("~decel_time", 100)
        self.device_name = rospy.get_param("~device_name")
        self.dual_driver_motor = rospy.get_param("~dual_driver_motor")
        self.use_matrix_navgo_bypass = rospy.get_param("~use_matrix_navgo_bypass")
        self.can_device = rospy.get_param("~can_device")
        self.can_bitrate = rospy.get_param("~canbus_bitrate")
        self.dual_motor_id = rospy.get_param("~dual_motor_id")
        self.motor_1_id = rospy.get_param("~motor_1_id")
        self.motor_2_id = rospy.get_param("~motor_2_id")
        self.accel_time = rospy.get_param("~accel_time")
        self.decel_time = rospy.get_param("~decel_time")


 

        # odometry calculation param 
        if not rospy.has_param("~wheels_x_distance"):
            rospy.set_param("~wheels_x_distance", 0.0)
        if not rospy.has_param("~wheels_y_distance"):
            rospy.set_param("~wheels_y_distance", 0.481)
        if not rospy.has_param("~wheel_diameter"):
            rospy.set_param("~wheel_diameter", 0.151)
        if not rospy.has_param("~max_motor_rpm"):
            rospy.set_param("~max_motor_rpm", 3000.0)
        if not rospy.has_param("~gear_ratio"):
            rospy.set_param("~gear_ratio", 20.00)
        if not rospy.has_param("~total_wheels"):
            rospy.set_param("~total_wheels", 2.0)
        self.wheels_x_distance_ = rospy.get_param("~wheels_x_distance")
        self.wheels_y_distance_ = rospy.get_param("~wheels_y_distance")
        self.wheel_diameter = rospy.get_param("~wheel_diameter")
        self.max_motor_rpm = rospy.get_param("~max_motor_rpm")
        self.gear_ratio = rospy.get_param("~gear_ratio")
        self.total_wheels_ = rospy.get_param("~total_wheels")
        self.wheel_circumference_ = math.pi * self.wheel_diameter


        self.sub_cmd_vel = rospy.Subscriber("/cmd_vel", Twist, self.callback_vel)
        self.sub_RobotMode = rospy.Subscriber('/matrix_mode_controller/mode', RobotMode, self.mode_callback) 
        self.sub_AllowMasterOn = rospy.Subscriber('/matrix_mode_controller/allowed_master_on', Bool, self.allowed_callback)
        self.pub_motor_state = rospy.Publisher("/matrix_canopen_motor/"+self.device_name+"/status_word", DeviceStateCanopen, queue_size=10)

        if not self.use_matrix_navgo_bypass:
            self.pub_can_sent = rospy.Publisher("/sent_messages", Frame, queue_size=10)
            self.sub_can_receive = rospy.Subscriber("/received_messages", Frame, self.can_recv_callback)
            self.init_canbus(self.can_device, str(self.can_bitrate))
            try:
                self.bus = can.Bus(interface='socketcan',
                                    channel=self.can_device,
                                    receive_own_messages=False,
                                    bitrate=self.can_bitrate)
            except:
                print("[matrix_CanOpenMotor_orientalBLVD-KRD]: cansocket name {} not found.please check list network interfaces".format(self.can_device))
                os.system('ifconfig')
                sys.exit(0)
        else:
            self.sub_can_receive = rospy.Subscriber("/matrix_io/canbus_send", Frame, queue_size=10)
            self.sub_can_receive = rospy.Subscriber("/matrix_io/canbus_receive", Frame, self.can_recv_callback)

        self.server = Server(MotorConfig, self.dyrecfg_callback)

        
        
        
        
        # can_filters = [{"can_id": 0x601, "can_mask": 0xFFF, "extended": False}]
        # self.bus.set_filters(can_filters)

        # self.buffer = can.BufferedReader()
        self.motor_status = DeviceStateCanopen()

        self.g_req_vel = Twist()
        self.g_prev_command_time = 0
        self.prev_control_time = 0        

        self.COMMAND_RATE = 20
        self.prev_rpm = 0
        self.timeout_state = 0
        self.speed_e = 0
        self._isMotor_1_OperationEn = False
        self._isMotor_2_OperationEn = False
        self._isFault_Detected = False
        self._isAllowed_Master_ON = False
        self._isAuto_mode = True
        self._isInitial_Manual = False
        self._isSkip_Allowed_Master_ON = False
        self._isManuaMode = False

        self.current_motor_state = "INIT"

        self.current_robotmode = RobotMode()

        self.ControlState = Enum('ControlState', ['INIT', 'MANUAL_MODE', 'ROBOT_SYSTEM_CHECK', 'MOTOR_STATE_CHECK', 'INIT_MOTOR', 'WAIT_STATUSWORD_ENABLED', 'BASE_CONTROL', 'GET_ACTUAL_VELOCITY', 'FINAL', 'FAULT_CHECKING', 'FAULT_DETECTED', 'CLEAR_FAULT', 'ERROR', 'PAUSE'])

        self.ControlState_seq = self.ControlState.INIT.value

        rate = rospy.Rate(50)

        while not rospy.is_shutdown():
            self.ControlLoop_StateMachine()
            # self.receive_canbus(0.01)
            rate.sleep()
        # After shutdown
        self.close_CANnMotor()

    def dyrecfg_callback(self, config, level):
        rospy.loginfo("""Reconfiugre Request: , {restart_motor}""".format(**config))
        self._isManuaMode = config.manual_mode
        self._isManuaMode = config.free_mode

        if config.restart_motor:
            self.disabled_dualMotor(True) 
            config.restart_motor = False
        
        # SDOsetAccelDecel(self.motor_2_id, config.)
        if config.accel_time != self.accel_time or config.decel_time != self.decel_time:
            self.accel_time = config.accel_time
            self.decel_time = config.decel_time
            self.disabled_dualMotor(False)
            time.sleep(1.0)
            self.init_dualMotor(False)
        else:
            pass
        return config
    
    def mode_callback(self, msg):
        self.current_robotmode = msg
    
    def allowed_callback(self, msg):
        self._isAllowed_Master_ON = msg.data 
    
    def callback_vel(self, msg):
        self.g_req_vel = msg
        self.g_prev_command_time = rospy.Time.from_sec(time.time()).to_nsec()
        try:
            if self.current_motor_state != "Enabled Operation":
                if self.g_req_vel.linear.x != 0.00 or self.g_req_vel.angular.z != 0.00:
                    rospy.logwarn("[matrix_CanOpenMotor_orientalBLVD-KRD]: Motor in <Switch on disabled> state cannot operation.Please go to <OPeration Enable> state")
                    self.stopBase()
                else:
                    pass
            else:
                pass
        except:
            pass
    

    def can_recv_callback(self, msg):
        message = msg
        # print(message.data)
        self.DiagnosticsStatusWordnPublish(message)
    
    def DiagnosticsStatusWordnPublish(self, message):

        try:
            frame_size_data= 0x00
            statusword_form = [0x4b, 0x41, 0x60, 0x00]
            if self.device_name =="ZLAC8015D":
                frame_size_data == 0x43
            else:
                frame_size_data == 0x4b

            if (message.data[0] == 0x4b or message.data[0] == 0x43) and message.data[1] == 0x41 and message.data[2] == 0x60 and message.data[3] == 0x00:
                # rospy.logwarn("status word {} {}".format(hex(message.data[5]), hex(message.data[4])))

                # message = [0x00, 0x00, 0x00, 0x00, 0x27, 0x13, 0x00, 0x00]
                sw_h = bytearray([message.data[4], message.data[5]])
                sw_d = unpack('<h', sw_h)
                sw_d = sw_d[0]
                sw_b = bin(sw_d)
                self.motor_status.binary = sw_b

                STW_ReadytoSwitchON = int(sw_b[len(sw_b)-1])
                STW_SwitchedON  = int(sw_b[len(sw_b)-2])
                STW_OperationEnabled = int(sw_b[len(sw_b)-3])
                STW_Fault = int(sw_b[len(sw_b)-4])
                STW_VoltageEnabled = int(sw_b[len(sw_b)-5])
                STW_QuickStop = int(sw_b[len(sw_b)-6])
                STW_SwitchONDisabled = int(sw_b[len(sw_b)-7])
                STW_Warning = int(sw_b[len(sw_b)-8])


                if STW_Fault:
                    # print("Fault")
                    self.current_motor_state = "Fault"
                    self.motor_status.state = DeviceStateCanopen.STATE_FAULT
                elif STW_ReadytoSwitchON and STW_SwitchedON and STW_OperationEnabled:
                    # print("Enabled Operation")
                    self.current_motor_state = "Enabled Operation"
                    self.motor_status.state = DeviceStateCanopen.STATE_OPERATION_ENABLED
                elif STW_SwitchONDisabled:
                    # print("Switch ON Disabled")
                    self.current_motor_state = "Switech on disabled"
                    self.motor_status.state = DeviceStateCanopen.STATE_SWITCH_ON_DISABLED
                else:
                    # print("UNKNOW")
                    self.current_motor_state = "UNKNOW"
                    self.motor_status.state = DeviceStateCanopen.STATE_UNKNOW

                
                # print("motor state ---- {}, mode {}".format(self.motor_status.text, self.motor_status.state))
                array = []
                array.append(message.data[4])
                array.append(message.data[5])

                self.motor_status.status_word = array
                
                
        except:
            pass
            # self.current_motor_state = "UNKNOW"
            # self.motor_status.state = DeviceStateCanopen.STATE_UNKNOW

        try:  
            # print(message.arbitration_id)
            if message.id == (0x080 + self.motor_1_id) or message.id == (0x080 + self.motor_2_id):
                self.current_motor_state = "Fault"
                self._isFault_Detected = True
                self.motor_status.state = DeviceStateCanopen.STATE_FAULT
                self.motor_status.fault_state = message.data
                self.motor_status.status_word = []
        except:
            self.current_motor_state = "UNKNOW"
            self.motor_status.state = DeviceStateCanopen.STATE_UNKNOW
        
        self.motor_status.text = self.current_motor_state    
        self.pub_motor_state.publish(self.motor_status)
    
    def receive_canbus(self, timeout):
        pass

    def ControlLoop_StateMachine(self):
        # print(self.ControlState_seq)
        self.SDO_SendReqStatusWordDualMotor()
        if self.device_name == "ZLAC8015D":
            # self.SDO_MotorSpin(self.dual_motor_id, req_motor_1, self.motor_1_id)
            # self.SDO_SendReqMotorActualSpeed(self.dual_motor_id)
            # self.SDO_MotorSpin(self.dual_motor_id, req_motor_2, self.motor_2_id)
            # self.SDO_SendReqMotorActualSpeed(self.dual_motor_id)
            # print(req_motor_1)
            self.SDO_SendReqMotorActualSpeed(self.motor_1_id)
            self.SDO_SendReqMotorActualSpeed(self.motor_2_id)
        else:
            # self.SDO_MotorSpin(self.motor_1_id, req_motor_1)
            # self.SDO_MotorSpin(self.motor_2_id, req_motor_2)
            self.SDO_SendReqMotorActualSpeed(self.motor_1_id)
            self.SDO_SendReqMotorActualSpeed(self.motor_2_id)
        

        if self._isManuaMode:
            if self.ControlState_seq != self.ControlState.MANUAL_MODE.value:
                self.disabled_dualMotor(False)
            self.ControlState_seq = self.ControlState.MANUAL_MODE.value
        else:
            pass

        # if self._isMotor_1_OperationEn != self._isMotor_2_OperationEn:

        if self.ControlState_seq == self.ControlState.INIT.value:
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: INIT")
            self.ControlState_seq = self.ControlState.MOTOR_STATE_CHECK.value
        
        elif self.ControlState_seq == self.ControlState.MANUAL_MODE.value:
            if not self._isManuaMode:
                rospy.logwarn("[matrix_CanOpenMotor_orientalBLVD-KRD]: Diabled motor switched to Auto Mode")
                self.disabled_dualMotor(False)
                self.ControlState_seq = self.ControlState.INIT.value
                # time.sleep(1.0)
                rospy.logwarn("[matrix_CanOpenMotor_orientalBLVD-KRD]: Go to --> Auto Mode success!")
            else:
                rospy.logwarn("[matrix_CanOpenMotor_orientalBLVD-KRD]: Robot in Manual Mode")
        
        elif self.ControlState_seq == self.ControlState.MOTOR_STATE_CHECK.value:
            
            # check incoming ID 080+ID
            # self.SDO_SendReqStatusWord(self.motor_1_id)
            # self.SDO_SendReqStatusWord(self.motor_2_id)
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: MOTOR_STATE_CHECK")
            # self.SDO_SendReqStatusWordDualMotor()
            self.ControlState_seq = self.ControlState.FAULT_CHECKING.value


        elif self.ControlState_seq == self.ControlState.ROBOT_SYSTEM_CHECK.value:
            rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: CHECKING ROBOT_SYSTEM_CHECK {}".format(self.ControlState_seq))

            

            if not self._isAllowed_Master_ON :
                if self._isMotor_1_OperationEn or self._isMotor_2_OperationEn:
                    # Transitions 11 + 12  | Status Machine "Operation enabled" -> "Switech on disabled"
                    self.disabled_dualMotor(False) 
                    self.ControlState_seq = self.ControlState.FINAL.value
                else:
                    self.ControlState_seq = self.ControlState.FINAL.value
            else:
                self.ControlState_seq = self.ControlState.FAULT_CHECKING.value
        
        
        
        elif self.ControlState_seq == self.ControlState.FAULT_CHECKING.value:
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: FAULT_CHECKING")
            if self._isFault_Detected or self.motor_status.state == DeviceStateCanopen.STATE_FAULT:
                rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Fault Detect. Disable dual motor !!!!!")
                if self._isMotor_1_OperationEn or self._isMotor_2_OperationEn:
                     # Transitions 11 + 12  | Status Machine "Operation enabled" -> "Switech on disabled"
                    self.disabled_dualMotor(True, self.ControlState.FAULT_CHECKING.value, self.ControlState.FAULT_DETECTED.value) 
                    # self.NMT_service(0x00, "Reset Node")
                    self._isFault_Detected = False
                    self.MotorSwitched(self.motor_1_id, "Fault Reset")
                    self.MotorSwitched(self.motor_2_id, "Fault Reset")
                    time.sleep(1.0)
                    self.motor_status.state = DeviceStateCanopen.STATE_SWITCH_ON_DISABLED
                else:
                    # pass
                     # Transitions 11 + 12  | Status Machine "Operation enabled" -> "Switech on disabled"
                    self.disabled_dualMotor(True, self.ControlState.FAULT_CHECKING.value, self.ControlState.FAULT_DETECTED.value) 
                    # self.NMT_service(0x00, "Reset Node")
                    self.MotorSwitched(self.motor_1_id, "Fault Reset")
                    self.MotorSwitched(self.motor_2_id, "Fault Reset")
                    self._isFault_Detected = False
                    time.sleep(1.0)
                    self.motor_status.state = DeviceStateCanopen.STATE_SWITCH_ON_DISABLED
                self.ControlState_seq = self.ControlState.FAULT_DETECTED.value
            else:
                self.ControlState_seq = self.ControlState.INIT_MOTOR.value

        elif self.ControlState_seq == self.ControlState.INIT_MOTOR.value:
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: CHECK INIT_MOTOR")
            if not self._isMotor_1_OperationEn and not self._isMotor_2_OperationEn:
                # Transitions 3 + 4 * | Status Machine "Switech on disabled" -> "Operation enabled"
                if self.init_dualMotor(True): 
                    self.ControlState_seq = self.ControlState.WAIT_STATUSWORD_ENABLED.value
                else:
                    self.ControlState_seq = self.ControlState.ERROR.value
                
            else:
                self.ControlState_seq = self.ControlState.BASE_CONTROL.value
        
        elif self.ControlState_seq == self.ControlState.WAIT_STATUSWORD_ENABLED.value:
            # print("WAIT_STATUSWORD_ENABLED")
            if self.motor_status.state == DeviceStateCanopen.STATE_OPERATION_ENABLED:
                self.ControlState_seq = self.ControlState.BASE_CONTROL.value
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: ************************************************    ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]:                                                     ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: CanOpenMotor orientalBLVD-KRD Ready To Drive!!!     ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]:                                                     ")
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: *************************************************   ")
        
        elif self.ControlState_seq == self.ControlState.BASE_CONTROL.value: 
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: BASE_CONTROL")
            # Status Machine in "Operation enabled"
            if self.motor_status.state == DeviceStateCanopen.STATE_OPERATION_ENABLED:
                self.main_control()
                self.ControlState_seq = self.ControlState.FINAL.value
            else:
                self.ControlState_seq = self.disabled_dualMotor(False, self.ControlState_seq, self.ControlState.FINAL.value)
        
        elif self.ControlState_seq == self.ControlState.FAULT_DETECTED.value:
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: FAULT_DETECT")
            
            self.ControlState_seq = self.ControlState.CLEAR_FAULT.value
        
        elif self.ControlState_seq == self.ControlState.CLEAR_FAULT.value:
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: CLEAR_FAULT")
            self.ControlState_seq = self.ControlState.INIT.value
        
        elif self.ControlState_seq == self.ControlState.FINAL.value:
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: FINAL")
                
            self.ControlState_seq = self.ControlState.INIT.value
        
        elif self.ControlState_seq == self.ControlState.PAUSE.value:
            # rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: PAUSE")
            # self.ControlState_seq = self.ControlState.INIT.value
            pass
        
        else:
            rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: UNKNOW")

        if not self._isAllowed_Master_ON :
            self.ControlState_seq = self.ControlState.ROBOT_SYSTEM_CHECK.value


    def init_dualMotor(self, reset_node):
        success = False
        # if self.NMT_service(0x00, "Reset Node"):
        #     time.sleep(1.0)
        if reset_node:
            self.NMT_service(0x00, "Reset Node")
            time.sleep(1.0)

        
        if self.device_name == "OrientalmotorBLVD_KRD":
            if self.init_motor(self.motor_1_id):
                self._isMotor_1_OperationEn = True
                # time.sleep(0.5)
            if self.init_motor(self.motor_2_id):
                self._isMotor_2_OperationEn = True
                # time.sleep(0.5)
            if self.NMT_service(0x00, "Switch to the <Operational> state"):
                success = True
        elif self.device_name == "ZLAC8015D":
            # print("AAAA")
            self.init_motor(self.dual_motor_id)
            self._isMotor_1_OperationEn = True
            self._isMotor_2_OperationEn = True
            success = True
        else:
            pass

        
        
        return success


    def disabled_dualMotor(self, reset, wait_state = 0 , next_state = 0):
        # rospy.logwarn("[matrix_CanOpenMotor_orientalBLVD-KRD]: Disabled dual motor sucess!!!")
        state = 0
        if self._isMotor_1_OperationEn or self._isMotor_2_OperationEn:
            
            if self.device_name == "ZLAC8015D":
                self.SDO_DisableOperationEnabled(self.dual_driver_motor)
                self._isMotor_1_OperationEn = False
                self._isMotor_2_OperationEn = False
            else:
                self.SDO_DisableOperationEnabled(self.motor_1_id)
                self._isMotor_1_OperationEn = False
                self.SDO_DisableOperationEnabled(self.motor_2_id)
                self._isMotor_2_OperationEn = False


            if reset:
                self.NMT_service(0x00, "Reset Node")
                time.sleep(1.0)
            pass
        else:
            if self.motor_status.state == DeviceStateCanopen.STATE_SWITCH_ON_DISABLED:
                state = next_state
            else:
                state = wait_state
        rospy.logwarn("[matrix_CanOpenMotor_orientalBLVD-KRD]: Disabled dual motor sucess!!!")
        
        return next_state

                    
        
    def main_control(self):
        # this block drives the robot based on defined rate
        if ((rospy.Time.from_sec(time.time()).to_nsec() - self.prev_control_time) >= (1000000000 / self.COMMAND_RATE)):
            self.moveBase()
            self.prev_control_time = rospy.Time.from_sec(time.time()).to_nsec()
        else:
            pass
        
        # this block stops the motor when no command is received
        if ((rospy.Time.from_sec(time.time()).to_nsec() - self.g_prev_command_time) >= 400000000):
            self.stopBase()
        else:
            pass
    
    def stopBase(self):
        self.g_req_vel.linear.x = 0.0
        self.g_req_vel.angular.z = 0.0
    
    def moveBase(self):
        # get the required rpm for each motor based on required velocities, and base used
        req_motor_1, req_motor_2 = self.calculateRPM(self.g_req_vel.linear.x, self.g_req_vel.angular.z)
        # print(req_motor_1)
        if self.device_name == "ZLAC8015D":
            self.SDO_MotorSpin(self.dual_motor_id, req_motor_1, self.motor_1_id)
            # self.SDO_SendReqMotorActualSpeed(self.dual_motor_id)
            self.SDO_MotorSpin(self.dual_motor_id, req_motor_2, self.motor_2_id)
            # self.SDO_SendReqMotorActualSpeed(self.dual_motor_id)
            # print(req_motor_1)
            self.SDO_SendReqMotorActualSpeed(self.motor_1_id)
            self.SDO_SendReqMotorActualSpeed(self.motor_2_id)
        else:
            self.SDO_MotorSpin(self.motor_1_id, req_motor_1)
            self.SDO_MotorSpin(self.motor_2_id, req_motor_2)
            self.SDO_SendReqMotorActualSpeed(self.motor_1_id)
            self.SDO_SendReqMotorActualSpeed(self.motor_2_id)
        
    
    def calculateRPM(self, linear_x, angular_z):
    
        # convert m/s to m/min
        linear_vel_x_mins = linear_x * 60
        linear_vel_y_mins = 0

        # convert rad/s to rad/min
        angular_vel_z_mins = angular_z * 60
        
        tangential_vel = angular_vel_z_mins * ((self.wheels_x_distance_ / 2) + (self.wheels_y_distance_ / 2))

        x_rpm = linear_vel_x_mins / self.wheel_circumference_
        y_rpm = linear_vel_y_mins / self.wheel_circumference_
        tan_rpm = tangential_vel / self.wheel_circumference_

        # calculate for the target motor RPM and direction
        # left motor
        # rpm_motor_right = -(x_rpm + y_rpm + tan_rpm)

        rpm_motor_right = -(x_rpm + y_rpm + tan_rpm)

        # right motor
        rpm_motor_left = x_rpm + y_rpm - tan_rpm
        

        # calculate with gear box 
        rpm_motor_left = rpm_motor_left * self.gear_ratio
        rpm_motor_right = rpm_motor_right * self.gear_ratio 

        rpm_motor_left = min(self.max_motor_rpm, max(-self.max_motor_rpm, rpm_motor_left))
        rpm_motor_right = min(self.max_motor_rpm, max(-self.max_motor_rpm, rpm_motor_right))

        value_motor_left = rpm_motor_left
        value_motor_right = rpm_motor_right

        # print("[matrix_CanOpenMotor_orientalBLVD-KRD]: MotorLeft(1) {} RPM, MotorRight(2) {} RPM".format(round(rpm_motor_left), round(rpm_motor_right)))

        
        return [value_motor_left, value_motor_right]
    

    #*********************************************************#
    #
    #
    #               Motor control API                     
    #
    #
    #*********************************************************#
    def init_motor(self, MotorID): # Transitions 3 + 4 *
        success = False

        # set Acceleration & Deceleration time
        # for Driver -> ZLAC8015D
        if self.device_name == "ZLAC8015D":
             # set Asynchronoous control only dual motor driver
            self.SDOsetModeDualDrive_SyncAsynMode(MotorID, "asynchronous")
            time.sleep(0.1)
            # set Profile Velocity Mode
            self.SDO_ModeofOperation(MotorID, "Profile Velocity Mode")
            time.sleep(0.1)
            self.SDOsetAccelDecelCAN(MotorID, self.accel_time, self.decel_time, index_motor=self.motor_1_id)
            time.sleep(0.1)
            self.SDOsetAccelDecelCAN(MotorID, self.accel_time, self.decel_time, index_motor=self.motor_2_id)
            time.sleep(0.1)
        # for CANOPEN Motor driver -> SmartrisLefertDrives, OrientalmotorBLVD_KRD
        else:
            # set Profile Velocity Mode
            # self.SDO_ModeofOperation(MotorID, "Profile Velocity Mode")
            # time.sleep(0.1)
            self.SDOsetAccelDecelCAN(MotorID, self.accel_time, self.decel_time)
            # time.sleep(0.1)
        
        # Go to --> Operation Enable
        #                                                              Follow instructions HP-5143E.pdf page 33 [5.1 Status Machine]
        #                                                                              current Status Machine 
        #                                                                                Switch on disabled
        if self.MotorSwitched(MotorID, "Shutdown"):                 #Transitions 2 --->  Ready to switch on
            # time.sleep(0.1)
            if self.MotorSwitched(MotorID, "Switch ON"):            #Transitions 3 --->  Switched on
                # time.sleep(0.1)
                if self.MotorSwitched(MotorID, "Enable Operation"): #Transitions 4 --->  Operation enabled
                    success = True
                    rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: Initial Motor-ID {} success!!!".format(MotorID))
                else:
                    rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Error Enable Operation Motor-ID {} ".format(MotorID))
            else:
                rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Error Switch ON Motor-ID {} ".format(MotorID))
        else:
            rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Error Shutdown Motor-ID {} ".format(MotorID))
        return success

    def SDOsetModeDualDrive_SyncAsynMode(self, MotorID, mode):
        success = False
        if self.device_name == "ZLAC8015D":
            if mode == "asynchronous":
                data_frame = [0x2b, 0x0f, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00]
                print("trigASy")
                success = True
            elif mode == "synchronization":
                data_frame = [0x2b, 0x0f, 0x20, 0x00, 0x01, 0x00, 0x00, 0x00]
                success = True
            else:
                rospy.logerr(mode)
                rospy.logwarn("not found")
                success = False
        else:
            pass

        if success:
            success = self.SendToCan(0x600 + MotorID, data_frame)
        
        return success
    
    def SDOsetAccelDecelCAN(self, MotorID, accel, decel, index_motor=-1):
        rospy.loginfo("set accel motor_id:{}, accel:{}, index_motor:{}".format(MotorID, accel, index_motor))
        sub_index = 0x00
        # for Driver -> ZLAC8015D
        if self.device_name == "ZLAC8015D":
            sub_index = index_motor
        # for CANOPEN Motor driver -> SmartrisLefertDrives, OrientalmotorBLVD_KRD
        else:
            sub_index = 0x00

        #Dec to Hex 4 byte LSB->MSB
        #set Acceleration 6083h
        value_hex = struct.pack('<i', int(accel))
        data_frame = [0x23, 0x83, 0x60, sub_index, value_hex[0], value_hex[1], value_hex[2], value_hex[3]]
        for x in data_frame:
            print(hex(x))
        success = self.SendToCan(0x600 + MotorID, data_frame)
        #set Deceleration 6084h
        value_hex = struct.pack('<i', int(decel))
        data_frame = [0x23, 0x84, 0x60, sub_index, value_hex[0], value_hex[1], value_hex[2], value_hex[3]]
        print(data_frame)
        for x in data_frame:
            print(hex(x))
        success = self.SendToCan(0x600 + MotorID, data_frame)
        
    
    def SDOclearErrorDualMotor(self):
        # for Driver -> ZLAC8015D
        if self.device_name == "ZLAC8015D":
            self.SDO_clearError(self.dual_motor_id)
        # for CANOPEN Motor driver -> SmartrisLefertDrives, OrientalmotorBLVD_KRD
        else:
            self.SDO_clearError(self.motor_1_id)
            self.SDO_clearError(self.motor_2_id)

    def SDO_clearError(self, MotorID):
        success = False
        if self.device_name == "OrientalmotorBLVD_KRD":
            data_frame = [0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00]
        elif self.device_name == "ZLAC8015D":
            data_frame = [0x2b, 0x40, 0x60, 0x00, 0x80, 0x00, 0x00, 0x00]
        success = self.SendToCan(0x600 + MotorID, data_frame)
        return success

    
    def MotorSwitched(self, MotorID, cmd):
        success = True
        data = 0x00
        # follow HP-5143E.pdf page 34 [6 Status Machine control commands]
        if cmd == "Shutdown":                        #Transitions 2, 6, 8   “Shutdown” command received from controlword.
            data = 0x06
        elif cmd == "Switch ON":                     #Transitions 3         “Switch On” command received from controlword.
            data = 0x07
        elif cmd == "Switch ON + Enable Operation":  #Transitions 3, 4*     
            data = 0x0F
        elif cmd == "Disable Voltage":               #Transitions 7, 9, 10, 12
            data = 0x00
        elif cmd == "Quick Stop":                    #Transitions 7, 10, 11
            data = 0x02
        elif cmd == "Disable Operation":             #Transitions 5         “Disable operation” command received from controlword.
            data = 0x03
        elif cmd == "Enable Operation":              #Transitions 4, 16     “Enable Operation” command received from controlword.
            data = 0x0F 
        elif cmd == "Fault Reset":                   #Transitions 15
            data = 0x80
        else:
            success = False
        # * Automatic transition to enable operation state after executing switched on state functionality.
        if success:
            data_frame = [0x2B, 0x40, 0x60, 0x00, data, 0x00, 0x00, 0x00]
            success = self.SendToCan(0x600 + MotorID, data_frame)
            if success:
                rospy.loginfo("[matrix_CanOpenMotor_orientalBLVD-KRD]: Succcess set Status Machine control commands Motor-ID {}, cmd {}".format(MotorID, cmd))
            else:
                rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Fail set Status Machine control commands Motor-ID {}, cmd {}".format(MotorID, cmd))
        else:
            rospy.logerr("[matrix_CanOpenMotor_orientalBLVD-KRD]: Not found Status Machine control commands cmd {}".format(cmd))

        return success
    
    def SDO_MotorSpin(self, MotorID, target_vel, index_motor=-1):
        success = False

        #Dec to Hex 4 byte LSB->MSB
        vel_hex = struct.pack('<i', int(target_vel))

        # for Driver -> ZLAC8015D
        if self.device_name == "ZLAC8015D":
            data_frame = [0x23, 0xff, 0x60, index_motor, vel_hex[0], vel_hex[1], vel_hex[2], vel_hex[3]]
            # print(data_frame)
        # for CANOPEN Motor driver -> SmartrisLefertDrives, OrientalmotorBLVD_KRD
        else:
            data_frame = [0x23, 0xff, 0x60, 0x00, vel_hex[0], vel_hex[1], vel_hex[2], vel_hex[3]]
        success = self.SendToCan(0x600 + MotorID, data_frame)
        return success
    
    def SDO_ModeofOperation(self, MotorID, mode):
        success = False
        data_frame = []
        if mode == "Profile Velocity Mode":
            data_frame = [0x2f, 0x60, 0x60, 0x00, 0x03, 0x00, 0x00, 0x00]
            success = True
        else:
            success = False
        
        if success:
            success = self.SendToCan(0x600 + MotorID, data_frame)
        return success

    def SDO_SendReqMotorActualSpeed(self, MotorID):
        # for Driver -> ZLAC8015D
        if self.device_name == "ZLAC8015D":
            # ZLAC8015D/ZLAC8015D CANopen Communication Routine V1.05.pdf
            # ZLAC8015D Serv vo Driver (Special for Hub Servo Motor) CANopen Communication Routine Version 1.05 | Page 17
            # Index 606Ch, Subindex 0x01, 0x02
            # Left and right target speed combination Low 16bits is left motor, High 16bits is rgiht motor 
            # current speed of motor unit is 0.1r/min
            data_frame = [0x40, 0x6c, 0x60, MotorID, 0x00, 0x00, 0x00, 0x00]
            MotorID = self.dual_motor_id
        # for CANOPEN Motor driver -> SmartrisLefertDrives, OrientalmotorBLVD_KRD
        else:
            data_frame = [0x40, 0x6c, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00]
        success = self.SendToCan(0x600 + MotorID, data_frame)
        return success

    def SDO_SendReqStatusWordDualMotor(self):
        # for Driver -> ZLAC8015D
        if self.device_name == "ZLAC8015D":
            self.SDO_SendReqStatusWord(self.dual_driver_motor)
        # for CANOPEN Motor driver -> SmartrisLefertDrives, OrientalmotorBLVD_KRD
        else:
            self.SDO_SendReqStatusWord(self.motor_1_id)
            self.SDO_SendReqStatusWord(self.motor_2_id)

    def SDO_SendReqStatusWord(self, MotorID):
        data_frame = [0x40, 0x41, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00]
        success = self.SendToCan(0x600 + MotorID, data_frame)
        return success
    
    def SDO_DisableOperationEnabled(self, MotorID): # Transitions 11 -> 12
        success = False
        # Transitions 11
        # - “Quick Stop” command received from controlword.
        # - “QSTOP signal input” is active. (break)
        if self.MotorSwitched(MotorID, "Quick Stop"):   
            # Transitions 12
            # - “Quick Stop” function is completed or “Disable Voltage” command received from controlword
            # - “HWTO signal input” is active
            if self.MotorSwitched(MotorID, "Disable Voltage"):
                success = True
        return success

    # Follow instructions HP-5143E.pdf page 17 [NMT Communication Objects]
    def NMT_service(self, MotorID, cmd):
        success = True
        COB_ID = 0x00
        Byte0_cmd = 0x00
        Byte1_NodeID = MotorID
        if cmd == "Switch to the <Operational> state":
            Byte0_cmd = 0x01
        elif cmd == "Switch to the <Stoped> state":
            Byte0_cmd = 0x02
        elif cmd == "Switch to the <Pre-operational> state":
            Byte0_cmd = 0x80
        elif cmd == "Reset Node":
            Byte0_cmd = 0x81
        elif cmd == "Reset Communication":
            Byte0_cmd = 0x82
        else:
            success = False
        
        if success:
            data_frame = [Byte0_cmd, MotorID]
            success = self.SendToCan(COB_ID, data_frame)
        else:
            pass

        return success

                  
    

    #*********************************************************#
    #
    #
    #               CanOpen Utility                     
    #
    #
    #*********************************************************#
    
    def SendToCan(self, MotorID, DataFrame):
        success = True
        # can_msg = Frame()
        # can_msg.id = int(0x601)
        # array = []
        # for data in DataFrame:
        #     array.append(int(data))
        # for x in range(8-len(array)):
        #     array.append(0)
        # can_msg.data = array
        # can_msg.dlc = len(array)
        # self.pub_can_sent.publish(can_msg)
        if not self.use_matrix_navgo_bypass:
            try:
                # data_frame = struct.pack('<i', int(req_value_left))
                message = can.Message(  arbitration_id=MotorID, 
                                        is_extended_id=False, 
                                        data=DataFrame)
                self.bus.send(message, timeout=1.0)
            except:
                print("cannot send command to Canbus")
                success = False
                # sys.exit(1) 
        else:
            message = Frame()
            message.id = MotorID
            message.is_rtr = False  
            message.is_extended = False
            message.is_error = False
            message.dlc = len(DataFrame)
            message.data = DataFrame

        return success

    

    def close_CANnMotor(self):
        # self.MotorSwitched(1, "Disable Voltage")
        # self.MotorSwitched(2, "Disable Voltage")
        if self.device_name == "ZLAC8015D":
            self.SDO_DisableOperationEnabled(self.dual_driver_motor)
        else:
            self.SDO_DisableOperationEnabled(self.motor_1_id)
            self.SDO_DisableOperationEnabled(self.motor_2_id)
        self.NMT_service(0x00, "Reset Node")
        if not self.use_matrix_navgo_bypass:
            print ("[matrix_CanOpenMotor_orientalBLVD-KRD]: Force down can0")
            os.system('echo \"a\" | sudo -S ip link set can0 down')
        else:
            pass
    
    def init_canbus(self, can_device, bitrate):
        print ("[matrix_CanOpenMotor_orientalBLVD-KRD]: Force down {}".format(can_device))
        os.system('echo \"a\" | sudo -S ip link set '+ can_device +' down')
        print("")
        # time.sleep(1.0)
        print ("[matrix_CanOpenMotor_orientalBLVD-KRD]: Bringup {}".format(can_device))
        os.system('echo \"a\" | sudo -S ip link set '+ can_device +' up type can bitrate ' + bitrate)
        # time.sleep(0.5)
        # self.NMT_service(0x00, "Reset Node")
        # print("")
        print ("[matrix_CanOpenMotor_orientalBLVD-KRD]: {} bringup success!!!".format(can_device))



    # def callback_reset_counter(self, req):
    #     if req.data:
    #         self.counter = 0
    #         return True, "Counter has been successfully reset"
    #     return False, "Counter has not been reset"
if __name__ == '__main__':
    rospy.init_node('number_counter')
    NumberCounter()
    rospy.spin()
